### ISSUE TITLE
Demo Simple Checkout does not work

### ISSUE THREAD

**Issue by Moowalker** [VivaPayments/API#1066]
Trying to test the simple checkout (https://developer.vivawallet.com/online-checkouts/simple-checkout/) with the demo HTML provided. After I enter the credit card and all othe info correct the 3ds windows tries to open but it fails with the following error: 

`Mixed Content: The page at 'https://demo.vivapayments.com/web/checkout/simplecheckout?publickey=5f2kM9bl8iARIHy8aCQILOZr5XzR%2FBqbDvm6xHVeXy4%3D&amount=1000&lang=en&baseurl=https%3A%2F%2Fdemo.vivapayments.com&description=My+product' was loaded over HTTPS, but requested an insecure form action 'http://demo.vivapayments.com/web/checkout/threedsecurevalidation'. This request has been blocked; the content must be served over HTTPS.`

As is seems the redirect is done to http instead of https.

**Comment by matthewrgourd** [comment]
Hi @Moowalker we believe the issue may be due to some of our code samples being out of date and still mentioning http for the demo environment. I will adjust these as soon as possible but in the meantime if you could replace any instances of *http*://demo.vivapayments.com with **https**://demo.vivapayments.com ? Thank you!
