### ISSUE TITLE
No redirection after payment

### ISSUE THREAD

**Issue by thanosge** [VivaPayments/API#1087]
Hello,
After successful payment I don't get redirected to the website and the order is not completed. However the amount is drawn from the customer.

![Screenshot_1](https://user-images.githubusercontent.com/44574548/65332915-3b849e80-dbc8-11e9-9b65-0eaecfb7bc07.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/44574548/65332918-3c1d3500-dbc8-11e9-95d4-baede164ca0a.jpg)

This is the page that I get after completing the payment.
![Screenshot_2](https://user-images.githubusercontent.com/44574548/65332911-3aec0800-dbc8-11e9-8a9d-beb2a4fd3734.jpg)

**Comment by VivaWalletSupport** [comment]
Hello, specify the Source Code (9148) in your plugin settings.

**Comment by thanosge** [comment]
Added that but now it doesn't take me to the viva payment page. It takes me to this page

![Screenshot_3](https://user-images.githubusercontent.com/44574548/65334504-2d844d00-dbcb-11e9-9c7b-3fd68c4a9eff.jpg)

It says "Thank you for your order, please click the button bellow to pay" but there is no button bellow...

**Comment by VivaWalletSupport** [comment]
Please provide following screesnhots and we will look into the issue:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by thanosge** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/44574548/65335845-dcc22380-dbcd-11e9-9b2f-96f64632f02e.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/44574548/65335848-dd5aba00-dbcd-11e9-893e-531520314a33.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/44574548/65335852-ddf35080-dbcd-11e9-8b20-39dd09ddd383.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/44574548/65335853-df247d80-dbcd-11e9-9da3-43290b879e83.jpg)

**Comment by VivaWalletSupport** [comment]
Please check you have not inserted any unwanted spaces with the source code in the plugin settings. Also check if anything is logged in your PHP errror log.

**Comment by lobtx** [comment]
Hi everyone, I was about to create an issue but there's no need I guess as I am facing the same issue than thanosge.

Every thing is set according to https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ tutorial.

I'm correctly led to 3DS payment window, I receive the confirmation code SMS, but when I validate the payment I'm stuck to this viva pay page which becomes totally white, and get no redirection to my website.

I got no issue with any other payment means (bank transfer, check,...).
I checked the plugin configuration and got no blank in any fields.

Like thanosge my order is not completed (still waiting for payment) and no cash is provided to my viva wallet.
My bank does not send me the SMS I usually receive after my VISA payments are achieved.

Do you need further information? This issue is quite blocking. 

Thanks
