### ISSUE TITLE
Πρόβλημα με shopify και viva payment

### ISSUE THREAD

**Issue by harris84firefox** [VivaPayments/API#1103]
Γειά σας,
έχουμε ένα ηλεκτρονικό κατάστημα σε shopify και έχουν γίνει 12 επιτυχημένες πωλήσεις με την VIVA τους τελευταίους 2 μήνες. Χτες όμως έγινε κάτι πολύ περίεργο. Πελάτης πήγε να πληρώσει, η πληρωμή έγινε κανονικά και η παραγγελία δεν εμφανίστηκε ποτέ στο shopify. Κατά τύχη είδαμε μια πληρωμή στο site της viva. Μετά από τηλεφωνική επικοινωνία με τον πελάτη μας είπε ότι το site της viva κόλησε κατά την διάρκεια της πληρωμής. Το να κολήσει ένα site μπορεί να γίνει καμιά φορά, το αδικαιολόγητο ήταν ότι τράβηξε τα χρήματα από τον πελάτη, χωρίς να έχουμε ΚΑΜΙΑ ειδοποίηση. Δεν γίνεται κάθε μέρα να μπαίνω στο site της VIVA και να ελέγχω μήπως έχω καμία παραρρελία που δεν έχει εμφανιστεί στο shopify. Ο κωδικός της συναλλαγής είναι 11286104178778 στις 25/6

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this but I'm not sure if what you were advised is correct. Your Shopify website only uses Viva Wallet as a payment gateway so I believe it is more likely that the former was hacked. However, I'll get in touch with our Shopify developer and see if he can shed any light on it. Thanks!

**Comment by harris84firefox** [comment]
former was hacked -> Έχω ενεργοποιήσει two-factor authentication και καμία άγνωση ip δεν έχει συνδεθεί στο shopify κατάστημά μου σαν διαχειριστής. Επίσης, είναι αδύνατο να μεταφέρεις μια παραγγελία στα abandoned checkouts στο shopify. Είναι τραγικό να μου δίνεις σαν μόνη σοβαρή απάντηση ότι μπήκε hacker στο κατάστημά μου ενώ έχει κολήσει το σύστημά σας.

**Comment by matthewrgourd** [comment]
@harris84firefox Sorry for the delay getting back to you. Our [status page](https://status.vivawallet.com/history?page=2) tells me all our systems were up and running on 25/6. Is **Use test mode** deselected in the below dialog box? It should be in order to avoid such an issue. 
![VivaWalletPaymentProvider](https://user-images.githubusercontent.com/44943019/65031089-88eadc80-d938-11e9-8f9a-229f816addf4.png)

If that's not the problem, please let me have further details about your setup.

Alternatively, I noticed this article in the Shopify help pages which may or may not be relevant to your problem: https://community.shopify.com/c/Payments-Shipping-Fulfillment/orders-not-shown/td-p/501805

**Comment by harris84firefox** [comment]
Test mode is deselected from the beginning of our website (only selected the first day)

**Comment by matthewrgourd** [comment]
Hi @harris84firefox, our Shopify plugin expert has come back with the following:

> If the payment page did not respond after payment, maybe the client network was lost. I'd recommend that the merchant enables the payment notification for his account, so we will receive an email each time a payment is made. This way they won't miss a payment, in the rare case this happens again.

Hope this helps!
