### ISSUE TITLE
403 ERROR PaymentsPolicyCreditRestriction

### ISSUE THREAD

**Issue by marketima** [VivaPayments/API#1116]
hi,
yesterday i complete integration and had successful charge
with my vivawallet account. (180euro)

today i try to work and it failed several times

i got that response from vivawallet to my server:

ERROR 403 PaymentsPolicyCreditRestriction

can you please tell me why and HELP me?

regrads

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Can you send through the account or business name and the first 8 digits of your merchant ID. Are you testing on live or demo?

**Comment by marketima** [comment]
sorry for the delay.
it was fixed(the 403 error).

but today i see :

"Payment Error: Error 405': Action blocked due to security policy
it is viva"

my marchent ID is: 2eab15be-51b3-4676-90d1-dca0be62b8d9

thx for your help.

**Comment by marketima** [comment]
i'm using live by the way

**Comment by matthewrgourd** [comment]
Hi there, thanks for this. I've made a note of your merchant ID but if you don't mind I'm going to remove part of it from your post on this public forum for security reasons. I can't see anything on your account that immediately shows what the problem is. If possible, can you send through screenshots of any request / response logs with confidential information blanked? Thanks!

**Comment by marketima** [comment]
this is what i see by answer from VIVA:

"Payment Error: Error 405': Action blocked due to security policy
it is viva"

**Comment by marketima** [comment]
payment api - Native checkout v1

**Comment by matthewrgourd** [comment]
Hi @marketima, Native Checkout v1 has been deprecated, please follow these instructions to migrate to v2: https://developer.vivawallet.com/online-checkouts/migrating-from-native-checkout-v1/
