### ISSUE TITLE
Redirect checkout

### ISSUE THREAD

**Issue by eranfl** [VivaPayments/API#1120]
Hi, 
I've implemented the redirect checkout by when clicking a button it will redirect to the payment page. Everything loads OK but after I click the "charge" button, it just hangs (as shown in the attached image).

I checked the console and there are no errors (I allowed a load of unsafe scripts as well...)

![image](https://user-images.githubusercontent.com/16452344/66321017-8e7c8680-e928-11e9-9acd-0a1df05b99b3.png)

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. In the event that you are attempting a test transaction within the demo environment, please see reply from one of our lead developers to a similar query: 

https://github.com/VivaPayments/API/issues/1073#issuecomment-532243393

> Unfortunately, currently, there are no card numbers that trigger the 3DS window and are able to
successfully complete a payment . This is due to the fact that these are just dummy card numbers and can't be validated correctly within our system. I understand that this can be quite confusing (and it is) to most people trying to integrate with Native Checkout v2. We are currently working towards implementing a dummy issuer's/3DS window to allow better control to API/Native Checkout v2 consumers over cardholder authentication process during the integration phase, but it might be a while till this reaches demo environment.

>A suggested workaround is to use the 4111 card along with the authenticateCardholder param set to false, as shown [here](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-4-request-a-charge-token). This will essentially skip 3DS authentication and complete the payment. If you've already handled the authentication window in your JS code then you are fine to follow this approach.
