### ISSUE TITLE
Demo api registration error

### ISSUE THREAD

**Issue by devtst** [VivaPayments/API#1126]
Hello 
i am trying to create an account for the demo api (https://demo.vivapayments.com/el/signup) but i getting the error "Registration cannot be completed".
The response from server is  {FriendlyMessage: "SecurityMerchantValidationFailed: Invalid categoryCode"}
The selected category is "**Digital Goods—Software Applications (Excluding Games)**"

How to solve this issue and complete the registration?

Thank you in advance.

![demo error](https://user-images.githubusercontent.com/56337450/66458703-13c48000-ea7c-11e9-96d6-ce52c6f4529b.jpg)

**Comment by matthewrgourd** [comment]
Hi @devtst I couldn't recreate this problem. Is it still an issue or have you now created your demo account?

**Comment by matthewrgourd** [comment]
Hi @devtst, you can create as many demo accounts as you like, just vary the mobile number at registration (doesn't have to be real as we don't need to send any verification texts unless you are registering for production). The error you're receiving is because you attempted to set up a new account with a previously registered mobile number. I've checked more than once and there's definitely no issue at the Viva Wallet end. Hope this helps! Am closing this issue now.
