### ISSUE TITLE
Native checkout v2 preauth EXPLOIT

### ISSUE THREAD

**Issue by Stratubas** [VivaPayments/API#1282]
Hello again.

Charge tokens generated at
https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens

have an "Amount". This is the amount that I see in the bank's authorisation page.

However, when making a transaction with preauth at
https://demo-api.vivapayments.com/nativecheckout/v2/transactions

there is another "amount". This appears to be the actual payment amount.

The first "Amount" seems to be completely irrelevant.

For example, I created a charge token with 100 cents as "Amount",
then created a transaction with 9900 cents as "amount",
and successfully captured 99 euros, even though a charge of only 1 euro was authorised.

Am I doing something wrong?

**Comment by matthewrgourd** [comment]
Hi @Stratubas, I need to check your query with a developer. I'll get back to you when I've an answer.

**Comment by matthewrgourd** [comment]
Hi @Stratubas, our dev team has got back to me and apparently you did everything correctly. The purpose of passing the 3DS authentication when creating a charge token is to verify that the card is not stolen and that the actual cardholder is making the transaction. That's why it is mandatory to pass a two-factor authentication (Otp, biometrics etc.) There is no reason to reject the transaction. However, this is our particular implementation, so there's a small possibility that the transaction will be rejected from the issuer bank.
