### ISSUE TITLE
Native checkout v2 - how to reuse a card - is 3DS mandatory

### ISSUE THREAD

**Issue by Stratubas** [VivaPayments/API#1283]
We were requested to have our mobile apps updated to use native checkout v2.

Going through the documentation at
https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

it doesn't seem that a card can be used more than once.

In our existing mobile app, which uses an older viva API, the "transaction_id" could be used to use the same card multiple times. Is there anything similar in v2?

It also appears that 3DS is not optional. Is that true? We wouldn't want to change the app's flow (to show the bank's web view), if it's not necessary.

**Comment by matthewrgourd** [comment]
Hi @Stratubas, I need to check your query with a developer. I'll get back to you when I've an answer.

**Comment by matthewrgourd** [comment]
Hi @Stratubas I've consulted with our dev team and here is a summary of their response:

1. The ability to tokenize a card in order to reuse it multiple times was temporarily removed before Christmas hence why the dev portal no longer mentions it. The feature has now been reinstroduced and I've provided a temporary write-up here: https://github.com/VivaPayments/API/issues/1256#issuecomment-572530964 I'll be updating the documentation with a similar explanation in the next few days. Right now, recurring transactions, which you alluded to, are disabled. However, you can use the above procedure to achieve the same result.

2. 3DS isn't optional, it's a requirement of the latest addition to PSD2 which is (SCA) Strong Customer Authentication. This had to be adhered to from 14th September 2019.

Hope this helps!
