### ISSUE TITLE
Card Tokenization & Create Order (Newsphone Hellas)

### ISSUE THREAD

**Issue by staran001** [VivaPayments/API#1317]
Hello,

We would like to know if there are any changes regarding the endpoints for 
/api/orders and /api/cards with the native checkout v2 changes.
More specifically, we have a mobile application that creates an order and tokenizes the card of the user. The token and the order are then sent to a server to finish the checkout procedure.
Is there something we need to change regarding the mobile application ?
Maybe the new checkout flow, requires more information or something else ?

Thank you.

**Comment by matthewrgourd** [comment]
Hi there, there have been some changes since the start of January. The up-to-date information you need is at the following locations on our developer portal:

https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

https://developer.vivawallet.com/api-reference-guide/native-checkout-v2-api/

https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/

**Comment by staran001** [comment]
So if i understand correctly, the card tokenization API is also changed ?

**Comment by matthewrgourd** [comment]
Hi @staran001 creating a payment order is exactly the same as before but card tokenization has changed slightly. All the documentation you need is as above.

**Comment by staran001** [comment]
Hello again, i would like to ask if the old way of making payments will be working as well as the new native checkout flow.
This guide here [](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/) does not contain the order creation part. Is the order creation something else ? or is it just omitted ?
