### ISSUE TITLE
Problem with online payments gateway

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1318]
Hi @matthewrgourd Can you help me with this customer B87434361 because he tell me that more of 50% transactions online payments are wrong. The problem is when the customers of this merchant try to buy things by online payments the system don't allow use the majority of the cards.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada , thanks for raising. Please email me with the customer’s Merchant ID, business name and the relevant website address, referencing this issue (#1318): mgourd@vivawallet.com I will then investigate. Thanks!

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd I wrote you the mail with data that you asked me. He is using prestashop 1.7

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada , thanks for your email. I can't see any obvious issues with their account. As previously requested, please confirm which of our online checkouts or e-commerce plugins the merchant is using to take payments. Thanks!

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I looked at the account again and it was only fully approved by us for e-commerce on 2nd Jan 2020. The only failed transactions since then have been due to the card issuer (problem with customer's card) not our platform. I've looked at the e-commerce website of the merchant and it doesn't look like our plugin is currently in use, but I may be wrong. If the merchant is still having issues and is definitely using the Viva Wallet plugin for Prestashop please get them to send through the following screenshots:

* Payment module settings from Prestashop (mask the API Key).
* Viva Wallet [payment source settings](https://developer.vivawallet.com/images/NewPaymentSource.png) (include the browser's URL in the screenshot).
* Viva Wallet [Websites/Apps page](https://developer.vivawallet.com/images/WebsitesSubmenu.png?classes=border&width=900) (include the browser's URL in the screenshot).
* [API Access page](https://developer.vivawallet.com/images/API%20Access.png?classes=border&width=900) (mask API Key (include the browser's URL in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Closing as no recent reply.
