### ISSUE TITLE
Store not found - Shopify 

### ISSUE THREAD

**Issue by Neyonis** [VivaPayments/API#1342]
Hello, 

I can't paid on my website. I have the message Error - store not found ... 
The account is fully verified and i followed your guide to install Viva wallet, the test mode is not selected.. 
Could you help me ?

**Comment by matthewrgourd** [comment]
Hi @Neyonis, this usually happens because a wrong entry has been made for Merchant ID in the Shopify settings. Please see below illustration of what needs to be done. For instructions on finding your Merchant ID, see https://www.vivawallet.com/wp-content/uploads/2019/03/how-to-find-merchant-id-2.png

![viva-wallet-payment-provider-settings](https://user-images.githubusercontent.com/44943019/73534911-4246dc00-441a-11ea-9d93-2c349626beb4.png)

**Comment by Neyonis** [comment]
Hi @matthewrgourd thanks you, i already have the Merchand ID but i can't find the store token 
i send an email

**Comment by Neyonis** [comment]
Hey ! now with the store token (missing it) it's working very well ! thanks a lot
