### ISSUE TITLE
[Woocommerce] Loading payment page failing 

### ISSUE THREAD

**Issue by lobtx** [VivaPayments/API#1372]
Hi,

I have a woo-commerce based e-shop using WooCommerce Vivawallet Gateway plugin (3.5.7).
About 40% of my clients cannot reach the 3DS payment page even after waiting 5 minutes. The problem appears in both desktop and mobile common browsers (Mozilla, Chrome, IE).

I've made several tests myself, sometimes the page is loaded in a few seconds, sometimes in a few minutes (which is really too much for a buyer), and sometimes it never shows up.

I've checked every configuration in WP plugin and viva wallet sources but I find nothing relevant.

Can I send you screens of my confs so you can help me to figure it out ?

I use the Redirection/Native checkout v2 feature. 

Much thanks

Loris

**Comment by matthewrgourd** [comment]
Hi @lobtx, sorry to hear this. Do you have the live web address of your e-commerce site? Also, if you could email me the business name and Merchant ID? Email address is mgourd@vivawallet.com. Thanks!

**Comment by matthewrgourd** [comment]
Hi @lobtx did you try to email me because I think I may have missed you? Please try emailing me the requested details (business name and Merchant ID) again so I can check your account before investigating further. You'll need to reference this issue (#1372). Email address is mgourd@vivawallet.com Thanks!

**Comment by lobtx** [comment]
Hi

My bad, I used a wrong address, I just sent you again the information you asked. I'm about to send you screenshots of my configs.
Thanks !

**Comment by matthewrgourd** [comment]
Hi @lobtx thanks for sending through that information. As I stated in my email, we believe the variations that you're finding relate to customer cards rather than to the Viva Wallet payment gateway. In those specific cases, customers should contact their card issuer to find out if their 3DS settings are correct or, indeed, whether 3DS is supported. However, if you have any more information to the contrary, please let me know and I'm happy to investigate further. Thanks!

**Comment by lobtx** [comment]
It is possible that some clients are in the case you describe, obviously, but one of our regular clients (a friend actually) often meets the problem with his own credit card, which is fully 3DS compatible. Most of the time, he has to try to perform the payment on several browser with his computer and mobile to finally get to reach the 3DS code confirmation page.

Moreover, when customers fail to reach the 3DS page, they sometimes call us and describe the same behavior. Next time we will ask them about their 3DS settings.

**Comment by matthewrgourd** [comment]
@lobtx the 3DS prompt is a popup and is provided by a third-party. There may be browser issues because it is a popup? Anyway, we don't handle the 3DS side of things ourselves except to receive the authentication outcome which the card issuer has communicated to the third-party service.

**Comment by matthewrgourd** [comment]
Hi @lobtx I got one of our developers to fully test our WooCommerce plugin and apparently it is working correctly. The only problems I can see with declined payments in the last month relate to the cardholders not having sufficient funds. I'm closing this issue for now but please re-open if you can find any specific examples for me to look up. Thanks.
