### ISSUE TITLE
Deposit of a guarantee amount

### ISSUE THREAD

**Issue by PRGM-MCK** [VivaPayments/API#1409]
Hello, I would like to know if there is a way to keep a deposit amount as a guarantee and return it back immediately after our clients have returned the product they have rent from us. Usually banks need around 1 or 2 working days for this. But we need to find a way to return the money back at the same moment and be available for usage. Can you help me with this?

**Comment by matthewrgourd** [comment]
Hi @PRGM-MCK sounds like what you need is our reversal / refund facility available in the Viva Wallet [banking app](https://members.vivawallet.com/en-gb/signin). However, the time it takes for your customer to receive the reversal amount varies, since it depends exclusively on the issuer and the type of card. You would need to inform customers that they will have to wait up to five business days for the reversal amount to appear in their card statement.

**Comment by PRGM-MCK** [comment]
Thank you matthewgourd. This creates some problems however in our project and we are trying to find out solutions that will enable customers to use easier our app.

**Comment by matthewrgourd** [comment]
Hi @PRGM-MCK I've looked into this further and there is a parameter in our [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/), [Create payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post) call called `isPreAuth`. If you set this to 'true' for each payment order it looks like your requirement may be satisfied :-)
