### ISSUE TITLE
Some doubts about checkout redirect

### ISSUE THREAD

**Issue by Jagoas** [VivaPayments/API#142]
Hello,
my name is Francisco Godino 
I'm starting the Viva's integration for one of our customers and I have some doubts.

First is abut test account
   Is a demo account but I need verify my account with passport, Id Card and more documents. Is really necessary for create a test account?

Second
  We need integrate the redirection Checkout method, but I don't find in your system where can I add the notification Url. We need actualize the transactions in our side. Where can I add this?

Third
  I saw in your API that we only need seen the amount to create a Payment Order, this payment order is sent by post in redirect, and later you redirect the customer to our website. We need send our transaction Id to make a relation between your transaction and ours. How can I do that? is possible?

Fourth
   Don't find the way to make any communications with your system.
   Following your example, I'm sending to 
       http://demo.vivapayments.com/api/orders

   these parameters
   {
     "Email": "francisco.godino@easypaymentgateway.com",     <-- mail from my test account
     "Phone": "6932769189",                                              <-- phone from my test account
     "FullName": "Javier Godino",                                       <-- name from my test account
     "PaymentTimeOut": 86400,
     "RequestLang": "en-US",
     "MaxInstallments": 12,
     "AllowRecurring": true,
     "IsPreAuth": true,
     "Amount": 1000,
     "MerchantTrns": "0000001",
     "CustomerTrns": "Description that the customer sees",
   }

and your response is
 
            {
                   "Message": "Authorization has been denied for this request."
            }

Could anybody help me with that, please?

**Comment by krakenrules** [comment]
Hello Francisco Godino,

To start using the REST API you must provide a Username (MerchantId) and Password (API Key). This process is known as API Authentication. To obtain these values go to 'Settings', 'API Access' page. For more information, see https://github.com/VivaPayments/API/wiki/API%20Authentication and https://github.com/VivaPayments/API/blob/master/CreateOrder/ASP.NET/CSharp.aspx.cs sample page.

It is not necessary to verify your test account with any kind of documents. The demo environment exists to test integrations between your sites and our payment solutions. Orders and Transactions can be created with unverified accounts.

In order to use the Redirect Checkout method its necessary to create a payment order first and then redirect to Viva Checkout page using the created payment order code. For more information, see https://github.com/VivaPayments/API/wiki/Redirect-Checkout
and https://github.com/VivaPayments/API/wiki/CreateOrder

Finally, to set the notification URL for successful/failed transaction go to 'My Sales' menu, select 'Payment Sources' and edit the 'Default' payment source. You can also use the Payment Order Creation 'MerchantTrns' value to link values from your system. For more information regarding optional parameters see https://github.com/VivaPayments/API/wiki/Optional-Parameters and https://github.com/VivaPayments/API/wiki/Webhooks

Regards,
Chris
