### ISSUE TITLE
Could not create order. Generic Error.

### ISSUE THREAD

**Issue by justmary123** [VivaPayments/API#1511]
Hello, today we are unable to process payments from our shopify shop
justmar......myshopify.com

https://checkout.vivawallet.com/shopifyplugin
Error
Could not create order. Generic Error.

it has always worked properly and no changes have been made. Can you please check ASAP?

**Comment by matthewrgourd** [comment]
Hi @justmary123, I see a couple of other people have had this issue. I checked with our development team and I'm told there's definitely no generic error with our Shopify plugin. So it must be your settings, but I don't know an immediate answer, I'm afraid. I'll speak to the devs again! One thing to check, have your transaction volumes increased a lot recently?

**Comment by unclemuzy** [comment]
@justmary123 we're experiencing the same problem on our site - see https://github.com/VivaPayments/API/issues/1506 for reference in case any future comments are of assistance.

**Comment by matthewrgourd** [comment]
Hi @justmary123 can you confirm if this is still an issue? Apparently some changes were made over the weekend.

**Comment by unclemuzy** [comment]
@matthewrgourd I opened #1506 4 days ago, made multiple phonecalls and requested an explanation as to why the issue was occurring, was promised a phonecall back (not received) and after loosing almost as much in failed transactions as we had taken in successful ones I went ahead and integrated a PayPal solution along with the VivaWallet checkout. 

From what I have seen the issue seems to have been resolved. 

But my confidence in the solution is very low right now and I am in discussion with other providers as we need a reliable platform for our business and our customers. 

No reflection on you personally, but I am sure you can understand that this is a critical time for many small businesses - perhaps more so than ever before.

**Comment by matthewrgourd** [comment]
Hi @justmary123, our dvelopment team has applied some fixes. Apparenty, there was a minor performance issue. @unclemuzy I'm sorry you feel that way but completely get where you're coming from.
