### ISSUE TITLE
woocommerse plugin

### ISSUE THREAD

**Issue by thalia2020s** [VivaPayments/API#1529]
Hello we have the website https://antalia-pharma.com/ and we are going live this week with a big social media campaign .When we tested the buy and proceed to the viva PLUGIN setup instractions This message appears:
Pay for order No 123
Thank you - your order is now pending payment .You should be automatically redirected to vivapayments to make payment.
Wrong Merchand Credentials or Source Id
**No order is placed in  our woocommerce
No redirection ever happened to viva.**

**Comment by matthewrgourd** [comment]
Hi @thalia2020s , sorry to hear this. I've checked your settings and you currently have the below (see screenshot) registered against your website's payment source in the Viva Wallet banking app:

![Screenshot 2020-04-01 at 14 51 59](https://user-images.githubusercontent.com/44943019/78145233-89584a00-7428-11ea-87fc-03524a1175c1.png)

Please correct based on the information given in our [installation guide](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) at Step 5. Success / Failure URLs entered (after your domain name) should be as follows instead of what you have:

- index.php?wc-api=wc_vivawallet&vivawallet=success
- index.php?wc-api=wc_vivawallet&vivawallet=fail

Hope this helps!
