### ISSUE TITLE
Approval of payment source? How to test it from development website?

### ISSUE THREAD

**Issue by IlPizza79** [VivaPayments/API#1538]
Hi, I've just created a new payment source in "Websites / Apps" page from my account, and I've some questions:
- right now is "pending", do I need to notify someone to get it approved? Or I simply have to wait?
- once approved, can I use this payment source with Simple Checkout payment, to display my logo in popup dialog?
- is there a way to test payment from my development website before activating it on the "real" website domain?

Thanks in advance.

**Comment by matthewrgourd** [comment]
Hi @IlPizza79 our support team will be in contact with you once the payment source has been approved.

**Comment by matthewrgourd** [comment]
Hi @IlPizza79 did your payment source get approved? I believe this can be used with our [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/) offering, yes. The relevant config option is `data-vp-sourcecode` otherwise the 'Default' source code will be used. In answer to your third query, I believe you can test with a payment source code from the [sandbox environment](https://developer.vivawallet.com/getting-started/#sandbox-account) if you have registered one of these. The payment sources don't have to be approved.

**Comment by IlPizza79** [comment]
Hi, yes it was approved but right now I'm still using the "default" source code.
Thank you for the sandox link, I'm a bit short on time right now but I hope to find some time to test it.
Thank you very much, I guess I can close this issue.
