### ISSUE TITLE
List of requirements

### ISSUE THREAD

**Issue by Cypoun** [VivaPayments/API#1564]
Hello,
### For betters answers I wrote this question in english but it concerns a _french_ online-shop.
_All the italic words are french terms_.

I would like to know what are all the requirements to use VivaWallet on our merchand website.
For now all I know is:

- HTTPS web site
- VivaWallet logo on the footer including paiements methods accepted
- Terms and Conditions (_CGU_)including : Name, Adress, mail contact, tax ID (_n°TVA_), ... 

Am I right ? Is there any other requirements ?
I really would like to use VivaWallet as soon as possible but can't find anywhere a proper list of requirements.

Thanks for your answer,
Bests Regards,

**Comment by matthewrgourd** [comment]
@Cypoun that's everything that we need in order to activate the payment source for our payment gateway, yes. However, there are a number of ways of integrating. Are you using an e-commerce platform like Shopify or WooCommerce (for Wordpress) or is it a website you're hosting yourself?

**Comment by Cypoun** [comment]
Ok Great !
The website is using PrestaShop. Anything particular to know about it ?

**Comment by matthewrgourd** [comment]
All I can advise you really is that you need to follow our [installation guide](https://developer.vivawallet.com/e-commerce-plugins/prestashop/) with clearly laid out instructions in order to start using our plugin for PrestaShop. And you need to have [opened](https://app.vivawallet.com/) a Viva Wallet Merchant Account prior to that. Hope this helps!
