### ISSUE TITLE
Error: Call to undefined function curl_init()

### ISSUE THREAD

**Issue by mynovaweb** [VivaPayments/API#1578]
We use Joomla 3.9.16 and VirtueMart 3.6.2 and at the last step of CheckOut procedure weI take the following error message: 0 - Call to undefined function curl_init()

Could you please help us 

The error refers to **https://martintech.gr**

**Comment by matthewrgourd** [comment]
Hi @mynovaweb sorry to hear this! 

n order for me to investigate further what your issue might be, please send through the following screenshots:

- VirtueMart payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by mynovaweb** [comment]
Hello

I sent U screenshots you asked for... The names of the image files correspond to the requests you made to me..

Thnx in advance

![Screenshot_2020-04-17-Martintech-04](https://user-images.githubusercontent.com/63452424/79544138-383a8e00-8097-11ea-803b-26bec2ad7f4f.jpg)
![Screenshot_2020-04-17-Martintech-03](https://user-images.githubusercontent.com/63452424/79544144-396bbb00-8097-11ea-8d15-a27617cbadfd.jpg)
![Screenshot_2020-04-17-Martintech-02](https://user-images.githubusercontent.com/63452424/79544150-3a045180-8097-11ea-8457-783390a0830f.jpg)
![Screenshot_2020-04-17 Martintech-01](https://user-images.githubusercontent.com/63452424/79544153-3a9ce800-8097-11ea-99ba-a3b8117283a3.png)

**Comment by matthewrgourd** [comment]
I believe this is a duplicate of another issue which has since been solved. If not, please reopen and we'll investigate further. Thanks!

**Comment by matthewrgourd** [comment]
@mynovaweb I'm sorry, I thought this issue had been solved for some reason. I've just done a test and have been able to recreate the issue:

![Screenshot 2020-04-22 at 09 32 31](https://user-images.githubusercontent.com/44943019/79959657-4c5a0300-847c-11ea-8286-62e91bdc4aa3.png)

Has your site worked with our plugin previously or is it a fresh install? I checked your payment source settings and what you've got for the Success / Failure URLs is:
WRONG
Success URL: 
`shop/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&bnkact=success`
Failure URL:
`shop/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&bnkact=fail`
CORRECT
instead of:
Success URL:
`index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&bnkact=success`
Failure URL:
`index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&bnkact=fail`

Can you change these and see if that makes any difference? If not, I'm afraid it will be an issue with your VirtueMart settings which I'm not an expert on. However, you could send me a screenshot of those settings (obscuring your Merchant ID and API key).

**Comment by mynovaweb** [comment]
Unfortunately, the error still persists after the change you suggest,
although to tell you the truth, I tried it myself and I was afraid that
this /shop/ affected the operation of the plugin.

I sent you a print screen for Virtuemart Viva Payment backoffice settings

[image: Untitled-1.jpg]

Στη διάθεση σας,



Παύλος Ι. Παπαδόπουλος

Novaweb
IT Services - Web Design & Administration

*Κ:* 6983 707 289 - *W:* novaweb.gr



Στις Τετ, 22 Απρ 2020 στις 11:40 π.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @mynovaweb sorry to hear this. Unfortunately that screenshot didn't come through. Can you try again or send to my email at mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Hi @mynovaweb thanks for sending that screenshot through. Unfortunately I don't understand Greek so this is a bit of guesswork. Ensure test mode is switched off. The field 'Vivawallet Instalment Logic' is blank which is correct. Can you tell me what the field directly below that (translated) means?

**Comment by matthewrgourd** [comment]
Hi @mynovaweb thanks for resending the translated version! All your settings look fine so I'm puzzled as to why you're experiencing issues. All I can think is maybe our plugin needs updating. I will raise with a developer and get back to you. Apologies for any inconvenience caused.

**Comment by mynovaweb** [comment]
OK, thanks

I am waiting for news ....

Στη διάθεση σας,



Παύλος Ι. Παπαδόπουλος

Novaweb
IT Services - Web Design & Administration

*Κ:* 6983 707 289 - *W:* novaweb.gr



Στις Τετ, 22 Απρ 2020 στις 1:09 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @mynovaweb, apologies for the extended delay. Our developer has replied as follows:

>Call to undefined function curl_init() means usually that the server is not running the PHP cURL extension (needed by the plugin). Usually this extension is activated by default on webservers, but in some rare cases (like this) it might not be enabled.

Can you check this? Thanks!

**Comment by matthewrgourd** [comment]
Hi @mynovaweb please close this issue if the problem has now been solved. Thanks!

**Comment by mynovaweb** [comment]
Thanks, now it seems that works. We will follow that and I hope in no new problem!
