### ISSUE TITLE
urgent payment decline

### ISSUE THREAD

**Issue by papanastasiou** [VivaPayments/API#1585]
my clients redirected to make the payment to the viva page they insert cards debit credit prepaid MasterCard visa etc and payment declined by system. Then they redirect to my website in error 404 pages...
the e-shop is 
https://www.ieramoni.gr/

**Comment by Dragonvapour123** [comment]
@papanastasiou I'm having the same issue and it is impossible to get hold of anyone. keep me updated and I will keep you updated as well

**Comment by matthewrgourd** [comment]
Hi @papanastasiou sorry to hear this. There isn't a general issue. I can see from your settings where the problem lies. I believe you're using WooCommerce with our plugin? Is that correct? You need to check you downloaded the correct plugin from this page on the Viva Wallet developer portal:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

Then you need to check you followed all the instructions correctly. Once you get to Step 5, go to the Viva Wallet banking app and edit the payment source with the number 9148 replacing the current values you have for the Success / Failure URLs with the following (as illustrated in the accompanying screenshot):

Success URL – `index.php?wc-api=wc_vivawallet&vivawallet=success`
Failure URL – `index.php?wc-api=wc_vivawallet&vivawallet=fail`

![Screenshot 2020-04-15 at 10 04 13](https://user-images.githubusercontent.com/44943019/79319857-cc262180-7f00-11ea-8743-937d4eccd39b.png)

Hope this helps! Let me know how you get on...

**Comment by matthewrgourd** [comment]
@Dragonvapour123 please raise a support request via our [support home page](https://github.com/VivaPayments/API/issues) (click on **New Issue** button) and I will look at separately. Provide as much info as possible about the nature of the problem, e.g. which of our plugins you're using.

**Comment by papanastasiou** [comment]
No sir, Not working your scenario. redirect me to another page with -1 and there is no charge on my MasterCard 
i tried the purchase with another IP, anonymous browser.

**Comment by matthewrgourd** [comment]
Hi @papanastasiou if it's working now, please close this issue. If you have an additional problem please raise a separate issue with as much information as possible. Thanks!
