### ISSUE TITLE
Woocommerce error

### ISSUE THREAD

**Issue by tase09** [VivaPayments/API#1593]
Hi! I ve just set up the module in woocommerce and it gets me to payment but after i receive an error and the payment is not processed.
![image](https://user-images.githubusercontent.com/58305947/79209081-9ecb6c00-7e4b-11ea-8a1b-6d6b617eb5bf.png)

**Comment by tase09** [comment]
after getting to gateway for payment it comes back on the fail page and i cannot track the error because it s on your part... somethings happens on the gateway...

**Comment by matthewrgourd** [comment]
Hi @tase09 sorry to hear this. 
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Hi @tase09 if maybe first you could let me know the registered business name so I can check your account.

**Comment by tase09** [comment]
Specials Ice Cream & Drinks SRL, gelafresh.ro

**Comment by matthewrgourd** [comment]
Hi @tase09 I'm sorry but I'm having difficulty finding your account, can you email the Merchant ID? My email address is mgourd@vivawallet.com Thanks!

**Comment by WeedyTech** [comment]
Hello we have the same problem with our customers who are under google chrome. 

This represents a huge shortfall. Can you try to find a global solution for updating your woocommerce plugin?

**Comment by tase09** [comment]
the website is running the latest version of woocommerce

**Comment by tase09** [comment]
i ve noticed u placed an order i had the module deactivated u can try now
again if you want to see

**Comment by matthewrgourd** [comment]
Hi @tase09, Ok, thanks. I believe the error you mean is one that comes up normally with a declined card. Do you complete 3DS successfully? Thanks for sending through your merchant ID.

**Comment by matthewrgourd** [comment]
@tase09 let me test again and get back to you...

**Comment by tase09** [comment]
i get on the payment page to complete my credit card details and after that instead of getting to the next step when the bank sends me a code to confirm for payment it gets back to the checkout page with the error

**Comment by matthewrgourd** [comment]
@tase09 ok, that's not what I'm getting. It takes me to the 3DS for the issuer after clicking on payment, I complete the 3DS popup successfully then I'm taken to the error page. But I believe this is because the card has no funds rather than our plugin isn't working. I need to raise with a developer as we may need to adjust our plugin but as far as I can tell it is working for cards that have funds. Sorry for any inconvenience caused. You can either re-enable the plugin while I raise the issue or if you prefer to wait, I'll get back to you as soon as I can tomorrow. Thanks!

**Comment by tase09** [comment]
the plugin is enabled... the card i m using has more than enough for a cake to order trust me... it s not that the problem i tryed 2 different cards one visa and one ing

**Comment by matthewrgourd** [comment]
Hi @tase09 ok there's definitely a problem with our plugin in that case. Rest assured I will sort this for you through a developer as soon as I can.

**Comment by tase09** [comment]
ok can i disable the pluygin for the moment so that clients don t get frustrated if they try to pay?

**Comment by WeedyTech** [comment]
I can assure you that the problem comes from an incompatibility between the plugin and google chrome.

Try it from Mozillan, your payment will be accepted.

It is absolutely essential that the developers quickly find a valid solution for all those who use the plugin vivawallet, in 45 days since we use the plugin we have canceled observed a few thousand failed orders.


Thank you in advance for your work!

**Comment by tase09** [comment]
you are absolutelly right so how can we resolve the problem cause probably most of people use google chrome?

**Comment by tase09** [comment]
i ve just place on order on IE and worked

**Comment by tase09** [comment]
So now of a sudden it works on chrome too... i ve disabled some extensions like adblocker maybe those conflict somehow?

**Comment by WeedyTech** [comment]
> you are absolutelly right so how can we resolve the problem cause probably most of people use google chrome?

I've just check my analytics report, 50% of my customer use Chrome... It is a financial disaster.

We need developers find a solution as soon as possible

**Comment by WeedyTech** [comment]
I have nothing disabled and the same, it works now!

I think the developers immediately identified the problem and fixed the anomaly!

It was extremely fast, thank you very much, we will be able to announce the good news to all of those who have made attempts in recent weeks.

**Comment by tase09** [comment]
I had 2 orders last night both of them tried to pay online... one of them succeeded and the other one placed the order with cash on delivery with a note that she tried to pay online but didn t work

**Comment by matthewrgourd** [comment]
@tase09 sure, but I may need you to enable it again just briefly while our developer tests. I'm asking him in the next couple of hours as I know you were frustrated yesterday!

**Comment by tase09** [comment]
it is activated... it worked yesterday i tried on google chrome... 2 clients ordered one of them succeeded ... the other left a note that he tried to pay and didn t work

**Comment by matthewrgourd** [comment]
Hi @tase09 sorry for the delay getting back to you. I've checked your account and can see you're set up correctly. Since I last spoke to you I can see some cancelled transactions, a failed one (due to card issuer reason) and a successful one.

I've checked with our development team and the error message "an error occurred" in the screenshot you sent through is indeed the correct one for a transaction that has failed due to a card issuer reason (insufficient funds etc). I've asked for it to be added to the roadmap urgently that this error message is updated to contain something more descriptive and advise the customer why the payment has failed. Thanks!

**Comment by matthewrgourd** [comment]
Hi @tase09, we have updated our plugin. Please uninstall the old one and use the below instead. Hope this helps! Let me know how you get on. 

[vivawallet-for-woocommerce-3.6.0.zip](https://github.com/VivaPayments/API/files/4502512/vivawallet-for-woocommerce-3.6.0.zip)
