### ISSUE TITLE
Vivawallet Success/Failure URLs

### ISSUE THREAD

**Issue by Bambinaros** [VivaPayments/API#1595]
Good day,

We have a woocommerce eshop and would like to customize the pages displayed after transactions are completed, whether successfully or not. 
I have tried constructing custom pages and using their URLs as success/failure URLs but they are not displayed unless the parameters in the "Advanced Configuration" section of the corresponding Payment Source are also changed. And if I change those, then the order status never changes to "processing" but remains "pending payment" even for successful payments.

So, is it possible to construct a set of custom pages and use their URLs instead of the success/failure URLs provided for woocommerce? 
For instance, in the case of a failed payment, now a message is displayed that an error occured. Instead, we want to link to a custom page with a message saying that their credit card payment failed and allowing them to go to their order page to view their orders. I have said custom page but how can I get redirected there in case of a failed credit card payment?

Secondly (and I have only tested this in a demo environment), the status of failed payments are marked as "pending Payment", not as "failed". Is this normal?

Thank you for your time.

**Comment by matthewrgourd** [comment]
Hi @Bambinaros, sorry it's taken me a while to get back to you. I'm afraid the answer to the first part of your question is there's not really any customising you can do to get beyond that rather generic failure error message (although this has since been updated. Please see below updated Viva Wallet for WooCommerce plugin).

[vivawallet-for-woocommerce-3.6.0.zip](https://github.com/VivaPayments/API/files/4504201/vivawallet-for-woocommerce-3.6.0.zip)

On the second question, the behaviour on live will be the same as on demo. Once a payment failure is confirmed to us, we update the payment order's status of 'pending' to 'cancelled'. I'm not sure why there is a time lag but there must be some reason inherent to the platform. Hope this helps!
