### ISSUE TITLE
Paiement Refusé

### ISSUE THREAD

**Issue by Dlicechanvre** [VivaPayments/API#1602]
Bonsoir , j'ai créer mon compte vivawallet hier , compte confirmé aujourd'hui , je les normalement bien intégrer sur SHOPIFY mais gros problème , sa redirige bien les client sur la page de paiement mais aucun paiement n'aboutie! ... sois il sont bloquer sur la page 3D Secure toute blanche sois sa mes directement paiement refuser ...

**Comment by git842732** [comment]
We have the same kind of issue since today on our french website cbdqueen.fr, here the translation of this ticket in english for devs @matthewrgourd 

" I've created my viva wallet account yesterday, account confirmed today, integrated without issue on our website but big issue then : it's redirect costumer on payment page but no payment work, either they are blocked on the 3D secure page that is all white , either payment is cancelled "

**Comment by Dlicechanvre** [comment]
Nous de notre coté problème toujours pas régler ... Un paiement sur deux fonctionne ^^........

**Comment by Dlicechanvre** [comment]
Modiff , les paiements re fonctionne de nouveau :) 
Problème régler on dirais bien :)
