### ISSUE TITLE
Retrive Credit Card Transactions using API

### ISSUE THREAD

**Issue by fabiosicilia86** [VivaPayments/API#1622]
Hi,
i developed a site where i download the Viva Wallet Transactions via API but i see that are not the CARD Transactions... is there a way to download it?!
Thank you for response...

**Comment by matthewrgourd** [comment]
Hi @fabiosicilia86 are you attempting to do a wallet extract but through our API:

>Wallet Extrait:

You can extract and save all transactions carried out through your VivaWallet. This feature is also available for each separate wallet you have created. The search is monthly and the results pertain to all transactions (transfers, payment of bills...), apart from sales transactions. Otherwise, you can review overall financial performance after each clearance.

From https://support.vivawallet.com/hc/en-us/articles/360001355529-What-kind-of-reporting-is-available-

This feature isn't available through our API unfortunately.
