### ISSUE TITLE
Localhost and android

### ISSUE THREAD

**Issue by lovetoast** [VivaPayments/API#1651]
Hi,

2 questions please

1) can I set the URL for native checkout to localhost? For hybrid applications, or do you have a mobile sdk for app payments for ecommerce?
2) For POS payments, what's the process to get an app loaded on the pax device to start development?

**Comment by matthewrgourd** [comment]
Hi @lovetoast, please see my answers below.

1. I'm not sure about localhost. I don't think so because of [CORS](https://www.w3.org/TR/cors/). No, we don't currently have a mobile SDK – sorry!
2. Please see the answer to https://github.com/VivaPayments/mobile-android-cardterminal-interapp-sample/issues/2 and let me know if that helps.

Thanks!
