### ISSUE TITLE
CORS issue on tokenization card

### ISSUE THREAD

**Issue by viclec** [VivaPayments/API#1694]
Hello,

I followed the guide: https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/
But I get a CORS issue.
![image](https://user-images.githubusercontent.com/19333791/82582016-15216380-9b9a-11ea-9316-979f4896ac77.png)

I tried to make the request through Postman and it works fine (Bearer token seems correct). I tried to find a solution using https://www.vivapayments.com/web/checkout/v2/js but couldnt find a method to generate card token and get a charge token using this card token.

Can you give me any guidance on what's the issue and how should I resolve it?

Thanks

**Comment by matthewrgourd** [comment]
Hi @viclec I think you need to disable your browser's cross-origin restrictions. This article looks helpful: https://www.thepolyglotdeveloper.com/2014/08/bypass-cors-errors-testing-apis-locally/

**Comment by viclec** [comment]
> Hi @viclec I think you need to disable your browser's cross-origin restrictions. This article looks helpful: https://www.thepolyglotdeveloper.com/2014/08/bypass-cors-errors-testing-apis-locally/

Is there any other way to solve this? Isn't this going to be an issue for customers with security enabled?

**Comment by viclec** [comment]
As mentioned in https://www.thepolyglotdeveloper.com/2014/08/bypass-cors-errors-testing-apis-locally/ a solution that they would suggest is to add Access-Control-Allow-Origin: * in response headers. Could this be possible? Right now I tried Edge, Firefox, Chrome and all of them are rejecting the response.

**Comment by matthewrgourd** [comment]
@viclec this is only an issue if you're using localhost which your customers definitely won't be doing!

**Comment by viclec** [comment]
> @viclec this is only an issue if you're using localhost which your customers definitely won't be doing!

![image](https://user-images.githubusercontent.com/19333791/82877076-6d61b800-9f42-11ea-958b-930ace1c527d.png)
![image](https://user-images.githubusercontent.com/19333791/82877373-c29dc980-9f42-11ea-9237-826cf69fb24d.png)

I tried also on our demo and production platforms and we get the same response. In case we would get this response on localhost only it won't be an issue for us. What can we do to fix this on our production environment?

**Comment by matthewrgourd** [comment]
Hi @viclec, apologies, I'm not sure what's going on here, will need to check with a developer and get back to you!

**Comment by matthewrgourd** [comment]
Hi @viclec, I've received a reply back from our development team. You could get an access token making a call to:

**POST** /connect/token HTTP/1.1
**Host**: demo-accounts.vivapayments.com
**Authorization**: Basic <client_id:secret>
**Content-Type**: application/x-www-form-urlencoded 
grant_type=client_credentials

You could use that token in [Step 3: Initialize Native Checkout](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-3-initialize-native-checkout)

However, there is a problem because we think the button **Generate a pair of credentials** does not work properly on demo:

![Screenshot_2020-06-12_at_15_44_45](https://user-images.githubusercontent.com/44943019/84516313-84840200-acc5-11ea-8f85-37a0d7f9c598.png)

...but we could provide you with the pair of values for demo. On production, that feature works.

**Comment by viclec** [comment]
@matthewrgourd So we would need to generate a new pair of credentials in order to fix the CORS issue? Because we are facing this issue on demo and on production environment, too.

**Comment by viclec** [comment]
Still facing the same issue after all this time. We are not trying to get an access token, but a card token (card tokenization). Can you help up out? Still getting the CORS error.

**Comment by matthewrgourd** [comment]
Hi @viclec, sorry to hear that. If you don't mind, please open a [new issue](https://github.com/VivaPayments/API/issues) with full details of the problem including screenshots with confidential info. blanked out. It's easier than updating this closed issue which could be confusing. I will look at it as soon as I can. Thanks!
