### ISSUE TITLE
Simple checkout domains

### ISSUE THREAD

**Issue by lovetoast** [VivaPayments/API#1708]
Can I use simple checkout on 2 different domains? for example, http://localhost for a hybrid mobile app and https://mylivesite for my live site? It looks fine, just wanted to make sure there won't be issues in production.

**Comment by matthewrgourd** [comment]
Hi @lovetoast you don't have to register individual domains but to use localhost might be problematic due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). If it's not working in Chrome try Firefox with a plugin, e.g. [CORS Everywhere](https://addons.mozilla.org/en-GB/firefox/addon/cors-everywhere/).

**Comment by lovetoast** [comment]
I think because it loads in an frame, the CORS is fine, unless I'm mistaken

**Comment by matthewrgourd** [comment]
So in that case you're fine, then!
