### ISSUE TITLE
The specified api action is disabled for the merchant

### ISSUE THREAD

**Issue by moustaidayoub** [VivaPayments/API#1714]
Please I'm trying to use the VivaWallet Simple Checkout. When I send POST request to https://demo.vivapayments.com/api/transactions. I get the message: 
"ErrorCode": 403,
"ErrorText": "The specified api action is disabled for the merchant XXXXX, please consult the documentation"
Thanks for your support

**Comment by matthewrgourd** [comment]
Hi @moustaidayoub I can enable this for you if you provide the Merchant ID on demo. Thanks!

**Comment by moustaidayoub** [comment]
here is my merchant ID: 
7d8a3bac-cccc-4ebc-ba69-e86afe29a9ee
--
Thank you

**Comment by matthewrgourd** [comment]
Hi @moustaidayoub that's done now! When you move over to production, you'll need to provide your production Merchant ID. You can email this to myself at mgourd@vivawallet.com when ready...

**Comment by matthewrgourd** [comment]
Hi @moustaidayoub I just emailed you. FYI, the link to our Simple Checkout page on the Viva Wallet Developer Portal is below in case you've not already seen it. If you're trying to integrate using another method, please let me know a.s.a.p. in order to avoid any confusion...

https://developer.vivawallet.com/online-checkouts/simple-checkout/

There is currently an issue in the demo version of Simple Checkout meaning failures are occurring when you attempt a test transaction. This has been fixed and a release is due today. So if you're getting errors it may be worth holding off any tests again until later today / tomorrow.

**Comment by matthewrgourd** [comment]
Hi @moustaidayoub, I'm advised by our dev team that the fix for production is now live. Regarding the demo environment, this should be available in the next hour. Thanks.

**Comment by matthewrgourd** [comment]
Hi @moustaidayoub, successfully updated yesterday.
