### ISSUE TITLE
Problem with Update 4.1.1 - "Click button to proceed to payment"

### ISSUE THREAD

**Issue by nicolascolocci** [VivaPayments/API#1728]
Hello, we received the notification on wordpress that the update to 4.1.1 from 3.6.2 was available, so i tried updating it with no success (it would say updating but stay at version 3.6.2). 

After a couple hours 4.1.1 magically decided to install and activate itself (in test mode obviously), without overwriting the old install of 3.6.2. That gave us 2 installs of vivawallet, so i deactivated 3.6.2.

I proceeded in reconfiguring 4.1.1 with merchant id, api and key, but clients were not getting redirected to vivawallet. Instead they were seeing an order completed page with the message "Click button to proceed to payment", but no button in sight.

I have switched back to 3.6.2 untill the issue is resolved.

Thanks and keep me posted

**Comment by matthewrgourd** [comment]
Hi @nicolascolocci,

Sorry to hear this. Basically what happened was we attempted to launch the 4.1.1 version of our plugin for WooCommerce last night but there were problems which several people have spotted and raised. We have since reverted back our changes. 

If you find any issues with 3.6.2, deactivate and delete all existing versions of our plugin from your plugin list in Wordpress, then reinstall 3.6.2 which is accessible via the following link:

[https://downloads.wordpress.org/plugin/vivawallet-woocommerce-gateway.zip](https://downloads.wordpress.org/plugin/vivawallet-woocommerce-gateway.zip)

All your settings should be the same. Installation instructions are also reverted back and available at the following location:

[https://developer.vivawallet.com/e-commerce-plugins/woocommerce](https://developer.vivawallet.com/e-commerce-plugins/woocommerce)

Apologies for any inconvenience caused. Our developers are still working on 4.1.1 and a revised update will be rolled out soon.

Thanks,

Matt
