### ISSUE TITLE
Simple checkout Activation

### ISSUE THREAD

**Issue by DaveHughes42** [VivaPayments/API#1735]
Hi,

I get this error after attempting to make an api call to process a transaction via simple checkout.

"[ThreeDSecureStatusId] => [ErrorCode] => 403 [ErrorText] => The specified api action is disabled for the merchant **********************(my merch id), please consult the documentation"

I'm guessing I need the simple checkout api activating for my account?

Can you help me with that please.

**Comment by matthewrgourd** [comment]
Hi @DaveHughes42, are you attempting this in the [sandbox](https://developer.vivawallet.com/getting-started/#sandbox-account) or in your [production account](https://developer.vivawallet.com/getting-started/#production-account)? Please share your Merchant ID(s) and I will enable the service. If you're sending a live production ID, please email me on mgourd@vivawallet.com rather than sharing it here. Thanks!
