### ISSUE TITLE
Cannot verify source for in-app payments

### ISSUE THREAD

**Issue by alfonsocuccaro** [VivaPayments/API#1745]
Hi,
we have developed an apps builder for food delivery apps, and we have integrated vivawallet as payment method. In the demo enviroment everything works fine, but we can't go live on a real Vivawallet account because we can't get our source approved.

The problem reported from the customer service is that the website hosted on the provided domain is not an e-commerce and there aren't data of the business of the real Vivawallet account. But we haven't an e-commerce, we only have an app, and the provided domain is the domain of our API server that the app uses do order products and checkout. 

How can we configure it? Is the configuration wrong?

I attach here the screenshot of the source configuration
service.web-app.it is the domain of our API server.

![detail](https://user-images.githubusercontent.com/6061785/84807897-342fdb80-b008-11ea-9f08-e576402373a3.PNG)

**Comment by matthewrgourd** [comment]
Hi @alfonsocuccaro, sorry to hear this. If the customer service department have said that then it is correct. I'm not sure if / how we can support app integration but will check with the development team for you.

**Comment by matthewrgourd** [comment]
Hi @alfonsocuccaro, I've looked into your query a bit more and may have some more info for you. Is it Native Checkout v2 you're attempting to set up? If so, you can set up a payment source that is active immediately by simply entering the following details in the corresponding fields:

- https (enabled)
- www.vivapayments.com (domain name)
- success (success URL)
- failure (failure URL)

Can you try that and see how you get on? It appears the payment source fields are used for our Redirect Checkout. When implementing Native Checkout v2 you don't have to put any 'real' values in order to create the source ID. Hope this helps! Let me know how you get on...
