### ISSUE TITLE
HTTP 403 caused by VivaPayments.cards.requestToken

### ISSUE THREAD

**Issue by hotelavailabilities** [VivaPayments/API#1748]
Hello, 

Our team has implemented the Native Checkout v2 3DS payment method in order to allow our customers accept payments from their own clients.
This was implemented months ago and was tested with Viva Wallet's demo environment, and we could complete test payments successfully.

So we recently tested this feature again and we are unable to complete any test payment.
Our issue is perfectly described by #1139 and #1310, meaning that we are getting an access token normally but an error occurs in Step 4, as described in your [documentation](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-4-request-a-one-time-charge-token).

We are facing a HTTP 403 error when the VivaPayments.cards.requestToken method is called from the client-side. The authenticateCardholder is set to false, like the mentioned issues describe.
It seems that this option is not referenced in the documentation any more.

If we remove this, this means that our clients will have to ask their own customers for card authentication details and type them in the rendered cardholder’s authentication page, is this correct?
Is this the only working solution, or what else could we try?

Thank you.

**Comment by matthewrgourd** [comment]
Hi @hotelavailabilities, due to security considerations, the skip auth option is now switched off by default and only available on a case by case basis. Please email me the Merchant ID and company name you have registered on demo. If you also require the feature to be enabled on live, please send me those account details as well. My email address is mgourd@vivawallet.com and the issue number to reference in the subject line is #1748. Thanks!

**Comment by hotelavailabilities** [comment]
Thanks for replying @matthewrgourd.

We will reconsider about including this option and get back to you by email if needed.
