### ISSUE TITLE
Woocommerce Vivawallet payment setup on checkout page

### ISSUE THREAD

**Issue by WNascimento77** [VivaPayments/API#1758]
I have followed the integration process on viva wallet website by inputting API, creating webhook all the necessary information. However when i test it on my site an erro message says invalid payment method and no fields to input the testing card details.

Do i have to add code for this redirect checkout process for a customer?

**Comment by matthewrgourd** [comment]
Hi @WNascimento77, sorry to hear this. Please may I have your website address so I can test? Also, your Viva Wallet account name. Thanks.

**Comment by WNascimento77** [comment]
https://www.pureconnectcbd.co.uk

 

PureConnectCBD LTD

 

Kindest Regards,

**Comment by matthewrgourd** [comment]
Hi @WNascimento77, I've tested just now and I'm not immediately sure what the issue is. In order for me to investigate further, please send through the following screenshots if you can:

- WooCommerce payment module settings (partially mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (partially mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by WNascimento77** [comment]
Hi Matthew,

thanks for swift reply. Please see attached settings.

 

 

 

 

 

 

Kindest Regards,

**Comment by matthewrgourd** [comment]
Hi @WNascimento77, those screenshots haven't come through. I think you just drag and drop. If you're having problems, please email me directly at mgourd@vivawallet.com. Thanks!
