### ISSUE TITLE
Woocommerce and Vivawallet issues

### ISSUE THREAD

**Issue by Leolecoin** [VivaPayments/API#1763]
Hello Sir,

I've implemented vivawallet following the instructions with woocommerce plug in.
I now have several issues that I don't know how to solve:

1) during the first payment test, the payment on woocommerce stayed on pending while the payment was successful. when the payment was a failure on vivawallet, woocommerce is waiting for payment.

2) The money never showed up on my vivawallet account and is still on pending status

3) How can I choose a successfull/unsuccessful payment page on my website following the payment on vivapayment ?

4) The 3D secure sms from my bank doesn't show my commerial name, but my real name

5) The email you send to my customer for successful payment is in English (I would need it in French)

thank you for your support

Best regards

**Comment by Leolecoin** [comment]
Hi, the website is https://lecoincbd.fr

thank you

**Comment by matthewrgourd** [comment]
Hi @Leolecoin, I've tested making a purchase on your site with a card with no funds. Works fine except I'm not taken back to the correct page on your website after completing 3DS. Can you let me have the following screenshots so I can investigate further?

- WooCommerce payment module settings (partially obscure your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (partially obscure API Key, include your browser's URL bar in the screenshot).

Regarding your other points, I believe these are all expected behaviour but I will double-check for you.

Thanks!

**Comment by Leolecoin** [comment]
Hi Matthew,

Thank you for your reply, please find bellow the requested screenshots.
after your failed payment, I have your payment on pending, and not canceled while you had no fund on your card. Is this normal?
I actually don't know how to choose a return page after success or failed payment.  should I add this index.php?wc-api=wc_vivawallet&vivawallet=success as a page URL ? 

Thank you,

Léo

![Capture 1](https://user-images.githubusercontent.com/67584351/86134861-64887700-baea-11ea-9672-ccfcbcc3dc53.JPG)
![capture 2](https://user-images.githubusercontent.com/67584351/86134864-65210d80-baea-11ea-8335-42d6697ceac7.jpg)
![capture 3](https://user-images.githubusercontent.com/67584351/86134866-65b9a400-baea-11ea-9448-048cb34c7313.jpg)
![capture 4](https://user-images.githubusercontent.com/67584351/86134868-65b9a400-baea-11ea-8b9c-f1f1132d8d34.jpg)
![capture 5](https://user-images.githubusercontent.com/67584351/86134870-66523a80-baea-11ea-9bde-bcb4852ab59a.jpg)

**Comment by matthewrgourd** [comment]
Hi @Leolecoin, thanks for sending through those screenshots. I've checked your settings and you need to update one thing in the payment source configuration. In "Nom de domaine" you've entered "www.lecoincbd.fr" but I believe it should be "lecoincbd.fr" (without the www) Can you try that and let me know how you get on?

**Comment by Leolecoin** [comment]
Hi Matthew,
I just changed it back to lecoincbd.fr, that what I set at the beginning and it wasn't working.
anyways, it's in pending status now.

thanks 

Léo

**Comment by matthewrgourd** [comment]
@Leolecoin I've just made the payment source active for you again.

**Comment by Leolecoin** [comment]
Hi Matthew,

thanks.

We still have some issues.

- We have this 3D secure thing, by sms. However, when we receive it my personal name (Florian G*****) appears, on the contrary of my website/professional name.
- The mail we receive from vivawallet, once the purchase is made, is still in English and we would need it in French

For the rest, it's all good !

Thanks

**Comment by matthewrgourd** [comment]
Hi @Leolecoin thanks for letting me know!
