### ISSUE TITLE
Ivapeo

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1764]
Hi @matthewrgourd! This customer Gestion Eficalia SL has two questions about implementation of payments gateway:

1. orders can be paid in installments?

2. what code we have to put in that box (screenshot):

![gestion eficalia online](https://user-images.githubusercontent.com/56823712/86002644-ea37f400-ba10-11ea-873e-d33b98c51fd1.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, is that an official Viva Wallet integration because I don't recognise the wording in the UI? If it is, the answer is purchases can only be paid in instalments if the merchant's account is based in Greece. As far as I'm aware, the instalments functionality isn't available for those clients who have accounts set up outside Greece. In answer to your second question, using the example of 300:3 in the 'Instalments logic' field, this means if the checkout total comes to 300 EUROS or more, the customer has the option of paying in 3 instalments.

**Comment by Alvaroalconada** [comment]
@matthewrgourd thx for the info. The second question is refered to "codigo fuente"

**Comment by matthewrgourd** [comment]
@Alvaroalconada the four-digit code of the [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) the merchant has to set up in the Viva Wallet banking app as part of the integration.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd the merchant doesn´t know where he can find this code. Could you show me through for telling merchant? thx

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada it's the four-digit code for the payment source that needs to be created in the Viva Wallet banking app, details here: https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/
