### ISSUE TITLE
issues payment gateway

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1789]
Hi @matthewrgourd This merchant ´´David Cobano Pareja´´ has the next issues, could you check it?
![PHOTO-2020-07-20-17-31-15](https://user-images.githubusercontent.com/56823712/88169742-c1c0a580-cc1c-11ea-85a3-aba341d750b7.jpg)
![PHOTO-2020-07-20-18-18-11](https://user-images.githubusercontent.com/56823712/88169760-c71df000-cc1c-11ea-94c1-14285b53da3f.jpg)
![PHOTO-2020-07-20-18-18-35](https://user-images.githubusercontent.com/56823712/88169770-ca18e080-cc1c-11ea-888f-84774e85b9de.jpg)
![PHOTO-2020-07-20-18-18-43](https://user-images.githubusercontent.com/56823712/88169779-cdac6780-cc1c-11ea-93d3-a5613ebba697.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada if this merchant is attempting to implement our Shopify plugin, he needs to request a token using our [Shopify token request form](https://forms.office.com/FormsPro/Pages/ResponsePage.aspx?id=11xgZwUpeU2CVq4fVCDCd_r-QSHD_PtMuAvap6OPapdUNkVITTFMNzMyWFdYSUJWNUw4MkxGSlhXRi4u) as clearly mentioned in the installation guide under [Before you start](https://developer.vivawallet.com/e-commerce-plugins/shopify/#before-you-start).

The error is occurring because the merchant has entered the wrong value for "Store Token". I've checked his account and he hasn't applied for one yet.
