### ISSUE TITLE
Redirect problem after payment

### ISSUE THREAD

**Issue by whalhalha17** [VivaPayments/API#1808]
Hello on the site legalweeddelivery.it I'm having redirection problems both when the payment is successful and when it is not successful how can you solve it?

**Comment by whalhalha17** [comment]
![vivawallet](https://user-images.githubusercontent.com/69385877/89726932-8d245a80-da20-11ea-891e-b9f65cc95282.PNG)

**Comment by matthewrgourd** [comment]
Hi @whalhalha17, sorry to hear this. There is a newer version of our plugin available. Please disable the current plugin then install the latest one by following the instructions on our WooCommerce documentation page:

https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/

Installation is straightforward and the plugin is built into your payment page rather than redirecting away from your website.

Let me know how you get on.
