### ISSUE TITLE
Yupi online sl

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1810]
Hi @matthewrgourd this merchant appears the next error:
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/56823712/89993141-90208480-dc86-11ea-8deb-19e4dd4d4840.png)

 He is using woocommerce:

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/56823712/89995285-95cb9980-dc89-11ea-8090-b1fa31427f98.png)

**Comment by matthewrgourd** [comment]
Having checked the CRM, I can see that the merchant has been testing with his own card ending in 2593. Since 10 August when testing began, there were 11 successful transactions with this card and only 3 unsuccessful payments. These 3 were issuer rejections (Visa
Do not honor (05)  so I can confirm there is no problem with our plugin. The failures are probably due to him entering the wrong billing information. I advise that he can re-enable the Viva Wallet plugin and start accepting transactions from real customers. However, just to point out that he's currently using the redirect version of our WooCommerce plugin. There is a new, native version available for download from here:
https://woocommerce.com/products/viva-wallet-for-woocommerce/
If he chooses to go down this path, the merchant will need to disable and delete the old plugin, then follow our [installation instructions](https://developer.vivawallet.com/e-commerce-plugins/viva-wallet-for-woocommerce/) for the new plugin.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd He just set up the new native version of woocommerce and he can´t receive payments from mastercard, do you know why?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada I've checked the CRM and he's not currently enrolled with Mastercard 3DS. As my colleague is away, I need to find out the correct steps to get this done. I've copied into my query on MS Teams channel "eCommerce Integrations".

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada please advise the merchant that he was uploaded to Mastercard yesterday so will be Mastercard approved for 3DS by tomorrow evening.

**Comment by Alvaroalconada** [comment]
@matthewrgourd so I understand that this issue has been solved and tomorrow evening the merchant could receive payments from mastercard cards, couldn´t?

**Comment by matthewrgourd** [comment]
@Alvaroalconada that's correct, yes.
