### ISSUE TITLE
Native checkout demo account expiry card date not fail validation

### ISSUE THREAD

**Issue by bulivlad** [VivaPayments/API#1830]
Hi,

The native checkout pass the card validation even if the card is expired (expiry date in the past). However the validation works for card number

Card details:
Card name: any string
Card number: 4111 1111 1111 1111
Expiry date: 10/15
CVV: 111

**Comment by matthewrgourd** [comment]
Hi @bulivlad, seems you're right. I will update the documentation to say you can use any expiry date.

**Comment by bulivlad** [comment]
Can you please also mention what is the behaviour we should expect on live api? As in what error will be thrown so we can handle it.

Another thing to mention here regarding form validations is that when using invalid card in native form the JS is wrapping up the exception coming from the server into a not really useful error.
When using an invalid card number the api will throw `CardsCreateValidationFailedInvalidCardNumber` but the JavaScript handling it is wrapping it up in `Bad Request` error which is not really helpful when trying to let user know what's wrong with his details.

However there is a workaround for it 
```javascript 
        $( document ).ajaxError(function(event, request, settings) {
            if(request.responseJSON !== undefined && request.responseJSON["message"] === "CardsCreateValidationFailedInvalidCardNumber") {
                //do whatever here when card is invalid
            }
        });
```

but maybe nice to be fixed

**Comment by matthewrgourd** [comment]
Hi @bulivlad thanks for the feedback. I've just realised the expiry date being valid in the past on demo needs to be fixed also. I will feed back to the dev team this + your suggestion about the other thing. Cheers!

**Comment by Sotiris-k** [comment]
Sorry for piling up on this issue but I believe it is relevant to what I'd like to mention.

The viva js that handles the card tokenization is mentioned in the documentation that in case of a fail we should just use the following statement to show the user what has happened.

`responseData.Error.toString()`

However, it would be better if we could know all the types of errors that are going to come through the script so we can prepare on our end with i18n and more customized messages.

**Comment by matthewrgourd** [comment]
@bulivlad, @Sotiris-k, thanks for your comments. I'm advised that the JavaScript is just checking that the card seems valid and that the date seems like a date. We know from a call to installments if the card can accept installments and if we need a CVV.  The rest of the validations (if the date is a past or future date) and the actual card validation (if there is credit etc) are going on when the actual make transaction API call is actioned. Then we have 3 error messages (and one ok state). The messages are broad but we don't want to be more specific about them because we don't want to expose information that the user should never see.

However, I will have our development team examine further and we will probably create improvements in the near future.

**Comment by Sotiris-k** [comment]
Hi @matthewrgourd thank you for the information. 

Even these 3 error messages, if you could add them in the documentation it would be helpful.

**Comment by matthewrgourd** [comment]
Hi @Sotiris-k will do! Thanks.
