### ISSUE TITLE
Error: Remote Key Injection

### ISSUE THREAD

**Issue by eatatcantine** [VivaPayments/API#1838]
hen starting up the viva wallet on terminal A920, a loading screen appears displaying the message 'Remote Key Injection'. This screen keeps loading without anything happening. We tried to restart several times, always the same screen when starting the app. 
![IMG_9272](https://user-images.githubusercontent.com/70519952/91718352-7a222780-eb93-11ea-9e0e-06290ceb1876.JPG)

**Comment by matthewrgourd** [comment]
Hi @eatatcantine, sorry to hear this. In order to get an answer to your query as efficiently as possible, please use the live chat facility available via our main website [www.vivawallet.com](https://www.vivawallet.com/), as indicated in the below screenshot:
![Screenshot_2020-09-01_at_11_57_49](https://user-images.githubusercontent.com/44943019/91841641-9d5bde00-ec4a-11ea-942a-8f9ac5d73b45.png)
