### ISSUE TITLE
Ibero Sarms

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1914]
Good morning @matthewrgourd! this merchant is having some problems with his payment gateway, he is using woocommerce

´´Hi Alvaro a lot of orders are appearing as cancelled, one of the our customers told us the next: After making the payment I was notified of a connection error with your payment server. After trying again several times, I left the page. How can I restart the order?´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I need the Merchant ID and / or website address, please?

**Comment by Alvaroalconada** [comment]
yes of course: 627710ED-4D78-4DF0-8120-2FDF9E10031A, https://www.iberosarms.com/

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I've checked his account, and I can see no unusual activity. Plenty of successful transactions so our plugin is working correctly. Please advise him there will always be some cancelled orders. These are either due to card issues or abandoned carts. However, it might be worth checking which version of our plugin he's using (**Plugins > Installed Plugins > Viva Wallet for WooCommerce**) as the latest (v1.1.1) has improved handling of card / cart issues.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant ensure me that the plugin is the latest version, the conversion rate with paypal vs viva is very different and coincidentally there aren´t so many carts abandoned because of code errors. One of his customers told him that he had a connection error with our wallet, however with the same data if he could pay by paypal.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, we have created a patch for the plugin that handles abandoned carts better. He could try that:

[viva-wallet-for-woocommerce-v1.1.1-patch.zip](https://github.com/VivaPayments/API/files/5383452/viva-wallet-for-woocommerce-v1.1.1-patch.zip)

He'll need to disable and delete the existing version of the plugin first, then follow our installation instructions from [Step 1](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#step-1-capture-viva-wallet-for-woocommerce-credentials).

**Comment by Alvaroalconada** [comment]
Hi @

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada does this problem still relate to https://www.iberosarms.com/ ?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I've looked at the recent transactions for https://www.iberosarms.com/ and there were 6 payment rejections due to card issuer on 6 Nov 2020. Please see below:

- 78,59 – Visa Do not honor (05)
- 78,59 – Visa Do not honor (05)
- 72,60 – Visa Do not honor (05)
- 72,54 – Mastercard Do not honor (05)
- 72,60 – Visa Do not honor (05)
- 72,60 – Visa Do not honor (05)

In each case, the customer should contact their card issuer to find out a detailed reason for the rejections. Status for the related orders in Woo would be "Pending payment" followed by "Cancelled". I can confirm that our plugin is functioning 100% correctly.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant replied me why this doesn´t happen in Paypal for example?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, as far as I'm aware, it's the same with all payment providers. However, as I say, if they want more detailed information about the rejections they should speak to the card issuers involved.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant tells me the next about before: Right Alvaro, and that's what I've done with everyone. And all those who answer me say the same thing, that it was wrong. Some of them patiently tried to pay by paypal afterwards and it did work.

That's why I'm surprised.

**Comment by matthewrgourd** [comment]
Ok, I guess it might be because we're not as well known as PayPal and some issuers use AI fraud technology that is sensitive to this. Definitely worthwhile merchant's customers checking in each case with their issuer to see if more information can be provided for me to feedback to the business.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant tells me the next: ´´
They don´t receive the SMS even if the phone number is correctly entered.

It is precisely the 2-step authentication that fails.´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, 3DS authentication is handled by the issuer, not us. This is not a problem we can solve. It lies with individual card issuers.
