### ISSUE TITLE
Access to Simple Checkout API

### ISSUE THREAD

**Issue by IleaBrussels** [VivaPayments/API#1925]
Hello,

1) Could you please provide access to Simple Checkout API? I need it for the demo version first and then for production.
2) It is stated here that Simple Checkout API uses basic authentication that will be phased out later:
https://developer.vivawallet.com/authentication/
Is it planned yet or can I already use the IdentityServer (OAuth 2) authentication for Simple Checkout API? If not, when do you plan to replace the basic authentification?
3) On the same page it is stated:
"When you pass your credentials in the header, you must Base64-encode them. The following is an example of an encoded HTTP basic authentication header:
Authorization: Basic ZmJmMWUwOTAtNjVkZS00Yzc1LWI1ODAtZDlkOWJjNDk0YWQyOldEdi1WKw== "

What is the pattern to encode? Is it [username]:[password] or something else?

4) Does Simple Checkout API support 3DS that has recently become mandatory in Belgium? In other words, does Viva Wallet display the page returned by a bank card issuer for a client to enter 3DS data?
Same question about the Redirect API

5) What is the advantage of Simple checkout vs Redirect?

**Comment by matthewrgourd** [comment]
Hi @IleaBrussels, please see my answers below:

1. Could you let me have the Merchant ID from your demo account? This is shown in the Viva Wallet banking app at the top of the **Settings > API Access** page. You will need to do the same for your production account.
2. As far as I'm aware, it's not on the roadmap to update Simple Checkout to use OAuth 2. I advise using [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) instead if this is important. 
3. You correctly state that the pattern to encode is username:password (see under [How to authenticate using basic auth](https://developer.vivawallet.com/authentication/#how-to-authenticate-using-basic-auth).)
4. Yes, all of our solutions, including Simple Checkout, trigger 3DS during the payment process.
5. The advantage of Simple Checkout over Redirect is that customers see a popup over the parent website rather than being transferred to a separate page away from the parent website when making a payment.

**Comment by IleaBrussels** [comment]
Hi,
Thank you for your prompt answer!
The Merchant ID from my demo account is  4f212a2e-e26b-480b-ba6c-3208a27c2980
Best regards

    On Tuesday, October 20, 2020, 10:12:56 AM GMT+2, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @IleaBrussels, please see my answers below:
   
   - Could you let me have the Merchant ID from your demo account? This is shown in the Viva Wallet banking app at the top of the Settings > API Access page. You will need to do the same for your production account.
   - As far as I'm aware, it's not on the roadmap to update Simple Checkout to use OAuth 2. I advise using Native Checkout v2 instead if this is important.
   - You correctly state that the pattern to encode is username:password (see under How to authenticate using basic auth.)
   - Yes, all of our solutions, including Simple Checkout, trigger 3DS during the payment process.
   - The advantage of Simple Checkout over Redirect is that customers see a popup over the parent website rather than being transferred to a separate page away from the parent website when making a payment.

**Comment by matthewrgourd** [comment]
Hi @IleaBrussels, I've enabled the Simple Checkout API on your demo account.

**Comment by IleaBrussels** [comment]
Hi,
Thank you!

    On Wednesday, October 21, 2020, 8:21:17 AM GMT+2, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @IleaBrussels, I've enabled the Simple Checkout API on your demo account.
