### ISSUE TITLE
website/app source code

### ISSUE THREAD

**Issue by LOUSTRINI** [VivaPayments/API#195]
`

`> website/app source code`

` what can we write on it ?

**Comment by defilerc** [comment]
Hi @LOUSTRINI ,

Can you please clarify what exactly are you trying to modify and what are you trying to achieve?

Regards,

**Comment by LOUSTRINI** [comment]
Enabled Yes No [WEBSITE]
Title [WEBSITE]
Merchant ID [WEBSITE]
Secret Key [WEBSITE]
Website/App Source Code

For Test source code Click here
<http://demo.vivapayments.com/selfcare/en-us/sources/paymentsources>. For
Live source code Click here
<http://www.vivapayments.com/selfcare/en-us/sources/paymentsources>.
[WEBSITE]
Test Mode Yes No [WEBSITE]
New order status -- Please Select -- Pending Processing [WEBSITE]
Debug Yes No [WEBSITE]
Payment from applicable countries All Allowed Countries Specific
Countries [STORE
VIEW]

2016-11-21 12:18 GMT+02:00 Konstantinos Athanasoglou <
notifications@github.com>:

**Comment by LOUSTRINI** [comment]
It doesn't work the line *web /app source*
please check and tell us what can we write in this line
Thanks a lot


2016-11-21 12:18 GMT+02:00 Konstantinos Athanasoglou <
notifications@github.com>:

**Comment by defilerc** [comment]
Hi @LOUSTRINI ,

It looks like you're using an external plugin, so let me clarify the Viva Payments API process, to help you fill this parameter.

In order to process payments through the Viva Payments API, you have to create an order and then create a transaction for this order (pay the order). Each time you create an Order, you have to specify a Source, by specifying a `SourceCode`. This enables the merchant to create orders from different sources,  in order to group his orders, redirect the user to different URLs or use them in any other way he sees fit.

By default, all orders are created using the `Default` source. In case, you don't want to create an additional order you can use the value `Default`. 

You can configure your Sources through the merchant login interface from `My Sales -> Payment Sources` menu.

Please note, that each time you change the domain for one of your sources in the live environment, a possible audit may take place to ensure all settings comply with Viva Payments Security policy.

Please let us know if you need further assistance.

Best regards

**Comment by LOUSTRINI** [comment]
Hi again
We have do everything that viva send us
We made the new web account with the CODE from viva but iit not working
If you can see the PrtScn

2016-11-21 12:53 GMT+02:00 Konstantinos Athanasoglou <
notifications@github.com>:

**Comment by defilerc** [comment]
Hi @LOUSTRINI ,

Please make sure you have attached the screenshot you are referring to, as there isn't a print screen in your post.

Please provide us the following info:

- The environment you are using (live/demo)
- Your Merchant API associated with the above environment
- The Viva Payments API request you are having trouble with (showing all the parameters you are passing)
- The response you are receiving (error code + error text)

so we can investigate further your issue.

Best regards,

**Comment by LOUSTRINI** [comment]
Hi
we using is live
and it doesn't find credit card in the last step
Thanks

2016-11-21 16:18 GMT+02:00 Konstantinos Athanasoglou <
notifications@github.com>:

**Comment by LOUSTRINI** [comment]
and after the last stepwe can see that

2016-11-21 16:50 GMT+02:00 Nikolaos Parmenidis <loustrini@gmail.com>:

**Comment by defilerc** [comment]
Hi @LOUSTRINI ,

There isn't any file attached to your response. 

Regards,
