### ISSUE TITLE
The checkout of viva wallet 

### ISSUE THREAD

**Issue by maofree** [VivaPayments/API#1950]
Hi
I'm using viva wallet with prestashop 1.7

at this moment does not consider the client's target language from prestashop. English is always set, so every customer must always change the language before entering data and it shouldn't happen

can you fix it?

thanks

**Comment by matthewrgourd** [comment]
Hi @maofree, sure, I can add as a feature request. However, I have to advise you that unfortunately we're not updating our PrestaShop plugin on a very frequent basis at the moment, so I don't know when it will be rolled out.

**Comment by maofree** [comment]
hi
I don't think there are major changes to be made
I imagine it is enough to pass the language iso code in the redirect url from prestashop to the page of the checkout, and then set it as the base language also in the checkout

**Comment by maofree** [comment]
hi
the owner of the site said me that for him these features are fundamental and he does not wait, I think he will go to remove it from the site

**Comment by matthewrgourd** [comment]
Hi @maofree, let me check, are you requesting a default language other than English in the plugin? If so, which one?

**Comment by maofree** [comment]
are you requesting a default language other than English in the plugin?
I don't understand this question
in the module's settings there are not this options
in the site there are the italian and french languages

**Comment by maofree** [comment]
ok understood, set as default language the "italian language"

**Comment by matthewrgourd** [comment]
Hi @maofree, at the moment our plugin automatically selects English for the language, unless customers are connecting from Greece, in which Greek is displayed. In order to make the language change to French or Italian for customers connecting from France or Italy, we need to make some code changes which I'm afraid won't be possible immediately. However, I've added your suggestion as a feature request. Apologies if this is not the answer you're expecting. At the moment, customers wishing to see the plugin in French or Italian have to change it manually using the dropdown on the payment page.

**Comment by maofree** [comment]
is it possible to set as default language for mondialshop.it the italian language instead of english?
is it not set on the dashboard of viva wallet?

**Comment by matthewrgourd** [comment]
Source code amended for checkout to default to Italian in all possible scenarios....see #1951 for updated source files.

**Comment by maofree** [comment]
ok thanks
