### ISSUE TITLE
Success & Failure URLs Viva Wallet

### ISSUE THREAD

**Issue by AmyLouHolland** [VivaPayments/API#2005]
Hi, I've had conflicting advice on this - I've been told by Viva tech support to create our own success and failure pages in our web CMS and use these URLs in our Viva Wallet account but then the integration instructions have told me to use the ones provided by Viva Wallet. I've put a payment through on the site (which works) and and get a 'order received' page (which I think is the standard one for WooCommerce). What I want to know is do I actually need those bespoke success and failure pages? And which ones should be in my Viva Wallet account??

**Comment by matthewrgourd** [comment]
Hi @AmyLouHolland, our latest WooCommerce plugin (installation instructions below) automatically creates the payment source so you no longer need to worry about any settings, especially the success / failure URLs you mention. In fact, please do not attempt to edit these otherwise you will get into difficulty.

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by matthewrgourd** [comment]
Hi @AmyLouHolland, please let me know how you got on. If everything is ok now, can you close the issue?

**Comment by AmyLouHolland** [comment]
Hi Matthew, sorry for the delay! I've been out of the office since Thursday afternoon so only saw your response this morning. That's great, thank you for clarifying. It was the communication from Viva Wallet about the creation of the pages and updating the URLs that confused me. The default ones are now in there and payments seem to be working fine. Thanks for your help.
