### ISSUE TITLE
PaymentsNonReversibleTransaction: Request to reverse transaction aborted

### ISSUE THREAD

**Issue by mrusciel** [VivaPayments/API#2021]
Los reembolsos me funcionaban perfecto en el entorno Demo, ahora en el vivo me da este error, me puede decir que hacer,

Saludos

**Comment by matthewrgourd** [comment]
Hi @mrusciel, this normally means you're attempting a partial refund before the transaction has been cleared. Full refunds can be performed at any time; partial refunds 1 day after the transaction. If your problem is something different, please share with me detailed request / response logs with confidential info. replaced with placeholders. I will then be able to troubleshoot further.

**Comment by mrusciel** [comment]
Tenia dudas pues en el entorno demo tenia otro código de error, intentaré el reembolso luego y ya le digo si funciona. Gracias.
