### ISSUE TITLE
VivaWallet on woocommerce err

### ISSUE THREAD

**Issue by toroscarol** [VivaPayments/API#2029]
Hello everybody, I have an issue with the wc vw plugin installation. On the checkout page the VivaWallet logo doesn`t load and I get a double name just like in the pic below.
The link is  https://sturzonline.ro/checkout-page-2/
Thank you all!
![VWErr](https://user-images.githubusercontent.com/18322892/100639082-6bd3db00-333d-11eb-9fb6-f05fe28b2ea2.JPG)

**Comment by matthewrgourd** [comment]
Hi @toroscarol, sorry to hear that. So that we can investigate further, please send us a log file from the plugin. To do this:

1. Go to **WooCommerce > Status > Logs** tab:

![log1](https://user-images.githubusercontent.com/44943019/99075879-2039d700-25b2-11eb-806d-f45cc6441d68.png)

2. Select relevant date from the dropdown:

![log2](https://user-images.githubusercontent.com/44943019/99075893-262fb800-25b2-11eb-844d-bbf073524f3f.png)

3. Click on the **View** button.

4. Copy the contents into a text file and save it with an appropriate name. 

5. Attach to this issue in .txt format.

In addition, we'd like to check if any other software could be interfering with ours. You can find out all the plugins installed from **WooCommerce > Status** in your Wordpress admin. In there you'll see lots of info but there are 2 relevant sections called **Active plugins** and **Theme**. Can you copy and paste their contents into this issue? Thanks!

**Comment by toroscarol** [comment]
[No log, plugins and theme.txt](https://github.com/VivaPayments/API/files/5622714/No.log.plugins.and.theme.txt)

Sadly I don`t have a log file, just a test log which is empty...

**Comment by matthewrgourd** [comment]
Hi @toroscarol, what version of our plugin do you have installed. Check **Plugins > Installed plugins > Viva Wallet for WooCommerce** for this info.

**Comment by toroscarol** [comment]
1.2.0 @matthewrgourd

**Comment by matthewrgourd** [comment]
Hi @toroscarol, oh gosh, I could see that in the file you sent through – doh! My feeling is that this is a theme or plugin compatibility issue. Try removing some plugins or changing the theme, until you find out the cause of the issue. Also I'm not sure about /checkout-page-2 for the page name. Why is that there? Looks non-standard to me!

**Comment by toroscarol** [comment]
I found it!!!
It was **Cookies and Content Security Policy** plugin. Maybe it is blocking some content being loaded...
Thank you very much for your help @matthewrgourd
