### ISSUE TITLE
getting 502 error in Simple checkout API

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#2031]
Hi,

One of our live customers tries to pay us using vivawallet - Simple checkout and using **card type  :  NET_VISA**.
But they are getting error 502 Transaction failed. (it seems to keep freezing after it has gone through the Visa authentication page process. ). 

Please find the below transaction failed dates
Transaction failed date : 2020-10-31 11:12:42.507
Transaction failed date : 2020-10-31 11:13:42.583
Transaction failed date : 2020-10-31 11:15:28.823
Transaction failed date : 2020-10-31 11:16:29.597
Transaction failed date : 2020-10-31 11:17:21.567
Transaction failed date : 2020-11-02 14:59:00.005

Trade name : EFILE READY LIMITED
Registration date : 19/02/2020
live Merchant id: b85b1ede-d9a6-4cfe-a992-3ae583cab24f

Please kindly let us know the reason and how we can avoid this.

Thanks,
Pavithra

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, unfortunately Simple Checkout doesn't give any useful feedback on card failures. Please see below (in bold) rejection reasons from issuer for each transaction you mention:

Transaction failed date : 2020-10-31 11:12:42.507 – **Visa Transaction not permitted to cardholder (57)**
Transaction failed date : 2020-10-31 11:13:42.583 – **Visa Transaction not permitted to cardholder (57)**
Transaction failed date : 2020-10-31 11:15:28.823 – **Visa Transaction not permitted to cardholder (57)**
Transaction failed date : 2020-10-31 11:16:29.597 – **Visa Transaction not permitted to cardholder (57)**
Transaction failed date : 2020-10-31 11:17:21.567 – **Visa Transaction not permitted to cardholder (57)**
Transaction failed date : 2020-11-02 14:59:00.005 – **Visa Do not honor (05)**

In all cases the customer would need to have contacted their issuer to find out what the problem is with their card.

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, I notice you're currently directing Simple Checkout payments to the "Default" payment source. You have a payment source 2902 set up for www.app.universalinvoice.com. What is that? Is your Simple Checkout integration meant to point to that? If so, you need to add the following parameter to your code: `data-vp-sourcecode="2902"` but you first need to check that you have selected **Native/Pay with Viva Wallet Checkout** under ‘Integration method’ in your [payment source settings](https://developer.vivawallet.com/online-checkouts/create-a-payment-source-simple-checkout/).

**Comment by pavithra-itcs** [comment]
Hi Mattewrgourd,

We added that sourcecode **2902** to use in Redirect Checkout payments API's. Still, our code not released in our live Application. Soon we are going to make use of this sourcecode 2902.

Regards,
Pavithra

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, unfortunately I can't find this against your account. The source code I'm seeing for "Payroo" (www.app.universalinvoice.com) is "2909".

**Comment by pavithra-itcs** [comment]
Hi Mattewrgourd,

Sorry for the wrong typing, our payment sourcecode is **2909** and Description is "**Payroo**".

Regards,
Pavithra

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, ok, and what is your query, please? It's not clear to me.
