### ISSUE TITLE
Failure and Success url's for woocommerce

### ISSUE THREAD

**Issue by ctzio** [VivaPayments/API#2036]
Hello, 
I installed on our website the Woocommerce redirection plugin from the Github repository. Can you tell me which url's I should place when I create a new online payment in Vivawallet?

In a relevant question. 
Reading the instructions from the plugin I realized that you've created an API key issuing system within the Vivawallet backend. However when I tried to issue keys I saw that there was no source code available. 
Anyway I placed the merchant ID and API key values I received and attempted a transaction. However I was never returned to the e-shop. 

I have to admit I am a bit confused. What is the correct way to set up vivapayments with redirection for Woocommerce? 
Thank you

**Comment by matthewrgourd** [comment]
Hi @ctzio, this is our previous redirect checkout for WooCommerce. If you wish to use that, the installation instructions are [here](https://developer.vivawallet.com/e-commerce-plugins/viva-wallet-woocommerce-gateway/) but we strongly advise you to opt for our newer, native version, details below:
**Download page**
https://woocommerce.com/products/viva-wallet-for-woocommerce/
**Installation guide**
https://docs.woocommerce.com/document/viva-wallet-for-woocommerce
Thank you!

**Comment by ctzio** [comment]
Hello, 
thanks for this. Is the new api redirection as well, iframe or is the processing done on our website?
Thank you?

**Comment by matthewrgourd** [comment]
Hi @ctzio, with our Native Checkout v2 solution, no credit card info is stored in the back-end, on the website or anything. The front-end (customer’s browser) is only dealing with sensitive data (like cc info) and sends that data to a Viva endpoint. The back-end never knows or processes anything sensitive.

**Comment by ctzio** [comment]
Hi, 
that's good to know. 
Thanks.

**Comment by matthewrgourd** [comment]
Hi @ctzio, I'm closing this now, but feel free to reopen if you have any issues installing the native version of our plugin.

**Comment by ctzio** [comment]
I have a question regarding native checkout. I see that in this case it's not creating an iframe or anything but it's just showing a credit card form, so what level of PCI compliance is required for this type of checkout?
We would like to fully outsource processing to Viva.  For merchants who fully outsourced all cardholder data functions, all cardholder data fully outsourced means that even the credit card form is not hosted on the own website to prevent tampering with. So I think the native checkout would require a higher level of PCI compliance than we currently need. 
Is redirection going to be completely abandoned?
Thank you

**Comment by matthewrgourd** [comment]
Hi @ctzio, we have adopted a native approach because it's much more user friendly and provides a seamless integration for customer. As a fully compliant PCI DSS Level 1 Service Provider and a principal member and licensed acquirer of Visa and MasterCard, Viva Wallet adhere to the card schemes’ operating regulations. We are also subject to yearly audits by a third-party PCI Qualified Security Assessor, Visa, MasterCard, and the banks we partner with.

**Comment by ctzio** [comment]
Hi, 
I probably didn't explain it correctly. I wasn't asking about Viva, who of course are fully compliant, but for the merchant. What level of PCI compliance do the merchants need to achieve in order to have native checkout?

**Comment by ioweb-gr** [comment]
@matthewrgourd I think what @ctzio  is saying is that because native checkout is actually rendering the form inline and submitting to the VIVA servers, that means that they won't be able to fully outsource the cardholder's data processing since part of it, the submission form of the credit card data, will reside on the merchant's website. 

The usual case for this type of integration is to implement the form on the gateway's servers and render it on an iframe which will handle the submission. That way the iframe can be protected via a content security policy and provide full compliance with a lower level of PCI DSS successfully fulfilling the requirements for SAQ-A

Part of it says

```
SAQ A merchants confirm that, for this payment channel:
 Your company accepts only card-not-present (e-commerce or mail/telephone-order) transactions;
 All payment acceptance and processing are entirely outsourced to PCI DSS validated third-party
service providers;
 Your company has no direct control of the manner in which cardholder data is captured, processed,
transmitted, or stored;
 Your company does not electronically store, process, or transmit any cardholder data on your
systems or premises, but relies entirely on a third party(s) to handle all these functions;
 Your company has confirmed that all third party(s) handling acceptance, storage, processing,
and/or transmission of cardholder data are PCI DSS compliant; and
 Your company retains only paper reports or receipts with cardholder data, and these documents
are not received electronically
```

Especially this part

```
Your company has no direct control of the manner in which cardholder data is captured, processed,
transmitted, or stored;
```

We've been going through this issue with OpenMage a lot to clarify what exactly must be done for the various Gateways so that merchants can be fully compliant and fulfill the requirements of SAQ-A

Moreover it's also a matter of security for the customers. As I read online, the only secure methods of doing this type of submission is either via redirection or via iframe.
