### ISSUE TITLE
Error after passing 3d secure, error 502

### ISSUE THREAD

**Issue by vassilismon85** [VivaPayments/API#2045]
I am having the same problem with several of my clients. I am using the simple checkout payment method. If the card holder has to pass the 3D Secure confirmation, after the confirmation we receive error 502 and the transaction fails.
I tried it myself with a card of mine, to make a real payment, to merchantid ***. My card is mastercard, I had enough money and I tried it both with push notification and with pin number via sms.
Both payments failed with the same error. The response from your server in one of my efforts was: 
(
    [Emv] =>
    [Amount] => 4.95
    [StatusId] => E
    [RedirectUrl] =>
    [CurrencyCode] => 978
    [TransactionId] => *****
    [ReferenceNumber] => 579511
    [AuthorizationId] =>
    [RetrievalReferenceNumber] => 034015579511
    [Loyalty] =>
    [ThreeDSecureStatusId] => 1
    [ErrorCode] => 502
    [ErrorText] => Transaction failed
    [TimeStamp] => 2020-12-05T17:47:10.3774934+02:00
    [CorrelationId] =>
    [EventId] => 10005
    [Success] =>
)
In case it helps, on my browser's console I noticed the errors attached.

![Error](https://user-images.githubusercontent.com/69846515/101247888-969aa680-3724-11eb-8185-b00de88ba991.jpg)
![Error2](https://user-images.githubusercontent.com/69846515/101247890-97cbd380-3724-11eb-9440-82bc70c39d34.jpg)

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, I've checked your account and I can confirm the below failure reason for the transaction you mention. It is a card failure rather than a problem with our checkout. The 500 error is somewhat misleading as it relates to the issuer rejecting the card rather than our platform having connectivity issues. For a more modern approach, please replace our Simple Checkout solution with Viva Wallet [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) if you wish. Thanks!

- 05/12/2020 17:47:09 – €4.95 – Mastercard Do not honor (05)

**Comment by vassilismon85** [comment]
How can it be a card failure, since I am making online payments with my card in other online payment gateways and it works? And if it is my card's problem why suggesting thah I should replace the Simple Checkout? If you cannot support

**Comment by vassilismon85** [comment]
And I have the same problem with several customers. I just tried it with my card so I could catch the error. So all my customers' cards give us a card failure and it is not your problem?

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, I have the info in front of me and it is 100% a card failure. However, you also have plenty of successful transactions so I can tell that our checkout is working correctly. I have advised you to switch from Simple Checkout as I was built a long time ago and our Native Checkout v2 solution is more up-to-date. It is up to you of course. If you want to continue using Simple Checkout that is fine also. If you have any other instances of payment failure, please let me know date / time / amount and I will find out the issuer rejection reasons for you.

**Comment by vassilismon85** [comment]
I told you that the problem is after passing 3D secure. If the customer uses a card with no need of verification, the transaction completes. I passed the 3D secure both with push notification and pin via sms, and both times the transaction failed. I used another card with no verification and it passes. So you are saying the you are having an online solution for payment gateway which is not up to date? Seriously?

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, there is nothing wrong with our Simple Checkout. It works fine. The only thing is customers do not receive very clear messaging about why their card has failed. This can lead to confusion and they may think our checkout is to blame when it is in fact their card.

Please let me know any other failed transactions and I will check for you.

**Comment by vassilismon85** [comment]
You are having a payment gateway in your developer portal as a suggestion and you are saying me that it is not up to date? I was using my card with 3d secure in all my customers' eshops and it was working fine. This problem has started happening the last 2-3 weeks I think. And it was my customers that informed me, because they are starting getting complains from the final users that cannot make the payment. So enerybody have card failures?

**Comment by genesispro** [comment]
Dear Matthew a bunch of errors that can easily be seen in the console window of the browser start way before the transaction gets verified. Chrome totally denied and throws the error transaction, in mozilla it doesn't fail but it warns... and at after the transaction verification it fails at your end. I think it is AGAIN a compatibility problem between your system and the modern browsers which most of the customers usually have since they usually get automatically updated! Please check it and let us know if it will be fixed. If you want give us a phone number or we can give you our phone number to try to identify it and solve it live! We expect "instant" support when it has to do with money. The easiest we can do is change mechanism to a different platform and stop using viva instead we are trying to solve it. We can't wait forever. Just to remind you it is not only with one account but we have tens of customers under our platform. The moment we decide to change platform ALL of them will follow to the new platform that we will connect. We thought at first to use Viva because it was supposed to be in Greece and we would have easier communication but... Please inform us asap a way to communicate and fix it once and for all! Thank you for your understanding ... Dimitris

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, @genesispro, apologies for any misunderstanding. Based on having a look at your account this morning, I can see no unusual activity. A few card issuer rejections (which is normal) but also plenty of successful transactions. Based on my experience, this means your Simple Checkout is working correctly. However, I will test your checkout now to confirm further. The website address is www.onlinefood.gr. Is that correct? Thanks!

**Comment by vassilismon85** [comment]
No, the eshop is https://www.onlinefood.gr/spitikomarousi. But if I can understand the problem the transaction using firefox and writing down manually the card details works. If I use google chrome I get the error. I just tried one transaction with firefox and it worked, and after 2 seconds I tried the same card with google chrome and it failed. Maybe there is a compatibility issue with the latest google chrome again?

**Comment by vassilismon85** [comment]
I am also available to give you remote access to my pc and make all the steps while you are watching, because I beleive that via google chrome you don't even get the request. Maybe you don't even have it in your log system, so you don't have the all data concerning how many transactions actually fail. I tend to believe that the problem starts on the final customer's browser, before reaching to your server. In my initial post I had some screenshots with errors on my browser's console, that initiated before the verification process.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, thank you for bringing this to our attention. We will carry out our own tests and get back to you.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, sorry, I can seem to resolve https://www.onlinefood.gr/spitikomarousi. Can you let me know the correct steps to test?

**Comment by vassilismon85** [comment]
This the customer's site. It is not a developer environment. And it is all in greek. How can I give written instructions? You have to sign up and then make an actual order. That is why I told you that I can give you remote access to my pc.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, please can you confirm the merchant ID and the payment source code that is currently linked up to https://www.onlinefood.gr/spitikomarousi. If you prefer, you can email those details. Please quote this issue (#2045). My email is mgourd@vivawallet.com. I'm somewhat confused because in order for our Simple Checkout to work, a live website address is required and https://www.onlinefood.gr/spitikomarousi isn't currently live.

**Comment by vassilismon85** [comment]
I have sent you the email. The site is live now. We made a restart of our server, that is why you could not connect before.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, I'm trying now. If I make a test payment for €16.11 would you mind refunding it?

**Comment by vassilismon85** [comment]
I will contact with the customer and tell him to make the refund. No problem

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, before I do that, can you please send me a screenshot of your settings for payment source 9393? Thanks.

**Comment by vassilismon85** [comment]
I have sent you the email with the settings.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85 thanks for sending through. The settings look fine. I've just make that test payment using my own card (with funds). I'm getting the same 500 error so looks like there's an issue even with an ok card (red cross displayed and payment didn't go through). Not sure why this is. Need to check with our development team. Thanks and apologies for any inconvenience caused...

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, I've raised this with our dev team. I'll let you know once we have a fix.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, FYI the dev team discovered an issue on production which has now been fixed. Let me know if any further queries, otherwise please close the issue if you feel it has been resolved. Thanks!

**Comment by vassilismon85** [comment]
We tried it and it worked. The issue fixed was something specific for the merchantid I sent you or is it the same fix for everybody? Because I encounter the same problem with other merchants also.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, it was a generic issue which is now resolved.

**Comment by vassilismon85** [comment]
Great. I don't know if I can ask you something else in this issue. I am having some customers who want to have TIP enabled in the simple checkout gareway. So the final consumer can add some money as a tip for the person that will deliver the order. Is it something like a feature to enable on the Simple Checkout?

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, unfortunately `tipAmount` isn't supported in the available parameters listed here: https://developer.vivawallet.com/online-checkouts/simple-checkout/#configuration-options

**Comment by vassilismon85** [comment]
@matthewrgourd .Thanks a lot. Closing the issue
