### ISSUE TITLE
Simple Checkout payment  response error (Demo)

### ISSUE THREAD

**Issue by HarishankarIT** [VivaPayments/API#2086]
Hi,

While doing a simple checkOut the payment response is not coming (error) in Demo (sandbox). And also In the sandbox account sales Transaction, no records are there.
Please let us know asap.
publickey="o74hi+EXG4rPLV6ZRyirmTAoTOWCLVSIz1gLYfNKe8M="

Regards,
HariIT

**Comment by matthewrgourd** [comment]
Hi @HarishankarIT are you using our test card 5511070000000020 as recommended in the Viva Wallet Developer Portal? Unfortunately there is a problem with this at the moment. I'll update you once I know more...

**Comment by HarishankarIT** [comment]
Hi,
no, I am not using this card number(5511070000000020). I am using another test card for the simple check out payment.

**Comment by HarishankarIT** [comment]
Hi matthewrgourd,
No, I am not using this card number(5511070000000020). I am using another test card for the simple check out payment.

**Comment by matthewrgourd** [comment]
Hi @HarishankarIT, I have an update for you: the 3DS simulator is provided by Modirum, a third-party company we use. The problem is on their side and unfortunately I currently don't have an ETA for a fix. In the meantime you can use the below cards to simulate successful / unsuccessful outcomes. These bypass the popup and are therefore the equivalent of frictionless transactions:

Long card number | Issuer | CVC | Expiry date | 3DS outcome
-- | -- | -- | -- | --
5188340000000011 | Mastercard | Any 3 digits | Any future date | Success
4016360000000010 | Visa | Any 3 digits | Any future date | Success
5188340000000029 | Mastercard | Any 3 digits | Any future date | Not authenticated
4016360000000028 | Visa | Any 3 digits | Any future date | Not authenticated

Hope this helps!
