### ISSUE TITLE
Problem With Redirect Checkout

### ISSUE THREAD

**Issue by dgkimisis** [VivaPayments/API#2088]
Good evening and happy new year, 

We are using redirect checkout(https://developer.vivawallet.com/online-checkouts/redirect-checkout/) for our beta application to perform test purchases.

We are making a successful API request to https://demo.vivapayments.com/ with
Merchantid - 02d4db03-c4d8-48f3-b6b3-b151843cf932 

and thus we get successfully redirected to https://demo.vivapayments.com/web/checkout?ref=3611840339172609 where we tried to make a purchase with the the card number 5511070000000020 with any valid date and 111 for the CVV2
 
When we pressed the Purchase button we were redirected to fail url(TransactionId - b89830cb-512a-481e-9b2e-29a5de288798)

How is it possible to get redirected to fail url after submitting the form https://demo.vivapayments.com/web/checkout for this transaction?(I am using https for redirect)

Thank you in advance,
D. Gkimisis

**Comment by matthewrgourd** [comment]
Hi @dgkimisis, heppy new year to you, too! I'm told there's a general issue with the test environment currently, meaning that the test card 5511070000000020 doesn't provide predictable outcomes. There is an upgrade taking place to alleviate this which should be completed today or tomorrow. I'll update you when I know more.

**Comment by matthewrgourd** [comment]
Hi @dgkimisis, I have an update for you: the 3DS simulator is provided by Modirum, a third-party company we use. The problem is on their side and unfortunately I currently don't have an ETA for a fix. In the meantime you can use the below cards to simulate successful / unsuccessful outcomes. These bypass the popup and are therefore the equivalent of frictionless transactions:

Long card number | Issuer | CVC | Expiry date | 3DS outcome
-- | -- | -- | -- | --
5188340000000011 | Mastercard | Any 3 digits | Any future date | Success
4016360000000010 | Visa | Any 3 digits | Any future date | Success
5188340000000029 | Mastercard | Any 3 digits | Any future date | Not authenticated
4016360000000028 | Visa | Any 3 digits | Any future date | Not authenticated

Hope this helps!

**Comment by dgkimisis** [comment]
Thank you for your response.
The problem was solved when I used MasterCard with no 5188340000000011 and I was redirected to success url.
