### ISSUE TITLE
Joomshopping and "Παρουσιάστηκε ένα σφάλμα Order not found"

### ISSUE THREAD

**Issue by diastasi** [VivaPayments/API#2092]
First of all the file that you give as payment addon for joomshopping is not OK.
I created a new zip file with the proper structure and I managed to install the vivawallet addon.
I created an account in DEMO, put the credentials in VIVAWALLET payment addon and tried to make a purchasing.
By click "Proceed Order" the next page was "https://xxxxxxxxx.gr/viva.php" and in 1sec redirected to "https://www.vivapayments.com/web/newtransaction.aspx?Ref="
The result is "Παρουσιάστηκε ένα σφάλμα - Order not found "

**Comment by matthewrgourd** [comment]
Hi @diastasi, sorry to hear that. Did you set up your Sueccess/Failure URLs in the Viva Wallet payment source as outlined in our [installation guide](https://developer.vivawallet.com/e-commerce-plugins/joomshopping/)?

- **Success URL** – yourdomain.gr/viva.php?success
- **Failure URL** – yourdomain.gr/viva.php?fail

So that I can investigate further, may I have your website address, please?

**Comment by diastasi** [comment]
Of course I followed the instuctions about joomshopping. Also I did everything in Demo vivawallet account.
![Screenshot_1](https://user-images.githubusercontent.com/77298233/104307881-7951b880-54d8-11eb-89bd-730068dd8d5b.jpg)

The address is e-magazi.gr
There is a demo customer account with demo/demo as credentials
![Screenshot_2](https://user-images.githubusercontent.com/77298233/104307946-8e2e4c00-54d8-11eb-978d-f241cc35b252.jpg)

**Comment by matthewrgourd** [comment]
Hi @diastasi, your settings look fine. Which version of JoomShopping are you using?

**Comment by diastasi** [comment]
joomla 3.9.24 and Joomshopping 4.18.5 (both latest)
As about the original vivawallet package, was not working, as @kazanakius wrote (https://github.com/VivaPayments/API/issues/1980 ) so I follow another instruction I found in github and create the following package to install:
[joomshopping_viva1.zip](https://github.com/VivaPayments/API/files/5804562/joomshopping_viva1.zip)

**Comment by diastasi** [comment]
I just install locally (with xampp) a fresh joomla and joomshopping (same versions) and did the same thing.
That means all joomshopping installation have the same problem??

**Comment by diastasi** [comment]
Do we have any kind of solution???

**Comment by kazanakius** [comment]
Yes... I have found a solution, it now works for me.. but I am trying really hard to remember exactly what I did, but I can't remember all the details, as it has been several months since I did it.
What I can remember, is that I unzipped the plugin which is offered by viva wallet, I created a folder inside it (i believe the name was pm_viva) in which I placed the already existing folders of the plugin, I zipped it again and installed it.
I hope that this helps you resolve it, and then post here the full proccess for the rest of the people to read.

The problem with the plugin, is that the folder structure is wrong. The contents of the zip have to be placed inside an other folder. I am not sure about the name that you have to use. Check "pm_viva"

**Comment by matthewrgourd** [comment]
Hi @diastasi, did the above solution from @kazanakius work for you?

**Comment by diastasi** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/77298233/104735116-e0c26f00-5749-11eb-9ee4-b55fb77663a2.jpg)

No, exactly the same thing,
What versions does @kazanakius is using? I told you Im using joomla 3.9.24 and Joomshopping 4.18.5

**Comment by kazanakius** [comment]
I m using same version

**Comment by diastasi** [comment]
@kazanakius Μπορώ να κάνω μία δοκιμαστική παραγγελία στο https://www.popshop.com.gr/ ???

**Comment by matthewrgourd** [comment]
Hi @diastasi, in that case, one of our developers will need to look at the plugin code and check what the issue is. Before you got that "Order not found error", which payment method did you choose, **Pay by card**, or **Pay by Viva Wallet** (personal account)?

**Comment by diastasi** [comment]
Pay by Viva Wallet (businness demo account)

**Comment by matthewrgourd** [comment]
Hi @diastasi think I just need to test again your website. Just to confirm, is it e-magazi.gr? Can you keep demo mode enabled so I can check the **Pay by Viva Wallet** feature with one of my colleagues?

**Comment by diastasi** [comment]
Yes it is https://e-magazi.gr/
the demo customer account is user:demo, pass: demo

**Comment by matthewrgourd** [comment]
Hi @diastasi, thanks for providing those details. I've been able to recreate the issue but I don't immediately understand why it is happening. The only thing I can think currently is that the plugin is not compatible with user accounts. Is there any way you can test without the _Create account_ option being available?

**Comment by diastasi** [comment]
I just tried it, still the same problem. I will try to install locally the same version of Joomla but an earlier version of Joomshopping (2 versions before) and test it.

**Comment by diastasi** [comment]
Everything is working FINE @matthewrgourd  @kazanakius .
I told you at first that "Also I did everything in DEMO vivawallet account."
DEMO is not working. !!!!! Please explane to customers that you mention about DEMO but it is NOT working

As soon as I change to normal account everything Worked !!!!!
