### ISSUE TITLE
Hablado y Escrito SL

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#2093]
Hi @matthewrgourd Happy new year my friend, I hope that you could rest very well for working hard again :)

Can you check it for me if this merchant has well set up settings for woocommerce
![foto 1](https://user-images.githubusercontent.com/56823712/104299077-0b4fc600-54c5-11eb-893b-40236d5dc67b.jpg)
![foto 2](https://user-images.githubusercontent.com/56823712/104299092-10147a00-54c5-11eb-94eb-26c4c2695b09.jpg)
![foto 3](https://user-images.githubusercontent.com/56823712/104299100-14409780-54c5-11eb-9d49-2a03b626b74c.jpg)
![foto 4](https://user-images.githubusercontent.com/56823712/104299110-173b8800-54c5-11eb-863e-bee4421cc251.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, happy new year to you, too! All looks fine in terms of the settings. Why do you ask, is the merchant experiencing a problem?

**Comment by Alvaroalconada** [comment]
@matthewrgourd I think yes but I´m going to ask more things in order to be more specific with the issue, thx

For future issues I´ll send you an email as you told me by teams

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, thanks a lot!

I have tested this merchant's checkout and payment through Viva Wallet seems to get 'stuck'. Can you check if the merchant has php cURL installed on their server? This may be where the problem lies. Let me know...

**Comment by Alvaroalconada** [comment]
@matthewrgourd What that´s mean php cURL?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada if the merchant doesn't understand what it means, don't worry about it. I think it was a bit of a long shot! I've done a bit more investigating and it looks like the merchant is using a theme called [Flatsome](https://flatsome3.uxthemes.com/). If they're still having an issue, can you get them to test with one of WordPress's default themes like Twenty Seventeen. If it works then they'll know the problem is related to the theme.

**Comment by Alvaroalconada** [comment]
hi @matthewrgourd merchant record me a video

https://user-images.githubusercontent.com/56823712/104308762-756e6800-54d1-11eb-8536-677c4d8c2159.mp4

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, thanks for that! It's exactly what I said, the payment progress indicator gets 'stuck'. My advice is as above, they need to test our plugin with one of WordPress's default themes like Twenty Seventeen. If it works then they'll know the problem is related to the theme.

**Comment by Alvaroalconada** [comment]
@matthewrgourd Can you indicate me over here which plugin has to test because I don´t get to find it

**Comment by matthewrgourd** [comment]
@Alvaroalconada  the merchant is using a theme called Flatsome. As a test, they need to swap that for a default theme such as Twenty Seventeen. They should know how to do that.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd stays the same as before. Look at this

https://user-images.githubusercontent.com/56823712/104423256-23375080-557e-11eb-8179-2580121bb932.mp4

**Comment by matthewrgourd** [comment]
@Alvaroalconada is this after changing the theme temporarily?

**Comment by Alvaroalconada** [comment]
@matthewrgourd yes that´s it!

**Comment by matthewrgourd** [comment]
@Alvaroalconada, in that case, please can you get him to provide the following info. for us to investigate further:

- I'd like to check if any other software could be interfering with ours. He can find out all the plugins installed from **WooCommerce > Status** in his Wordpress admin. In there he'll see lots of info. but he should click on the **Get system report** button, then **Copy for support** button. He should paste into a text file and send to you for inclusion in this issue. Thanks!
- We need to also get hold of a log file for the plugin, instructions below:
1. Go to **WooCommerce > Status > Logs** tab:

![log1](https://user-images.githubusercontent.com/44943019/99075879-2039d700-25b2-11eb-806d-f45cc6441d68.png)

2. Select relevant date from the dropdown (below screenshot is just for illustrative purposes. He should choose today's or yesterday's date, whichever is most relevant):

![log2](https://user-images.githubusercontent.com/44943019/99075893-262fb800-25b2-11eb-844d-bbf073524f3f.png)

3. Click on the **View** button.

4. Copy the contents into a text file and save it with an appropriate name. 

5. Attach to this issue in .txt format.

**Comment by Alvaroalconada** [comment]
hi @matthewrgourd here I let you the things that you requested before:
[informe wooc.txt](https://github.com/VivaPayments/API/files/5808444/informe.wooc.txt)
[log woo.txt](https://github.com/VivaPayments/API/files/5808446/log.woo.txt)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, thanks for those. Still investigating. Nothing in the log files. If you could get them to provide log files for the following dates and send those through too?

- Tuesday 12 Jan
- Monday 11 Jan

In the meantime I'm speaking to the developer who made the plugin as it's a bit of an odd case. Normally we don't have problems with this plugin.

Thanks!

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, our plugin developer has looked into this and it's something to do with their security policy. Our plugin is set up correctly and will work fine once their developer checks the following.

We think they have some kind of whitelist security setting as shown below:

![Screenshot 2021-01-13 at 5 44 07 PM](https://user-images.githubusercontent.com/44943019/104476479-2f400400-55b8-11eb-8beb-84b75569e486.png)

He should look at the below general info about security:

https://developers.google.com/web/fundamentals/security/csp?utm_source=devtools#source_whitelists

Also this about finding out if a website has a content security policy applied:

https://blog.bluetriangle.com/how-to-find-out-if-a-site-has-a-content-security-policy-csp-deployed

This is a screenshot of the information our developer has found out about his website from the Chrome developer console. It shows that there is a policy applied:

![Screenshot 2021-01-13 at 5 50 22 PM](https://user-images.githubusercontent.com/44943019/104476783-880f9c80-55b8-11eb-8c76-beffaa2faecf.png)

Provided he has technical skills, he can add a header or a meta tag to add a whitelist rule for prismic.com and vivapayments.com domain in order to whitelist the images cdn and our script file to load.

Hope this helps!

**Comment by Alvaroalconada** [comment]
hi @matthewrgourd merchant told me that there aren´t any registers

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, no worries, that's because we the think there is a more general issue as reported in my [more recent update](https://github.com/VivaPayments/API/issues/2093#issuecomment-759548081), above. Please pass on all that info verbatim and see if they can solve the issue themselves based on that.
