### ISSUE TITLE
Problem error 10301

### ISSUE THREAD

**Issue by DaveMTC** [VivaPayments/API#2136]
Hello good,

We have an account with you "Cloud Distro S.L", we have been working for a long time and for a month we have been receiving 10301 errors, we do not know why it is.

We have the integration via Native Checkout v2 API and Card Tokenization API.

We need some help.

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_

**Comment by matthewrgourd** [comment]
@DaveMTC, sorry to hear that. Please note that our API regarding the use of card tokens has been amended, and in particular the step to 'generate one-time charge token using saved card token' (step 5 in https://developer.vivawallet.com/web-api-integration/card-tokenization-api/). This step requires now the use of /nativecheckout/v2/chargetokens with the card token as input to the call; the change was done so that 3DS is now triggered in such cases (and thus eliminate the potential soft declines in these cases). We have also amended the error codes page to include the 10301 code for soft decline (refer to https://developer.vivawallet.com/web-api-integration/error-codes/).
