### ISSUE TITLE
Can't create webhook

### ISSUE THREAD

**Issue by Jhacarreiro** [VivaPayments/API#2156]
I'm assuming this is because I failed to create the webhook according to your instructions [here](https://developer.vivawallet.com/plugins/viva-wallet-woocommerce-gateway/).

Could this be because our domain is https://osmium.capital and it doesn't pass some validation expecting ".com" or similar? The address seems to be accessible and valid, this is what I tried to input: https://osmium.capital/index.php?wc-api=wc_vivawallet&vivawallet=webhook

And I get back an error saying it can't be verified error code 502.

Thank you,

Log:
`2022-03-18T08:55:10+00:00 CRITICAL Uncaught Error: Class "WC_Payments_REST_Controller" not found in /home/kukzgvi/www/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-rest-payments-accounts-controller.php:13
Stack trace:
#0 /home/kukzgvi/www/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php(582): include_once()
#1 /home/kukzgvi/www/wp-includes/class-wp-hook.php(307): WC_Payments::init_rest_api(Object(WP_REST_Server))
#2 /home/kukzgvi/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#3 /home/kukzgvi/www/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#4 /home/kukzgvi/www/wp-includes/rest-api.php(553): do_action('rest_api_init', Object(WP_REST_Server))
#5 /home/kukzgvi/www/wp-includes/rest-api.php(379): rest_get_server()
#6 /home/kukzgvi/www/wp-includes/class-wp-hook.php(307): rest_api_loaded(Object(WP))
#7 /home/kukzgvi/www/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#8 /home/kukzgvi/www/wp-includes/plugin.php(522): WP_Hook->do_action(Array)
#9 /home/kukzgvi/www/wp-includes/class-wp.php(396): do_action_ref_array('parse_request', Array)
#10 /home/kukzgvi/www/wp-includes/class-wp.php(758): WP->parse_request('')
#11 /home/kukzgvi/www/wp-includes/functions.php(1310): WP->main('')
#12 /home/kukzgvi/www/wp-blog-header.php(16): wp()
#13 /home/kukzgvi/www/index.php(17): require('/home/kukzgvi/w...')
#14 {main}
  thrown in /home/kukzgvi/www/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-rest-payments-accounts-controller.php on line 13`

**Comment by can3ry** [comment]
Hello and thank you for your question,

When you define an address and click the save button, Viva Wallet sends a GET request to that URL to verify the address. If the URL returns a [merchant-specific token](https://developer.vivawallet.com/webhooks-for-payments/setup-webhooks/#response-example) with 200 HTTP status, Viva Wallet verifies and saves the webhook URL. Otherwise, you get a 502 error. 

When I try to open [your webhook URL](https://osmium.capital/index.php?wc-api=wc_vivawallet&vivawallet=webhook), it returns HTTP code 400 and prints -1 to the page. A reason can be that you did not activate our Viva Wallet Smart Checkout plugin on WordPress.  Before saving a webhook URL on [Viva Wallet self-care](https://demo.vivapayments.com/selfcare/en/home), please ensure that you have activated the smart checkout plugin and updated its settings [according to this page](https://developer.vivawallet.com/plugins/viva-wallet-woocommerce-gateway/).

If you already activated the plugin but still got an error, plugins might have conflicts. The logs you shared seem to belong to another plugin named WooCommerce Payment. Could you please provide more details on how did you get this log? Could you also test it by deactivating the WooCommerce Payment plugin and activating only the Viva Wallet Smart Checkout plugin?

Regards,
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello,
The instructions [here](https://developer.vivawallet.com/plugins/viva-wallet-woocommerce-gateway/) are for our WooCommerce **Smart Checkout** plugin. I understand from the logs that you are using the WooCommerce **Standard Checkout** plugin. You don't need to set up a webhook URL for this plugin; please refer to [this page](https://developer.vivawallet.com/plugins/woocommerce/). You can also check the [WooCommerce documentation](https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/).
Please let us know if you need further assistance on this.
Viva Wallet Development Team

**Comment by Jhacarreiro** [comment]
How is this solved if I keep getting the error at check out? The money is
charged but the customer is informed that it wasn't.

I understand the error doesn't come from the web hook but that was just an
assumption from me of what the problem could be.

The error is still there and not working.



A quinta, 24/03/2022, 22:50, can3ry ***@***.***> escreveu:

**Comment by Jhacarreiro** [comment]
I changed the plugin for the smart checkout one and the error persists. webhook creation still fails. Already confirmed with support in Portugal that the "source" was created and is active.

![image](https://user-images.githubusercontent.com/19389037/160096810-a364547b-667a-49bc-b08a-d12fdb1eaf8d.png)

**Comment by can3ry** [comment]
Hello @Jhacarreiro,
I've deleted your last comment as it has API key information, which is private.
I see that the source code you shared belongs to WooCommerce **Standard Checkout**. It is WC-0001. The success/fail redirect URLs of **Standard Checkout** are different from the **Smart Checkout** redirect URLs. I've noticed that you did not update the URLs from the Viva Wallet's self-care, so please refer to [this page](https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-online-payments/) and **create a new source code** for the **Smart Checkout plugin**. And then, please update the source code field in the WooCommerce Smart Checkout plugin settings.
Viva Wallet Development Team

**Comment by Jhacarreiro** [comment]
Thank you for the support. I didn't find out exactly what was causing it but I did solve it with a free plug-in to redirect to another "success/thank you page" after the transaction if that helps anyone in the future!
