### ISSUE TITLE
Viva Wallet Standard Checkout for woocommerce 503

### ISSUE THREAD

**Issue by TechNoLogicRho** [VivaPayments/API#2187]
Hello,
trying to setup viva for two woo based websites using the official plugin from here https://woocommerce.com/document/viva-wallet-standard-checkout/#upgrading-the-plugin
On the first one everything was ok a couple of days ago. Now on both i am getting the following error when submitting payment.

https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens
status: 503, message: "PayShieldTransportChannelWriteFailedNotActive", eventId: "4714"}
eventId: "4714"
message: "PayShieldTransportChannelWriteFailedNotActive"
status: 503

Any ideas?

**Comment by cforrestvivawallet** [comment]
Hi @TechNoLogicRho,

Thanks for submitting your query. May I ask a few questions in order to investigate this for you?

1. Are you using the same Viva Wallet account/credentials to install the WooCommerce plugin on two separate sites?
2. Can you send across the full API call(s) you are making, and the responses you are receiving, when seeing this error?
3. Are you able to provide any logs from WooCommerce, [as per this link](https://woocommerce.com/document/viva-wallet-standard-checkout/#section-30)?

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
HI @TechNoLogicRho,

As far as I know, nothing has changed but I am glad to hear it is working correctly now!

I will close out this issue but please don't hesitate to reach out if you have any further questions or problems.

Kind regards,
Viva Wallet Development Team
