### ISSUE TITLE
woocommerce 404 redirect after purchase

### ISSUE THREAD

**Issue by embeddedskills** [VivaPayments/API#2231]
Hi, 

I currently have a problem with the vivawallet woocommerce plugin, 
after a purchase there is a problem with the redirect back to the "thank you page" in wordpress,
instead we get a 404 not found while the url seems to have two times the hostname before the path: e.g. https://hostname.comhttps://hostname.com/path...
Additionally, the order is not set as completed and no e-mail is sent while the customer's card is charged.

Anyone else is facing this issue?

Thanks in advance!

**Comment by can3ry** [comment]
Hello,

In order to investigate further, could please confirm that you've set the source code as mentioned [here](https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-online-payments/)? Also a screenshot is provided below. Could you also send your merchant id?

<img width="470" alt="woo-src" src="https://user-images.githubusercontent.com/51880555/181235583-777def64-bb50-4ecf-a576-8e6b094380c3.png">

Best regards
Viva Wallet Development Team

**Comment by embeddedskills** [comment]
Hi I will get back to you with these details, 
thank you for responding

**Comment by embeddedskills** [comment]
Hi it seems that the client did not set the success and failure URLs, now it seems to be working
