### ISSUE TITLE
Flutter web

### ISSUE THREAD

**Issue by BGGBGIBS** [VivaPayments/API#2253]
How could I open the payment URL in flutter web ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BGGBGIBS.

In order to integrate our Smart Checkout with your application please follow the documentation that you can find [here](https://developer.vivawallet.com/tutorials/smart-checkout-configuration/integrate-with-a-mobile-app/).

For any questions we are at your disposal.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BGGBGIBS. Have you found the time to review our answer?

Therefore, this ticket will remain active for at least 24 hours, so that you can come back if you wish. Thank you very much for contacting us.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BGGBGIBS.

I will close this ticket now, but please do not hesitate to get in touch if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
