### ISSUE TITLE
Clarification on EFT POS solution

### ISSUE THREAD

**Issue by SamuelMichelRiad** [VivaPayments/API#2265]
Hi team,

We have the following questions about the cloud-based EFT POS solution, which are not covered by the documentation.

1. To get a bearer token, we must call the /connect/token service. This requires a client ID and client secret. Where can we generate this client ID/secret, or is that something Viva Wallet IT will provide?
2. In the /ecr/v1/transactions:sale request, the **sessionId** and **cashRegisterId** fields are required. Can you confirm that we can set these two values to whatever we choose?
3. How do we include ISV parameters (ISV amount, client id/secret, etc.) to the /ecr/v1/transactions:sale request?

Thanks

**Comment by SamuelMichelRiad** [comment]
Thank you for the answers. Can you please advise on a tentative date for when the API will be released? Also, are there any plans to make the printing functionality available through the API or will we be forced to print the default payment receipt through the Viva POS app?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

The estimated release date is around the end of October, but this may change. For the functionalities our cloud-based EFT POS will provide, stay tuned at our[ Developer's Portal](https://developer.vivawallet.com/).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

I just wanted to follow up on the reply I sent yesterday. I was simply wondering if you read my response. Are there any other questions, I may help you with?

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

I hope this information helps, however, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

Since it's been a while since we last heard from you, we will close this ticket.
We hope this information helps, however, should you have any questions, please don't hesitate to reply back here and we would be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team
