### ISSUE TITLE
EFT POS url

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2271]
Hi,

I would like to [initiate a sale request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Transactions/paths/~1ecr~1v1~1transactions:sale/post) using the EFT POS API.

What are the live and sandbox servers to use with that api? I.e. what server hosts the `/ecr/v1/transactions:sale` endpoint?

Moreover, it is highly unusual to see a : in a URL. Is it a typo?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you very much for contacting us. Keep in mind that the cloud-based EFT POS solution is still under development. This means that it is not yet ready for use. Also due to this there are some gaps in our documentation, which will be completed soon.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi,

Our local VivaWallet representative told us as much. But we want to be ready when the EFT POS API becomes operational.

I'll get in touch by email if you prefer not to publicly release the relevant information for now.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

The estimated release date is around the end of October, but this may change. For more up to date information about our cloud-based EFT POS solution please check our [developer's portal](https://developer.vivawallet.com/) regularly.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Did you find the time to review our answer?

In any case this ticket will remain active for at least 24 hours, to come back if you wish. Thank you very much for contacting us.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Since it's been a while since we last heard from you, we will close this ticket.
We hope this information helps, however, should you have any questions, please don't hesitate to reply back here and we would be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team
