### ISSUE TITLE
Failded Payment

### ISSUE THREAD

**Issue by Emytica** [VivaPayments/API#2277]
Hi,
I tried to make a payment test at this link:
https://demo.vivapayments.com/web/checkout?ref=430024927216547
Using test card 4147 4630 1111 0133 I receive FAILED with eventId=1

to receive the orderCode I sent this request:
Request: {"sourceCode":"6416","amount":1,"preauth":false,"paymentNotification":false,"customerTrns":"testPagam"}
Response: {"orderCode":4300249272165473}
The request was sent with permission oauth2.
Why am I getting FAILED ? I do something wrong?
regards,
Emilia

<b>Italiano:</b>
Ciao,
ho provato a far un pagamento test a questo link:
https://demo.vivapayments.com/web/checkout?ref=430024927216547
utilizzando la carta di test 4147 4630 1111 0133 ricevo FAILED con eventId=1
per ricevere l'orderCode ho inviato questa richiesta:
Request: {"sourceCode":"6416","amount":1,"preauth":false,"paymentNotification":false,"customerTrns":"testPagam"}
Response: {"orderCode":4300249272165473}
la richiesta è stata inviata con l'autorizzazione OAuth2.
Perché ricevo sempre failed? Sbaglio qualcosa?
Grazie,
Emilia

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

Thank you for contacting us. Could you please try executing a test transaction by using a different test card? If the issue persists let us know by providing us the error code. Thanks in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response. 

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

We hope this information helps, however, should you have any questions, please don't hesitate to reply back here and we would be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

We will close this ticket now, but please do not hesitate to get in touch if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
