### ISSUE TITLE
Viva ECR API

### ISSUE THREAD

**Issue by melaurent** [VivaPayments/API#2278]
Hello, is the ECR API ready to be used ? If so, what is the base enpoint ? https://www.api.vivapayments.com/ecr/v1/transactions:sale
or https://www.vivapayments.com/api/ecr/v1/transactions:sale

Thanks

**Comment by fmarchalemisys** [comment]
Hi melaurent,

Vivawallet updated the [doc](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Transactions/paths/~1ecr~1v1~1transactions:sale/post) a couple of days ago.

Now, the full url is documented in the drop down that pops when you click on the sample url.

It is the demo url though: https://demo-api.vivapayments.com/ecr/v1/transactions:sale

I guess the production [url should be](https://developer.vivawallet.com/tutorials/) https://api.vivapayments.com/ecr/v1/transactions:sale

But I believe it is not working yet as I can't get a valid OAuth token.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @melaurent,

Thank you very much for contacting us. Keep in mind that the ECR API is still under development. Also due to this there are some gaps in our documentation, which will be completed soon.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by melaurent** [comment]
Is there any other way we can trigger a transaction on the terminal remotely ? We currently have to type the amount on the machine.

**Comment by fmarchalemisys** [comment]
Support may have a more comprehensive response. Here is my two cents.

If the ECR and the payment terminal are in the same LAN, you can start a payment in [ECR mode with TCP paquets](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/vivawallet-api-cl/) sent from the ECR to the terminal.

You need to know the IP address of the terminal (it is displayed in the terminal's menu) then connect to that IP address with tcp socket from the ECR.

You must send a [txSaleRequest](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/vivawallet-api-cl/sale/#txsalerequest) to initiate a payment.

I got it working with a Pax Q30. I don't know if that protocol is supported by soft pos app.

**Comment by fmarchalemisys** [comment]
[According to the doc](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/vivawallet-api-cl/#requirements-and-limitations) soft pos app is not supported. Both the terminal and the merchant account must be configured for ERP/ECR mode.

**Comment by melaurent** [comment]
Thanks, that sucks, we were going to order a Q30 and do ECR/TCP but we ended up ordering a soft pos because we thought we could do remote sale through REST .....

**Comment by VivaWalletCustomerSupport** [comment]
Hello @melaurent,

Thank you very much for contacting us. If the ERP/ECR and the terminal are in the same LAN, you can remotely trigger a transaction using [Migrating from a previous Cardlink integration](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/vivawallet-api-cl/). 

Our ECR API is still under development. When the API is released you can use it to trigger a transaction remotely regardless in which network the terminal is connected. Our ECR API will be compatible with Soft POS devices.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by melaurent** [comment]
Hello @VivaWalletCustomerSupport , does the Viva Wallet NEXT supports same LAN ERP/ECR communication ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @melaurent, 

Our ERP/ECR integration is supported by our A910, A920/A920 Pro, A80 and Q30 devices.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @melaurent,

We just wanted to follow up on the reply we sent on Friday. We were simply wondering if you read our response. Are there any other questions, we may help you with?

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

We hope this information helps, however, should you have any questions, please don't hesitate to reply back here and we would be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport 

I just want to clarify this part of your answer:

> We were simply wondering if you read our response

@melaurent said he was about to order a Q30 but went for a **WV pos app** instead expecting to use the documented EFT API.

As EFT API is not available yet and ECR is not supported with WV pos app, it turns out he is left without a solution.

Your last suggestion of using a terminal he doesn't have is a moot point.

Can you instead offer a tentative date as to when the EFT API might be ready? It might be cheaper and faster to wait for the API to be ready than to purchase a Q30 and write a ERP/ECR bridge.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @melaurent, @fmarchalemisys,

Thank you very much for the provided information. Our ECR API is expected to be live until the end of November / early December.

Kind regards,
Viva Wallet E-commerce Support Team
