### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by MaestrelWP** [VivaPayments/API#2293]
Hi,
I am unsure that this need to be posted here, so feel free to inform me if I need to use a different channel to ask my question.
I am developing the integration of VivaWallet Smart Checkout as payment gateway for my WordPress online booking system plugin. I receive a 401 Unauthorized header response status when doing a curl request to https://demo-api.vivapayments.com/checkout/v2/orders. I correctly get an access token in the previous step and I have it added in the curl header as "Authorization : Bearer $access_token_goes_here". The response header is 401.

I am in Sandbox environment and my VivaWallet account ID is 811625746974

Kind regards

Celine

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MaestrelWP,

Thank you very much for contacting us. Can you provide us the scope that was created when the access token was generated? 
Kindly note that in access token creation [Smart Checkout credentials](https://developer.vivawallet.com/getting-started/find-your-account-credentials/client-smart-checkout-credentials/) should be used.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MaestrelWP,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

I hope this information helps, however, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by MaestrelWP** [comment]
Hi,

Yes, I use my sandbox Smart Checkout credentials :
- Smart checkout creds : https://tinyurl.com/2kmh7poj
- entered in my plugin HBook (that is working nicely, we have developped
more than 30 payment gateways addons for our booking system HBook) :
https://tinyurl.com/2lln4p8w

The scope is : urn:viva:payments:core:api:acquiring
urn:viva:payments:core:api:acquiring:cardtokenization
urn:viva:payments:core:api:redirectcheckout

You can check here: https://lodgyk.com/hbook-vivawallet/

I have pasted the part of code where the successive calls to access token
and then payment session token are : https://codeshare.io/ZJM387. It goes
to line 131 as response is status 401 UNAUTHORIZED*.*

Kind regards

Celine Godard
_______________________________________________________________


WordPress themes and plugins for the hospitality industry
WP Themes <https://maestrel.com/themes/> - WP Booking system HBook
<https://maestrel.com/hbook/>

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MaestrelWP,

Thank you for the additional information. Can you please send the endpoint URL you are making the call for the order code creation?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by MaestrelWP** [comment]
Hi,

The call is made to https://demo-api.vivapayments.com/checkout/v2/orders

Kind regards
Celine

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MaestrelWP,

Thank you for your response. We would like to advise you to check again your implementation. From your website we generated a bearer token and successfully generated an order code with [the sample code](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/#step-1-create-the-payment-order). 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MaestrelWP,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

I hope this information helps, however, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by MaestrelWP** [comment]
Hi,

Thank you. Fixed. The issue was indeed with the headers code.
