### ISSUE TITLE
Shopify Installments

### ISSUE THREAD

**Issue by pantelispanayiotou** [VivaPayments/API#2294]
Using viva integration with shopify, is there any way my customer can pay the amount in installments. If for example customer chooses to pay 100 euros in 5 installments then somehow viva can charge with a recurring order each month the corresponding amount.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pantelispanayiotou,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

I hope this information helps, however, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pantelispanayiotou,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
