### ISSUE TITLE
Problem retrieving transactionId on failed payments(demo env)

### ISSUE THREAD

**Issue by Octapius** [VivaPayments/API#2297]
Dear VivaWallet development team,
We have run into an issue with our demo development account.
We are able to do transactions with valid cards and be directed back to our success page with a valid transaction id without problem.
Nevertheless, we are running into two issues, which only happens in demo, and not in our production environment.

Firstly, the failed transaction is not being logged into our demo account, and secondly, the redirection to our failure url comes with null **t**(transactionId) and as a result /checkout/v2/transactions/{transactionId} API, responds with a 404 error, when we are trying to retrieve it.

In order to achieve identical implementation and behavior in both environments, we would like your technical feedback in order to figure out why this is happening.

Thank you in advance for your help.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Octapius,

Thank you very much for contacting us. Can you please provide us the MID of your demo account and the amount of the order of a failed attempt?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Octapius,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Octapius,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
