### ISSUE TITLE
Recurring Payments

### ISSUE THREAD

**Issue by IliasStathakopoulos** [VivaPayments/API#2300]
Is possible to make a recurring payment due to viva wallet api , with all payment methods? 
Because when i set the parameter  allowRecurring=true the  methods i can make a payment are the credit card and the Googlepay.
I want to make recurring payments with PayPal , viva wallet and all the other methods. Is there a way to do that?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @IliasStathakopoulos,

Thank you very much for contacting us. Kindly note that PayPal and Viva Wallet payment method do not support recurring payments. You can find all the payment methods we support with all the features supported [here](https://developer.vivawallet.com/payment-methods/).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @IliasStathakopoulos,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

I hope this information helps, however, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team
