### ISSUE TITLE
implement the viva wallet smart checkout in javascript

### ISSUE THREAD

**Issue by SALEEMDADU420** [VivaPayments/API#2301]
I am trying to implement the viva wallet in my ecommerce website the technology I am using is JavaScript but I don't  how to implement the viva wallet in JavaScript

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SALEEMDADU420,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

I hope this information helps, however, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SALEEMDADU420,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
