### ISSUE TITLE
Obligation Created webhook does not fire in demo environment

### ISSUE THREAD

**Issue by lukawolf** [VivaPayments/API#2303]
I am implementing VivaWallet payments for use in our web and mobile app services. When a payment goes through we do not receive a webhook notification of the fact.

Steps taken:
1) Registered and verified a webhook
2) Created a new payment via v2 orders api
3) Paid using a test Visa card (master card works neither)

VivaWallet functionality expected:
1) Redirect to success url
2) Send a webhook confirming the payment status

Functionality observed:
1) Redirect to success url

In order to expedite the solving of this issue, I include the following details
Viva Account ID: 350654437898
Payment IDs:
?t=a1dac70a-357d-4d2f-bd1c-7a67b7793010&s=3379342681671547
?t=e0cd3d43-ac9b-4c64-a992-4f6e5e94cc61&s=3879412363442707

The Transaction Failed webhook also does not fire for failed statuses:
?s=2979451644902931

**Comment by VivaWalletCustomerSupport** [comment]
Hello @lukawolf,

Thank you very much for contacting us. Kindly note that [Obligation Created](https://developer.vivawallet.com/webhooks-for-payments/obligation-created/) webhook is available only for marketplace. If your account is not a marketplace account we would like to advise you to use [Transaction Payment Created ](https://developer.vivawallet.com/webhooks-for-payments/transaction-payment-created/)webhook.

About the Transaction Failed webhook, we would like to inform you that will fire only in failed attempts that are visible on your Viva Wallet account. In order to trigger a decline with test cards a specific amount should be used. The amount should be in the range 99.01 € to 99.98 €. Kindly note that if the transaction amount is into the range we mentioned before the transaction will fail regardless which card will be used.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @lukawolf,

We just wanted to follow up on the reply we sent on Friday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @lukawolf,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
