### ISSUE TITLE
WHMCS gateway module

### ISSUE THREAD

**Issue by dewinbrush** [VivaPayments/API#2304]
I'm searching any WHMCS Gateway module which is not exist. Is there any plan to release it? or any source for SmartCheckout?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @dewinbrush,

Thank you very much for contacting us. Kindly note that we do not have a ready-made plugin at the moment, however if your platform allows 3rd party API Integrations you can integrate with Smart Checkout.

To implement our Smart Checkout please follow the instructions you can find [here](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @dewinbrush,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @dewinbrush,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
