### ISSUE TITLE
mal funzionamento plug in viva wallet

### ISSUE THREAD

**Issue by growshopitalia** [VivaPayments/API#2314]
salve con gli svluppatori abbiamo provveduto ad installare la plug in da voi fornita per  il cms magento 2.4.5 per l'abilitazione ai pagamenti con carta sul nsotro e comemrce www.growshopitalia.com
purtroppo come descritto nel file di testo allegato ci da errore
il tipo di errore è ben descritto nel file txt

[viva_wallet_error.txt](https://github.com/VivaPayments/API/files/10446600/viva_wallet_error.txt)
vi sottolineo il dubbio dei nostri sviluppatori che la nostra versione è la 2.4.5 ed il vostro modulo sembrerebbe compatibile fino alla 2.3
attendo cortese risocntro

**Comment by VivaWalletCustomerSupport** [comment]
Hello @growshopitalia,

Thank you very much for contacting us. Can you please share with us a screenshot of the module's configuration? Also can you please provide the Merchant ID of the Viva Wallet account that the website is integrated with?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by growshopitalia** [comment]
here is


![Configuration-Settings-Stores-Magento-Admin-Grow-Shop-Italia](https://user-images.githubusercontent.com/122986818/213406679-6710ad44-c8b5-4ade-ba50-199afb9592b0.jpg)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @growshopitalia,

Thank you for the additional information. Kindly note that Magento Smart Checkout module is functional on public domains. As we can observe your domain requires a password to access the domain. We would like to suggest you to remove the password from the domain and try again. Also ensure that the Success and Failure URLs of the source you created are the following:

Success & Failure URLs: vivapayments/viva/callback

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by growshopitalia** [comment]
the error persist

**Comment by VivaWalletCustomerSupport** [comment]
Hello,

Thank you for your answer. You can add your developer in the conversation by providing to him the github's ticket URL or by mention him on this conversation by pressing @ and then his github username.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @growshopitalia,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by growshopitalia** [comment]
our developer is creating a demo enviroment

**Comment by VivaWalletCustomerSupport** [comment]
Hello @growshopitalia,

Thank you for the feedback. If you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @growshopitalia,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if the issue is resolved.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @growshopitalia,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
