### ISSUE TITLE
Issue with MAX_SAFE_INTEGER for OrderCode in createPaymentOrder endpoint response

### ISSUE THREAD

**Issue by styltsou** [VivaPayments/API#2316]
I try to access the smart checkout API in Node.js. When an orderCode that is returned from createPaymentOrder is larger than javascripts MAX_SAFE_INTEGER, the oder code is 'rounded'. This happens even if I convert the order code to a string. The following results to an 'payment order code not found' error when trying to redirect to the payment gateway in my frontend app. Is there any way to reslove this iissue?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou,

Thank you very much for contacting us. We would like to suggest to use the bigint function and output the order code as a string. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by styltsou** [comment]
Hello,
I might have forgotten to mention that I already use the BigInt function. I
pass the oderCode from the response, inside tha function right away. Should
I provide a small code snippet at the current github issue?

Thank you, for your immediate response
Stylianos

Στις Παρ 20 Ιαν 2023 στις 11:23 π.μ., ο/η VivaWalletCustomerSupport <
***@***.***> έγραψε:

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou,

Thank you for the prompt response. Kindly note that this is out of our scope. We can support only integration issues and errors regarding the integration. 

This is a javascript functionality. In javascript any integer you output as a JavaScript number (not a BigInt) that's more than 15-16 digits (specifically, greater than Number.MAX_SAFE_INTEGER + 1 [9007199254740992]) may be rounded, because JavaScript's number type (IEEE-754 double-precision floating point) can't precisely hold all integers beyond that point.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou,

We just wanted to follow up on the reply we sent on Friday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by styltsou** [comment]
Thank you a lot for your help

Στις Τρί 24 Ιαν 2023 στις 2:09 μ.μ., ο/η VivaWalletCustomerSupport <
***@***.***> έγραψε:
