### ISSUE TITLE
Set color panel checkout for woocommerce

### ISSUE THREAD

**Issue by bandolerro** [VivaPayments/API#2325]
Hello I'm using vivawallet for woocommerce smart checkout v2, I've seen in the doc that we can add a color to the checkout panel as a url param, however I've seen no way to do it with the plugin in woocommerce. And I've not been able to bypass the sender url to add the param manualy.

Do you have a workaround so I can select a color for the woocommerce vivawallet smart checkout plugin? 

thank you very much

**Comment by VivaWalletCustomerSupport** [comment]
Hello @bandolerro,

Thank you very much for contacting us. Regarding your question. 

Currently [color selection](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/#optional-but-recommended-specify-brand-color) is only available on Custom Smart Checkout Integration. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @bandolerro,

We just wanted to follow up on the reply we sent on Friday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @bandolerro,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
