### ISSUE TITLE
order_state - meaning of I, P, F

### ISSUE THREAD

**Issue by nickpapoutsis** [VivaPayments/API#2331]
Hi,

Can you please confirm the meaning of I, P, F used for order_state in default plugins?

I'm guessing I means "pending", P means successfully paid and F means failed but couldn't find anything in the documentation (except for the StatusId which looks relevant but is completely different).

**Comment by VivaWalletCustomerSupport** [comment]
Hello @nickpapoutsis,

Thank you very much for contacting us. The order_state values in our plugins are the following:

I=Pending
P=Paid
F=Failed

Our documentation does not include information about the parameters of our plugins. They have developed to use it as it is.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @nickpapoutsis,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by nickpapoutsis** [comment]
HI,

Yes, you have answered my question.

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @nickpapoutsis,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
