### ISSUE TITLE
The Transaction Failed

### ISSUE THREAD

**Issue by jpincas** [VivaPayments/API#2342]
We are developing a Viva Wallet integration for our platform Pakk.  We are 90% finished and doing extensive testing at the moment.

Since about an hour ago, every test transaction we attempt just gives this message.

![Screenshot 2023-02-23 at 14 15 05](https://user-images.githubusercontent.com/17711012/220917030-17f894c4-ef4c-4d3a-b314-d4f25b3fd353.png)

**Comment by jpincas** [comment]
Just to add some detail.  When inspecting the Network tab, we can see that the call to https://demo.vivapayments.com/web2/checkout/v2/transactions is getting a 403 with this payload:

![Screenshot 2023-02-23 at 14 25 48](https://user-images.githubusercontent.com/17711012/220919705-ced3cf74-aa9a-48ab-a210-8d7064b84ca5.png)

What can we do about this? This is a dev account that we are using for testing and we need to test failures.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jpincas,

Thank you very much for contacting us. Can you please create an order code and send it to us? On the paymentTimeOut parameter please use 86400 (one day).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jpincas,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jpincas,
 
This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
