### ISSUE TITLE
Your payment could not be processed Error on Magento 2

### ISSUE THREAD

**Issue by jrwenigma** [VivaPayments/API#2368]
Hello,

We've correctly installed VivaPayments Module on Magento 2, on the demo the payments are processing but when we go live none of our customers payments are processing, we just get the error: Your payment could not be processed

Is there an outage again with Viva Wallet?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jrwenigma, 

Thank you for your message. We did not experience any outage. Can you please send us a screenshot of the plugin settings and your MID to further investigate the issue?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jrwenigma,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jrwenigma,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
