### ISSUE TITLE
Unknown error when cancelling a transaction through the EFT POS API

### ISSUE THREAD

**Issue by SamuelMichelRiad** [VivaPayments/API#2372]
Hello support,

We have implemented refunds through the EFT POS API but found that the refund is only successful when the amount exactly matches the sale transaction amount.

For example, we have made a successful sale transaction of 10.00 DKK. When the refund amount is 10.00 DKK, the refund is **successful**. When the refund amount is anything less than 10.00 DKK, the refund **fails**. The API still returns status code 200, but the VW POS app displays the message "Transaction Failed - Unknown error"

Can you please advise? 

![WhatsApp Image 2023-04-18 at 11 38 53](https://user-images.githubusercontent.com/9570587/232706756-170bb288-44b6-4e4c-bd08-a8f9e02a1f47.jpeg)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

Thank you for your message. Kindly note that partial refunds are available only in cleared transactions. If the transaction is not cleared, you can only refund the whole amount of the transaction.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

We just wanted to follow up on the reply we sent on Tuesday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
