### ISSUE TITLE
compatibility with latest magento 2 and php v8

### ISSUE THREAD

**Issue by agelospanagiotakis** [VivaPayments/API#2375]
i was wondering if and when the magento 2 plugin will be compatible with mangento 2.4.5 and php v8.1
https://developer.vivawallet.com/plugins/magento/

**Comment by VivaWalletCustomerSupport** [comment]
Hello @agelospanagiotakis,

Thank you for your message. We would like to inform you that we are developing a new Magento plugin which will be compatible with Magento version 2.4.5. About the PHP versions that will be supported, they will be announced with the release of the plugin.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @agelospanagiotakis,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by agelospanagiotakis** [comment]
thank you
I am looking forward for this update.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @agelospanagiotakis,

This ticket will close for now. You can check our [Release Notes page](https://developer.vivawallet.com/releasenotes/) for information about the additions and updates to Viva Wallet's products and services. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
