### ISSUE TITLE
Transaction settlements on sandbox (clearanceDate)

### ISSUE THREAD

**Issue by viderspan** [VivaPayments/API#2377]
Dear Support,

Is it possible to set the sandbox transactions to settled status?
I would like to query the transactions that were settled on a given day.

There is an API endpoint for this in the technical documentation:

Retrieve transactions (OLD)

clearance date, e.g. GET /api/transactions/?clearancedate=2018-08-27

I see that the value of the clearance date and fee is always empty for the sandbox transaction.

How can I test the settlement process in order to develop a financial solution for it?

Thanks.

Best regards,
Krisztián

**Comment by VivaWalletCustomerSupport** [comment]
Hello @viderspan,

Thank you for your message. Kindly note that it is not possible for the transactions to be settled in the demo environment. Unfortunately, this API request functionalities can be tested only in a live environment. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @viderspan,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @viderspan,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
