### ISSUE TITLE
Cannot test VivaWallet in sandbox with headless browsers

### ISSUE THREAD

**Issue by t0mm4rx** [VivaPayments/API#2378]
Hello,

I'm developing E2E tests for a web application using VivaWallet as a payment processor.
I'm using Linux, Cypress, and headless versions of Chrome and Electron.

When the tested website does the redirection to `https://demo.vivapayment.com/...`, the request is never ended, blocking the execution of the test.

The test is working well on non-headless automated browsers.

Is there any kind of protection that I need to bypass in order to automate the tests?

**Comment by t0mm4rx** [comment]
It seems that the issue is coming from IP filtering. I've tried with different proxies but they get blocked.

Any way to bypass restrictions while testing on the sandbox environment?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @t0mm4rx,

Thank you for your message. Can you please provide us with the IPs you used for the requests? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @t0mm4rx,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @t0mm4rx,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
