### ISSUE TITLE
Login to Demo Account returns a Error 500!

### ISSUE THREAD

**Issue by harrys-nikoloudakis** [VivaPayments/API#2384]
I have a demo account for testing online payments in viva wallet.
For several months now when i try to connect to my account i get a page with an error 500.
how can this problem be solved??

**Comment by VivaWalletCustomerSupport** [comment]
Hello @harrys-nikoloudakis,

Thank you for your message. Can you please share with us a screenshot of the error? Also, please send us the mobile number or the e-mail address that the demo account is registered to.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by harrys-nikoloudakis** [comment]
I was able to connect using another browser.
I have 2 accounts. 1 for merchant and 1 for payment test.
I can view the second account but when I try to switch to the first account I get this error again.
![image](https://github.com/VivaPayments/API/assets/133211876/2d16c2d6-a868-42db-88e3-8c114acd8298)
![image](https://github.com/VivaPayments/API/assets/133211876/90618350-7eb4-4d35-bf82-82013d05e917)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @harrys-nikoloudakis,

Thank you for your message. Can you please clarify from which account the above error appears?
Kindly note that the features of the business account (blue background color) won't be affected if you cannot access the personal account (orange background color).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @harrys-nikoloudakis,

We just wanted to follow up on the reply we sent yesterdat. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by harrys-nikoloudakis** [comment]
It is from the account with the initials "ΧΝ" (personal).

**Comment by VivaWalletCustomerSupport** [comment]
Hello @harrys-nikoloudakis,

Thank you for your message. Can you please create a new personal demo account and try again? You can use a "dummy" phone number. Let us know if issuer persists.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @harrys-nikoloudakis,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @harrys-nikoloudakis,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
