### ISSUE TITLE
Smart checkout error: OrdersOrderCodeNotFound: Order with code ### was not found

### ISSUE THREAD

**Issue by grigmag** [VivaPayments/API#2388]
Hello, I am using a demo account to create Smart Checkout orders. 

In some cases, after successfully creating an order code and visiting `https://demo.vivapayments.com/web/checkout?ref=###` url, I get this error page:

![image](https://github.com/VivaPayments/API/assets/45455235/b8f2157e-f9c3-406f-9d14-938264594c96)

This is an example of a url that produces an error `https://demo.vivapayments.com/web/checkout?ref=9077444259872608`

In contrast this is an example of a successful link (might be expired when clicked)
`https://demo.vivapayments.com/web/checkout?ref=4350802566672601`

I suspect the reason is that the order code is a number and the first number (9077444259872608) is above the MAX_SAFE_INTEGER in JavaScript, which is 9007199254740991 (this might be the case for other languages as well, e.g. the language used by Viva in the backend). 

If that is the case, I believe this is an important bug because some orders will fail for no reason.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @grigmag,

Thank you very much for contacting us. 
As you already mentioned, when an ordercode is bigger than MAX_SAFE_INTEGER (9007199254740991) in javascript the order code that will be generated will be 'rounded'. 

In javascript any integer you output as a JavaScript number (not a BigInt) that's more than 15-16 digits (specifically, greater than Number.MAX_SAFE_INTEGER + 1 [9007199254740992]) may be rounded, because JavaScript's number type (IEEE-754 double-precision floating point) can't precisely hold all integers beyond that point.
We would like to suggest using the bigint function and output the order code as a string.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by grigmag** [comment]
Hello and thank you for your quick response.

You are correct, the mistake was in my handling of the response in the backend, which uses Node.js and axios. Specifically, axios automatically parses the json response and converts the orderCode to a number, which is problematic for numbers larger than MAX_SAFE_INTEGER.

For future reference for anyone that faces this problem, here is a quick and dirty fix that I used:
```typescript
const response = await axios.post<string>(url, data, {
  headers: {
    'Content-Type': 'application/json',
    Authorization: `Bearer ${accessToken}`,
  },

  transformResponse: (data) => {
    const matched = data.match(/"orderCode":\s*(\d+)/);
    const orderCode = matched[1];

    if (!orderCode) {
      throw new Error('Could not parse order code');
    }

    return orderCode;
  },
});
```

Other and more general ways to handle this can be found in https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigin

______________________________

Even though the wrong handling was on my part, do you think that the design of the `/checkout/v2/orders` API route in viva could be improved?

Specifically, would it not be a better practice to return the orderCode as a string in order to eliminate the possibility of such parsing mistakes, which can also be made automatically by the http request library used (e.g. axios)? Of course, I understand that such a change might be difficult to make now.

Alternatively, wouldn't it be a good idea to emphasize the need for custom parsing (at least in some languages like JavaScript) in the documentation, e.g. in https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post and/or https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/ ? 

This would help developers integrating with viva avoid this mistake in the future.

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @grigmag,

Thank you for your suggestion. We always consider our customers' feedback for future improvements. We will review your request and possibly, it will be available in a future release.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @grigmag,
 
We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @grigmag,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
