### ISSUE TITLE
Smart Checkout Plugin for PrestaShop

### ISSUE THREAD

**Issue by matheusdantasc** [VivaPayments/API#2390]
### Smart Checkout Plugin for PrestaShop

Hello. I'm trying to test the smartcheckout plugin for PrestaShop on a demo local environment (prestashop.local), but it's giving me this error: 

![image](https://github.com/VivaPayments/API/assets/66729835/c598e7b8-c0cd-4001-9550-62275c045ebb)

Is there any way I could test the plugin functionality while still running my PrestaShop website on localhost?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @matheusdantasc,

Thank you for your message. Kindly note that our module automatically generates webhooks when integrated. In order for the webhooks to be created and for the module to be functional, the website must be public.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by matheusdantasc** [comment]
Thank you for the response!

**Comment by matheusdantasc** [comment]
Greetings! My website is now public, but it's giving me the following error when I try to integrate the plugin:

![image](https://github.com/VivaPayments/API/assets/66729835/2cd3832c-55e6-4b46-98eb-10bde61f9e47)

"The source code is not valid for this domain."
What does this mean and how can I fix this? 

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @matheusdantasc,

Thank you for your message. Please check that your hosting provider supports the following:
PHP version 7.1 or later
PHP extensions: cURL, JSON
TLS 1.2 
Also, if you are using a CDN also see if it supports TLS 1.2

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @matheusdantasc,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by matheusdantasc** [comment]
Hello @VivaWalletCustomerSupport,

Sorry for the delay. I just checked, and all the requirements are being followed. What else could trigger this error?

Thank you,
Matheus

**Comment by VivaWalletCustomerSupport** [comment]
Hello @matheusdantasc,

Please make sure your server supports TLS 1.2. If you are using a CDN also see if it supports TLS 1.2.
Kindly note that this must the exact version. If, for instance, your server supports 1.3 there may be a conflict.

A restriction rule on your server or the use of VPN/PROXY may also trigger this error.
We would like to recommend whitelisting the following [IP addresses](https://developer.vivawallet.com/webhooks-for-payments/#whitelist-the-viva-wallet-addresses).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @matheusdantasc,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @matheusdantasc,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
