### ISSUE TITLE
Webview Integration Viva

### ISSUE THREAD

**Issue by yu5056561661** [VivaPayments/API#2393]
Webview integrates with Viva and will redirect to an address after successful or failed payment. How can this address be set? I used a hybrid development tool called UniApp and accessed it through webview on the page,
![image](https://github.com/VivaPayments/API/assets/75231131/12a4f801-dd96-4176-9f4d-aac78b6c53d8)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

Thank you for your message. 
For additional information regarding integrations with a mobile application, please check the link below:
https://developer.vivawallet.com/tutorials/smart-checkout-configuration/integrate-with-a-mobile-app/

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by yu5056561661** [comment]
Hello, I went to review the document yesterday and am currently integrating. I have a question that I would like to ask. When I see a video payment, I can call up the "Viva app" to make the payment. I integrate it by nesting webviews in the app, so how can I call up the "Viva app" to make the payment? Directly through“ https://demo.vivapayments.com/web2?ordercode ”After accessing, will the "vivo app" on the phone be automatically opened to make the payment, and then change the URL address of the current web view? Because I am in China, I cannot download the 'vivo demo app' for testing

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

Thank you for the response.  I would like to inform you that the integration with a mobile application refers to the integration of our [Smart Checkout payment gateway](https://developer.vivawallet.com/smart-checkout/) which is implemented inside your application. Can you please clarify which integration you wish to complete? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by yu5056561661** [comment]
> 

Smart Checkout

**Comment by yu5056561661** [comment]
I am currently using Smart Checkout, first verifying oauth2.0, then creating an order ->paying an order ->verifying payment results

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

Thank you for the clarification. Kindly note that since you are using Smart Checkout there is no need to download the demo app, our payment gateway is implemented inside your application.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
