### ISSUE TITLE
Issue : Native checkout V2

### ISSUE THREAD

**Issue by AmityTek** [VivaPayments/API#2395]
Hello,

I can't access to  : https://developer.vivawallet.com/native-checkout-v2/
Also i can't find public_key
so I can use correctly the checkout.js integration for my website.

Someone can help ?

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AmityTek,

Thank you for your message. Kindly note that the native-checkout-v2/ is deprecated and no longer supported.
We would recommend recommend integrating our [Smart Checkout Integration](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/). 

To locate the required [credentials](https://developer.vivawallet.com/getting-started/find-your-account-credentials/#common-credentials), navigate to your Viva Wallet account under Settings > API Access.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AmityTek** [comment]
I really need to integrate native checkout in my website
How to do ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AmityTek,

Thank you for your prompt response. We would like to inform you that we no longer offer a custom native checkout solution on our payment gateway.  

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AmityTek,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AmityTek** [comment]
Hello,
its ok thank you
