### ISSUE TITLE
Integrating Tap to Pay in React Native app

### ISSUE THREAD

**Issue by diklou** [VivaPayments/API#2398]
I would like to integrate Tap To Pay into my own React Native app.
![image](https://github.com/VivaPayments/API/assets/77521038/2bc7980d-95dc-4750-be8b-8ead51c8c5e8)

 Is this possible with viva wallet ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

Thank you for your message. You can perform app to app requests by following the instructions of the links below:

[Android app integration](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminal-apps/android-app/)
[iOS app integration](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminal-apps/ios-app/)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by diklou** [comment]
Are you saying that you don't support React Native ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

Thank you for your message. 
These are the general instructions. It is up to you to select the language of your choice.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by diklou** [comment]
But you don't have a React Native SDK ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

Can you please clarify how you will use our SDK? In order to integrate your application with our application please use the instructions of the link below:

[Androip App integration Sale Request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminal-apps/android-app/sale/)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by diklou** [comment]
Why are you deliberately avoiding answering my question ? Do you even know what React Native is ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,


All available SDKs can be found in the link below:
https://developer.vivawallet.com/apis-for-point-of-sale/sdks/

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
