### ISSUE TITLE
Where do I get the bearer token for marketplace API ?

### ISSUE THREAD

**Issue by Villex-code** [VivaPayments/API#2403]
I am creating a marketplace and need the authorize the API calls that I make. So far I haven't been able to create a connected account and retrieve a redirectURL that I will be sending to my sellers. Can someone please walk me through the process , I would greatly appreciate it !

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Villex-code,

Thank you for your message. In order to use our Marketplace API, please complete and submit an [online contact form ](https://www.vivawallet.com/contact) with a summary of your requirements. The Viva Wallet sales team will review your request and get back to you as soon as possible.

After that you should [setup your accounts](https://developer.vivawallet.com/marketplaces/#set-up-your-accounts). 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Villex-code,

We just wanted to follow up on the reply we sent on Monday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Villex-code** [comment]
Hello , with all due respect I have submitted this contact form at least 3
times so far , and still I haven't received any useful information about
the matter.

I am getting Forbiden Responses from the API that I am supposed to create
the connected account.

I still haven't fully understood if you need to set my account as
marketplace which will give me permission to perform these operations or
there is another way. I have read all the documentation around the
marketplace API and I am still getting 403 Response.

Is it not just possible to talk with a representative that knows about the
tech of it ?

Thank you
ᐧ

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Villex-code,

We apologize for the delay. Kindly note that Marketplace APIs are eligible only for merchants that have been approved to own a Marketplace account. If you do not own a Marketplace account, those APIs are not eligible.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Villex-code,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Villex-code** [comment]
Yes, I have received it.

I was wondering how I can I get such an account with those capabilities. I
am opening a business and I would need to receive payments for my sellers.
The matter is urgent so I would appreciate it a lot if you could answer to
this issue as soon as possible.

Thank you very much !
ᐧ

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Villex-code,

Thank you for your message. Kindly note that Marketplace APIs are eligible only for merchants that have been approved to own a Marketplace account. Since you already applied via the [online contact form ](https://www.vivawallet.com/contact) and not received any feedback by the the Viva Wallet sales team, we can only assume that your account was not deemed as eligible. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Villex-code,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Villex-code** [comment]
Yes, I did, thank you.

What are the requirements to deem my account eligible? I haven't found a
guide or anything specific and I keep having to go back and forth with
employees and live chat only to get the same answer.

You are a big and trusted company and you do great business. Can I get a
professional answer on this matter with specifics and details. I would
greatly appreciate it.

Thank you for your time
ᐧ

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Villex-code,

Thank you for the swift response. To proceed with the Platform account creation, please proceed with the verification of your business account. After your account is fully verified, we will proceed with our procedures.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Villex-code,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Villex-code** [comment]
I did, thank you!

So I guess I will be making a legal entity and verifying my account soon if
that is the only way to achieve the marketplace functionality.
ᐧ

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Villex-code,

Thank you for the update. This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
