### ISSUE TITLE
issue saving smart checkout vivawallet woocommerce plugin webhook ->error 502 in live mode

### ISSUE THREAD

**Issue by thierrygeufroi** [VivaPayments/API#2431]
hello,  although payments seem to work in live mode (gave few tries), I red that the webhook for transaction payment created had to be created for SMART CHECKOUT under wordpress. Whenever i try to save the webhook I receive the error code 502 message. Can somebody help me figuring out what is going on ? Thank you very much

**Comment by VivaWalletCustomerSupport** [comment]
Hello @thierrygeufroi,

Thank you for your message. We would like to advise you to contact your hosting provider and check if there is any restriction rule for server-to-server requests. Also, please ensure that your server supports only TLS version 1.2. Finally, please whitelist the IPs of the following link:

https://developer.vivawallet.com/webhooks-for-payments/#whitelist-the-viva-wallet-addresses

The above steps should be followed for your CDN as well if you are using any.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @thierrygeufroi,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @thierrygeufroi,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
