### ISSUE TITLE
Payment Order code uniqueness

### ISSUE THREAD

**Issue by styltsou** [VivaPayments/API#2438]
I am using the smart checkout for an e-commerce website and I was wondering if the Payment Order Code return from the API is  always unique.  Should I use this code to identify a unique entry (order) in my database? How many are the chances for an order code to be generated again in the long term?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou,

Thank you for your message. Kindly note that our order codes are a combination of a unique 16-digit number. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
