### ISSUE TITLE
delivery fee on the Pay on Delivery

### ISSUE THREAD

**Issue by auraki** [VivaPayments/API#2439]
hello, I added the plugin "Viva Smart Wallet" on the wordpress website (woocommerce).
I want to add on the check out, only on the section "Pay on Delivery"  of the Viva smart Wallet, additional delivery fee 2.5

I saw [this website](https://developer.vivawallet.com/apis-for-payments/payment-api/?fbclid=IwAR34uKgkHfe3fQYGsD12jiaNci1AbeiXCc0vTt9GO3StrWCS2x_wi0dqlMQ#section/Get-Support) but still I'm not sure how I can do, and where I should add the "paymentMethodFees": [{"paymentMethodId":"35", "fee": 250}]

**Comment by VivaWalletCustomerSupport** [comment]
Hello @auraki,

Thank you for your message. Kindly note that this fee can only be entered for payment orders created through an [API request](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post). Our plugins do not support this feature yet. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @auraki,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by auraki** [comment]
Hello,

thank you for your email and the quick response!!!

I appreciated it

**Comment by VivaWalletCustomerSupport** [comment]
You are very welcome @auraki!

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
