### ISSUE TITLE
Android app integration

### ISSUE THREAD

**Issue by AntonKankkunen** [VivaPayments/API#2445]
Hello!
We are creating a payment software that runs on the Viva Android terminal (cs50). Currently it uses intents to open and request a payment on the viva | terminal -app.
On that part everything is alright, but we started to wonder if we could design the app so that it wouldn’t need to open the viva | terminal app.
Could viva be used just as a payment gateway?
We would like to have 100% custom flow and design in our app, where we could show our own ”Insert / tap card” and”payment success/fail” -screens. Also to be able to modify the time how long a payment could be requested (viva| terminal app closed automatically in 1 minute).
Any answer and help where to start is appreciated

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AntonKankkunen,

Thank you for your message. Kindly note that the Viva terminal app must be opened to procced with a payment and cannot be bypassed. Also, the time period mentioned cannot be modified. 

We always consider our customers' feedback for future improvements. We will review your suggestions and possibly, it will be available in a future release.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AntonKankkunen,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AntonKankkunen,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
