### ISSUE TITLE
User deprecated functionality session id is not used as url parameter anymore Magento2.4 

### ISSUE THREAD

**Issue by Accesskaneh** [VivaPayments/API#2458]
Hi we have our site running Magento 2.4.4 and trying to install the VivaWallet module.
We have session ID in store configuration set to no  but still get the error "User deprecated functionality session id is not used as url parameter anymore"
Can you please advise on a solution 

![accesskaneh fault](https://github.com/VivaPayments/API/assets/147182915/165b21fb-6efd-428d-95ef-51d8479259bc)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Accesskaneh,

Thank you for your message. Can you please send us the domain of your website so we can investigate your issue? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Accesskaneh,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Accesskaneh,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Accesskaneh** [comment]
Hi thanks we manged to fix it form posts on support forums.

 

Thanks you
