### ISSUE TITLE
Recurring Payment 502

### ISSUE THREAD

**Issue by mitsisv** [VivaPayments/API#2464]
We have problem with Recurring Payment, we get error 502 from viva dashboard also 404 in post to endpoint https://www.vivapayments.com/api/transactions/{transactionId}

Is there a way to get more info about the problem? There was no problem till August.

![Untitled](https://github.com/VivaPayments/API/assets/11487494/bc2c7249-51a6-4823-9a9f-b216839b2732)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mitsisv,

Thank you for your message. Can you please share the transaction ID to further investigate?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by mitsisv** [comment]
Hello you can use this transactionId 375e1216-b293-4561-882d-114a26557ce8
Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mitsisv,

Thank you for your prompt response. In order to provide additional information regarding transactions, you will need to log in to your Viva Wallet account and contact us via Chat or email at support@vivawallet.com from your registered email address.
Please add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mitsisv, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mitsisv,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
