### ISSUE TITLE
Compatibility with new Opencart 3.0.3.9 and PHP 8.1?

### ISSUE THREAD

**Issue by sbzsystems** [VivaPayments/API#2467]
Hello,

Regarding the brand new 3.0.3.9 Opencart version which supports PHP 8.0, 8.1 and 8.2, I was wondering if the plugin supports the newer PHP versions and the new Opencart version.

Is there a changelog of the plugin updates, where the supported PHP versions are visible?

Kind regards

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sbzsystems, 

Thank you for your message.
The newer version is not supported yet but it is under development. We cannot provide a specific timeline; we would recommend checking our Release Notes Page for information about the additions and updates to Viva Wallet's products and services. 
https://developer.vivawallet.com/releasenotes/

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sbzsystems,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sbzsystems,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
