### ISSUE TITLE
Update Shopify checkout plugin text 

### ISSUE THREAD

**Issue by jordanvidal1** [VivaPayments/API#2476]
The Viva wallet payment method title on the Shopify checkout page is '30+ payment methods by Viva Wallet'. How can I change this to just 'Credit or Debit Card'?

I don't have 30+ payment methods selected, only 4, so this is misleading. It should just be the title of the payment method and not a description.

![viva-shopify](https://github.com/VivaPayments/API/assets/44398779/78a3dada-6fc7-4b4c-8d39-40bad3f24cf9)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jordanvidal1,

Thank you for your message. Kindly note that the way Shopify is implemented does not allow us to proceed with the modifications requested from the above screenshot.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jordanvidal1,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jordanvidal1,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
