### ISSUE TITLE
Powered by

### ISSUE THREAD

**Issue by onuproy** [VivaPayments/API#2483]
How to change Powered by 

https://prnt.sc/js5_W1TCvWU-

Thanks!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @onuproy, 

Thank you for your message. Please note that the requested field cannot be modified.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @onuproy, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by onuproy** [comment]
ok thank you!
