### ISSUE TITLE
"ISV multimerchant transactions are not currently supported with TapToPay"

### ISSUE THREAD

**Issue by wbison** [VivaPayments/API#2485]
We want to handle TapToPay payments in our restaurant POS iOS app

Referring to:
https://developer.vivawallet.com/apis-for-point-of-sale/card-terminal-apps/ios-app/sale/

This request:
vivapayclient://pay/v1?callback=nappkin&appId=nl.nappkin&action=sale&amount=650&clientTransactionId=XXX&ISV_merchantId=YYY&ISV_amount=0&ISV_clientId=ZZZZ&ISV_clientSecret=SSSS

results in this response:
"Wrong request parameters: ISV multimerchant transactions are not currently supported with TapToPay"

What are we doing wrong?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison, 

Thank you for your message. Nothing wrong from your side. As the error message states, ISV multimerchant transactions are not currently supported with TapToPay.
We would recommend checking our [release notes page ](https://developer.vivawallet.com/releasenotes/)for additions and updates to our products and services.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
