### ISSUE TITLE
Viva Wallet Standar checkout Woocommerce - Compatibillity Issue with woocommerce 8.5.2

### ISSUE THREAD

**Issue by kapamarou** [VivaPayments/API#2492]
ΗΙ there is a compatitibility issue with the new version of the woocommerce and the plugins is not working

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kapamarou,

Thank you for your message. Kindly note that an updated version of the plugin is expected to be released soon. We don't have an ETA yet, but we would recommend checking our [release notes page](https://developer.vivawallet.com/releasenotes/).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kapamarou, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by kapamarou** [comment]
Ηello thank you for your reply and i am sorry for late response . I hope that you fix it soon because many of clients cant update or use it to the new version

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kapamarou ,

Thank you for your message. We always consider our customers' feedback for future improvements. We will review your request and possibly, it will be supported in a future release.

Kind regards,
Viva Wallet E-commerce Support Team
