### ISSUE TITLE
e-banking/DIAS DEMO environment

### ISSUE THREAD

**Issue by epiksGr** [VivaPayments/API#2493]
Hello,
The documentation states that in the DEMO environment, the e-banking/DIAS is not available. However, if you go to the demo page https://demo.vivapayments.com/web2?ref=5617245978572605&color=3171b8, you can see the e-banking/DIAS option. I even made a test transaction, and my bank gave me a successful response, and the amount was removed from my balance. Where did this money go?
Thank you!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @epiksGr, 

Thank you for your message. As you already mentioned, this[ payment method](https://developer.vivawallet.com/payment-methods/direct-debit-other/ebanking/#how-to-activate-e-banking-διασ-dias) is unavailable on demo environment. 
Can you please provide more details about the test transaction you made?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @epiksGr,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @epiksGr,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
