### ISSUE TITLE
order accepted without payment

### ISSUE THREAD

**Issue by vicapos** [VivaPayments/API#2499]
Hi!
 i installed the latest vivawallet smart checkout  for prestashop. 1.7.8.11 version 
 I completed all the steps for installation and account creation.
 
But  i am facing a problem at checkout
 when a customer choose the vivawallet payment   and press the button to place the order
both customer and eshop  receives the email with his order (succesfully placed)
 before customer make the payment
 
 i saw the new feature      Viva On Hold Orders 
 is there any further settings i should do?
 
 thanx in advance
john

**Comment by nickolis** [comment]
Hello @vicapos 

Thank you for reaching out.

Regarding the issue you're experiencing with the VivaWallet Smart Checkout for Prestashop, it's important to note that the behavior you described is actually a feature of Prestashop itself, rather than the plugin. Prestashop sends order confirmation emails immediately after the customer places an order, regardless of whether the payment has been completed or not.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vicapos
 
Thank you for reaching out.
 
Regarding the issue you're experiencing with the VivaWallet Smart Checkout for Prestashop, it's important to note that the behavior you described is actually a feature of Prestashop itself, rather than the plugin. Prestashop sends order confirmation emails immediately after the customer places an order, regardless of whether the payment has been completed or not.
 
Kind regards,
Viva Wallet E-commerce Support Team

**Comment by vicapos** [comment]
well, that didn't occured in thw previous version of viva module
customer had to make the payment and after that , we received the confirmation email.

thanx for your answer.
Kind regards
john

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vicapos ,

Thanks for understanding. This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
