### ISSUE TITLE
AISP PSD2 Interface plans

### ISSUE THREAD

**Issue by frcake** [VivaPayments/API#2500]
Hello,

It's been some time since the last question about this issue.. do you have any plans/developments on when you are going to release an AISP interface?

✌️

**Comment by VivaWalletCustomerSupport** [comment]
Hello @frcake,

Thank you for your message. You can check the [Release Notes page](https://developer.vivawallet.com/releasenotes/) and the [PSD2 Compliance page](https://developer.vivawallet.com/about-viva/psd2-compliance/) for any updates about additions and updates to our products and services

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @frcake,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @frcake,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
