### ISSUE TITLE
Update Card for Recurring Payments

### ISSUE THREAD

**Issue by orcascript** [VivaPayments/API#2508]
Good evening,
In the process of implementing recurring payments, we would like to integrate the functionality of user being able to update the card which will be charged upon next time through our service. 
1. How do we link the the recurring payment with the new card? Is there any information we can send and retrieve to bind the card change to the recurring payment process?
2. Is there a webhook which fires after the user update his card?

Thank you in advance

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gosusoen 

Thank you for your message. Kindly note that this functionality is not supported. For the customer to change the card, you should repeat the entire process as it is a new subscription.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gosusoen,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gosusoen, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
