### ISSUE TITLE
No confirmation webhooks are sent to our API

### ISSUE THREAD

**Issue by 0xdhu** [VivaPayments/API#2512]
Hello,

I'm new on VivaWallet.
I try to integrate Smart Checkout into my apps. So far so good but I'm not receiving any webhooks. My configuration is okay and verified by VivaWallet. When I try to pay, the end-user is redirected to my success URL correctly but no webhook is sent to me.

Here are the information: ?t=f4f81fc6-edae-4f5d-895b-b62336ed3648&s=1033185497655239&lang=en-GB&eventId=0&eci=1

I am testing webhook in my local scripts and local scripts is working with ngrok service. 

Can you help me?

Thank you,

**Comment by VivaWalletCustomerSupport** [comment]
Hello @0xdhu ,

Thank you for your message. Please white list [those](https://developer.viva.com/webhooks-for-payments/#whitelist-the-viva-addresses) IPs and make sure that the URL is public. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @0xdhu,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @0xdhu,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
