### ISSUE TITLE
No payment methods available

### ISSUE THREAD

**Issue by apolyshow** [VivaPayments/API#2514]
Hey,

I have install and also enable Viva Wallet Standard Checkout and connect correctly with correct credentials into our website www.iliofos.gr . i can see it in my account. 
But, There are no payment methods available. This may be an error on our side. Please contact us if you need any help placing your 

How can solve this?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @apolyshow 

Thank you for your message. 
Upon investigating the reported issue, we have identified a conflict between the 'Standard Checkout' plugin and the 'WooCommerce Blocks' during the checkout process. 
When customers utilize the WooCommerce Blocks , it appears that our payment method may not be visible.

To address this, we recommend switching to an alternative checkout method:
Log in to your WordPress admin dashboard.
Navigate to Pages -> Checkout.
Change the checkout page to the classic checkout.

By making this adjustment, you should observe the successful display of our payment method.
Our development team is actively working to address the conflict and provide a permanent fix in the upcoming plugin updates.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @apolyshow 

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @apolyshow,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team

**Comment by apolyshow** [comment]
I couldn't make it work , the woocomerce isn't allowing the page to transformed at classic code unless i made it from the beginning and then i am getting an ugly interface....

**Comment by apolyshow** [comment]
i will continue only with the bank transfer option until you fix the problem

**Comment by nikolaos221** [comment]
Had the exact same issue. Still no update. The problem is that the plugin does not play nice with the new checkout experience which is based on woocommerce blocks. 
As a temporary solution go into your checkout page (switch to text editor), remove everything and place the [woocommerce_checkout] shortcode. Just to go back the classic experience. 
that solved the problem for me. Just need to work on the css to make it look better. 
at least you'll have the viva option available until they release an update. 
hope it helps

**Comment by VivaWalletCustomerSupport** [comment]
Hello @apolyshow

Thank you for your message. Upon investigating the reported issue, we have identified a conflict between the 'Standard Checkout' plugin and 'WooCommerce Blocks' during the checkout process. Our team is working on a new plugin for WooCommerce that will resolve this issue, but we don't have an ETA yet. Kindly note that the only solution for now is to use the classic checkout page.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @apolyshow ,

Our new WooCommerce plugin is now available!  

Download it [here.](https://wordpress.org/plugins/viva-com-smart-for-woocommerce/)

Please note that the new plugin requires your WooCommerce credentials for seamless integration.

Kind regards,
Viva E-commerce Support Team
