### ISSUE TITLE
Woocommerce thank you page is showing not found

### ISSUE THREAD

**Issue by sudhanshu-dubey** [VivaPayments/API#2528]
https://pharmasonline.com/thank-you-page/?t=6102cc4a-2cab-4f68-bc68-f9ec33ea99ad&s=4918898641943018&lang=en-GB&eventId=0&eci=1

I have this URL returning from viva wallet but it should not find because in URL there is additional parameter "s" which is causing the issue because s keyword is globally reserved by wordpress itself. For testing I replaced "s" with "p" then it worked properly. 

How to fix it?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sudhanshu-dubey,

Thank you for your message. In the link below you will find our guide about sources: https://developer.viva.com/getting-started/create-a-payment-source/payment-source-for-online-payments/

Regarding the [parameters](https://developer.viva.com/integration-reference/response-codes/#response-query-string-parameters), it is recommended to leave these parameters with their default names, unless you specifically require different parameter names to align with your internal systems or processes

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sudhanshu-dubey,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sudhanshu-dubey,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
