### ISSUE TITLE
Nem sempre funciona a comuninção de sucesso da transação

### ISSUE THREAD

**Issue by mariannacbm34** [VivaPayments/API#2531]
Já me aconteceu várias vezes as minhas encomendaas darem como não pagas, mas na verdade a transação foi bem sucedida e não muda o estado no woocomerce.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mariannacbm34,

Thank you for your message. 
Can you please provide more details about the transaction? We will also need the MID of your account. You can share it here via email at support@viva.com or via the Live Chat option (which can be found at the bottom-right of the Developer Portal and main Viva.com site, or in your Production Viva.com self-care account)

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mariannacbm34,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by mariannacbm34** [comment]
I will send the email

**Comment by VivaWalletCustomerSupport** [comment]
Thank you @mariannacbm34, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
