### ISSUE TITLE
POST to /connect/token throw 403

### ISSUE THREAD

**Issue by petyosv** [VivaPayments/API#2532]
Hi,

**Summary:**
We are integrating Smart Checkout to a website of a client.
We have done that many times, and we are having the following issue for first time.
The following tests are done against the Viva Wallet DEMO environment.

**Issue:**
When trying to retrieve an access token using CLIENT_ID and CLIENT_SECRET from our local environments everything is working fine and we can continue with creating an order.
When the website is deployed on the server that is prepped for production, we are receiving  **403**.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @petyosv, 

Thank you for your message. Is the issue ongoing? If so, please try again and share the Logs generated from your server. We will need a reference code to further investigate.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @petyosv, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @petyosv,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
