### ISSUE TITLE
Viva smart checkout slow with errors

### ISSUE THREAD

**Issue by MarkA-maker** [VivaPayments/API#2535]
Viva Wallet Smart checkout runs slow: with these messages
![viva2](https://github.com/user-attachments/assets/52114322-c598-4d99-9c11-14ebc7e5d251)
![viva2](https://github.com/user-attachments/assets/98ccd09c-dc29-4a77-9fd5-95d424dfb0ce)

**Comment by MarkA-maker** [comment]
![viva 1](https://github.com/user-attachments/assets/c6d2ceac-9ba2-4e48-8f94-d04ac7950513)

Customers at this point do not complete purchase

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MarkA-maker,

Thank you for your message. We did not have any downtime or network error. Is the issue ongoing? We would recommend checking your server for timeout errors.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MarkA-maker,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MarkA-maker,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
