### ISSUE TITLE
Question regarding MessageId and CorellationId in webhook payload

### ISSUE THREAD

**Issue by styltsou** [VivaPayments/API#2543]
Hello, I  have an endpoint in my web app that listens for Transaction Created Webhooks.  In case of a webhook retry, does the MessageId or CorellationId stay the same? Could one of the fields be used as an idempotency key?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou,

Thank you for your message and we apologize for the delayed response.
We will investigate your query further and let you know. 

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou,

Thank you for waiting. Kindly note that the CorellationId will remain the same for retries. Therefore it can be used to identify notifications as new ones or retries of a specific transaction.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @styltsou, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
