### ISSUE TITLE
Order Notification is not send to customer

### ISSUE THREAD

**Issue by hr03webindiainc** [VivaPayments/API#2545]
Hello,

My website have test mode enable and when I purchase showing a critical error on checkout.

can you please review the below loom video for idea?

Website: [https://dev.soe-jensen.com/](https://dev.soe-jensen.com/)

Loom: [https://www.loom.com/share/e240de67cc9a422db9370650552f6234](https://www.loom.com/share/e240de67cc9a422db9370650552f6234)

can you please help me to solve out as soon as possible?

Additionally this error trigger
![error-viva](https://github.com/user-attachments/assets/16215c49-1bdb-4681-aa7b-c79669e56eb9)

Thank you in Advance

**Comment by VivaWalletCustomerSupport** [comment]
Hello @hr03webindiainc, 

Thank you for your message. Kindly note that a demo viva account is required to use the test mode. Follow the guide below to create one and add the demo credentials to the plugin settings.
https://developer.viva.com/getting-started/account-registration-sign-in/ 

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @hr03webindiainc, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @hr03webindiainc, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team

**Comment by hr03webindiainc** [comment]
thank you for the reply Team
