### ISSUE TITLE
Change default source problem

### ISSUE THREAD

**Issue by jimanis** [VivaPayments/API#33]
I canged the source of payment from default to a payment source with code 2356. I change it to my code in my php checkout page it redirects me right but when I finish the transaction seems to go to the not ok page of default source of payment. The website is thefashionproject.gr can any technitian check it in order to solve the problem?

Thank you

**Comment by dmihos** [comment]
Hi jimanis
You seem to be opening Orders on Default source, that's why the urls of source 2356 are not used after the payment.
You need to use SourceCode 2356 during CreateOrder api call.
Please take a look at 
https://github.com/VivaPayments/API/wiki/CreateOrder
https://github.com/VivaPayments/API/wiki/Optional-Parameters

**Comment by jimanis** [comment]
In example you have for php the variable for Source is wrong
You have:
$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.'&RequestLang='.$RequestLang.'&Source='.$Source;

You sould have:
$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.'&RequestLang='.$RequestLang.'&SourceCode='.$Source;

**Comment by dmihos** [comment]
Thanks for letting us know
