### ISSUE TITLE
Pay with Viva Wallet code jquery error wordpress

### ISSUE THREAD

**Issue by dmilio** [VivaPayments/API#348]
Έχουμε ενεργοποιήσει την υπηρεσία Native/Pay with Viva Wallet checkout από το διαχειριστικό σας περιβάλλον και όταν εισάγουμε τον παρακάτω κώδικα στην σελίδα δεν εμφανίζεται το κουμπί του Pay with viva wallet

<script src="https://www.vivapayments.com/web/checkout/js"> </script> 
<form action=/charge" method="POST">
<button
    type="button"
    class="simple"
    data-vp-publickey="TO_API_KEY_ΜΑΣ"
    data-vp-lang="el"
    data-vp-description="Friendly description for you customer"
    data-vp-amount="2000">
</button> 
</form>

Η σελίδα έχει υλοποιηθεί σε wordpress και έχουμε εισάγει τον κώδικά είναι στη σελίδα http://movingminds.gr/test-page/ . Στην ιστοσελίδα δεν είναι εγκατεστημένο κάποιο ecommerce platform. Θέλουμε να εμφανίζουμε σε συγκεκριμένες σελίδες το pay with viva wallet με διαφορετικό ποσό και αιτιολογία που θα ορίζει ο διαχειριστής της σελίδας (όπως https://www.vivawallet.com/el-gr/business/e-shops/pay-with-viva-wallet)

![2b22cbf8-e5ca-4d86-a779-edc74671612a](https://user-images.githubusercontent.com/3342870/27858693-d61d6cd6-617e-11e7-96ce-4518788c1895.png)

Το error console εμφανίζει VivaPayments.js requires jQuery, αλλά το jquery φορτώνεται ήδη στη σελίδα.

**Comment by dmihos** [comment]
The jQuery script reference should precede the VivaPayments.js (jQuery should already be loaded for our script to run)

**Comment by acicovic** [comment]
Hi @dmihos,

In the site of @dmilio jQuery is declared before Viva so the issue is somewhere else. The page is still there so you can view it in the source.

We have the same problem using WordPress with the Divi theme. The issue is present even though jQuery is declared well before the Viva script declaration. Declaring the Viva script in the <head> (after jQuery declaration) or the <body> elements does not have any difference. Viva still fails to see jQuery.

It seems to me that your script finishes loading before jQuery has finished loading, and thus it cannot find it. Perhaps using a jQuery(document).ready in your code could solve the issue.

Thanks.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
