### ISSUE TITLE
OrderCode returns as a float on 32bit php

### ISSUE THREAD

**Issue by nickgardos** [VivaPayments/API#37]
Because of the fact that the OrderCode is now a 64 big integer, when I am json decoding the response of vivapayments on a 32bit system, it shows up as a float. Is it possible for you to return the code as a string and not as an integer, so 32bit systems can parse it?

**Comment by dpnevmatikos** [comment]
Hi there @nickgardos ,
Could you try parsing the order code using the method suggested [here](http://php.net/manual/en/function.json-decode.php) at Example #5 ?

There is also an [active PR](https://github.com/VivaPayments/API/pull/36/files) created recently by another dev who, I'm guessing, observed the same behavior and used the above solution. 

Unfortunately we cannot provide modifications to our JSON responses because existing 3rd party clients with our services would break.

Please let me know if the above solution works for you.

**Comment by nickgardos** [comment]
The JSON_BIGINT_AS_STRING flag fixed the problem. Thank you very much.

**Comment by dpnevmatikos** [comment]
:+1:
