### ISSUE TITLE
Viva Wallet Prestashop module installation issue.

### ISSUE THREAD

**Issue by globaltechgr** [VivaPayments/API#396]
Hello,

in order to install the Viva Wallet module for Prestashop for one of our customers, we download the files found in https://github.com/VivaPayments/API/tree/master/Plugins/prestashop/vivawallet.
We follow the instructions and when we install the module through the module manager we get nothing. All we see is the error shown below.

![vivawallet](https://user-images.githubusercontent.com/32466052/31094891-600c8fcc-a7bf-11e7-8a7b-e152818c12b6.png)

Is there something more we should do about it?

Thank you in advance.

**Comment by VivaWalletSupport** [comment]
Check if the file exists on the given location and if the folders / files have the right permissions (on LAMP 755 for folders and 644 for files).

**Comment by globaltechgr** [comment]
Hello.
We did repack the github folder in viva-payment.zip and as soon we run the installation from module manager we get redirected to http://plusseventeen.gr/admin994u2cc97/index.php?controller=AdminModules&token=d3609dad5fb9174117730385ef071775
(Attachment 1)
![vivawallet-1](https://user-images.githubusercontent.com/32466052/31407503-cf64979e-ae0d-11e7-9823-759d05ab1711.png)

So I went a created the folder modules/vivawallet and uploaded the folder content there with the appropriate permissions (Attachment 2)
![vivawallet-2](https://user-images.githubusercontent.com/32466052/31407538-eaa00962-ae0d-11e7-992e-f8d7a922f862.png)
, but when we access module manager we see the error in attachment 3.
![vivawallet-3](https://user-images.githubusercontent.com/32466052/31407546-ef40932e-ae0d-11e7-8538-1b982dfb57e8.png)
How can we proceed from there?
Thank you in advance,
Giannis Valassis

**Comment by VivaWalletSupport** [comment]
Could you email me FTP and admin access to tom at hellasboost dot gr to have a look?

**Comment by globaltechgr** [comment]
Hello.

I have email you the login credentials you will need.

**Comment by VivaWalletSupport** [comment]
Probably you saved the content of the vivawallet directory as a zipped package and not the directory. When opening your saved zipped package it must contain the folder vivawallet with inside all the files,

**Comment by globaltechgr** [comment]
Hello, I'm attaching the zipped file we used.
[viva-payment.zip](https://github.com/VivaPayments/API/files/1376297/viva-payment.zip)

**Comment by VivaWalletSupport** [comment]
Don't know how you downloaded the files that you have in your zip, but the do not contain the correct contents. Have a look for example at the vivawallet.php file that should contain following code: 
https://github.com/VivaPayments/API/blob/master/Plugins/prestashop/vivawallet/vivawallet.php

**Comment by globaltechgr** [comment]
Hi again. As we can see in the module asks for Mechant id API key and source code. We have found the merchand id and API key but where we can find the source code?

Thanks in advance

**Comment by VivaWalletSupport** [comment]
See the readme.txt

Vivawallet setup:
You can find your Merchant ID and API Key when you login your business account under Settings - API Access.

To connect the plugin with your e-commerce platform and Vivawallet you would have to create a new Payment Source in your Vivawallet business account, use the generated source code (usually a four digit number) in the plugin settings.

You can create a new Payment Source from the menu My Sales - Payment Sources - New Website/App.
Code - use this code in your plugin
Source Name - provide a logic name here
Linked Wallet - link the payment source to the wallet you want to use with it
Protocol - in case your e-commerce platform uses SSL on the checkout select https, otherwise use https
Integration method - redirection
Company Logo - your png company logo to display on the Vivawallet payment page
Success URL - as described in the plugin instructions
Failure URL - as described in the plugin instructions
Advanced Configuration - usually no need to make any changes here

Wait until Vivawallet has activated your newly created Payment Source before activating the plugin in your e-commerce platform.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
