### ISSUE TITLE
Problem with analytics report

### ISSUE THREAD

**Issue by SonataAmanes** [VivaPayments/API#501]
Hello,

I am using viva payments for a customer's ecommerce website.
The problem is that all orders that are paid through viva payments are attributed to vivapayments.com/referral as the source/medium in analytics.
As there is a significant percentage of orders that are completed through viva payments, it is a major issue that does not allow us to have proper data and analyze our advertising strategy.

Please let me know how I could fix this.

Thanks in advance

**Comment by kostGX** [comment]
This happens because you are redirected from vivapayments.com as you have probably implemented a  Redirect Checkout solution.

You could try catching the abandoned checkouts with UTM tags, in order to know:
- How many people you send to cart
- How many people abandon the cart

Otherwise I suggest using Simple Checkout, where the customer won't leave your website to complete the payment.
