### ISSUE TITLE
Phone parameter

### ISSUE THREAD

**Issue by GRANDX1** [VivaPayments/API#557]
We are trying to get PHONE parameter for the payment via API but get NULL. Can you please, advise the name of this parameter?

Thank you

**Comment by Sotiris-k** [comment]
I suppose that you're talking about the Native Checkout API.

To get the Phone info first of all you need to have included it during your Order creation process otherwise it will be unavailable. Secondly, it is included in the transaction payload. Info for getting the Transaction can be found [here](https://github.com/VivaPayments/API/wiki/GetTransactions)
