### ISSUE TITLE
Δεν γίνεται το redirect πίσω στο site, παρόλο που η πηγή πληρωμών είναι οκ!

### ISSUE THREAD

**Issue by bluemyria** [VivaPayments/API#57]
ΑΦΜ: 099766080

Αναφερόμαστε στην πηγή dev2.xorafaki.gr   Κάναμε πληρωμή χθες και πάλι δεν έγινε redirect παρόλο που το support μας επιβεβαίωσε ότι όλα είναι εντάξει. Θέλουμε να βγούμε live σε λίγες ώρες, ελπίζουμε με viva!

Ευχαριστώ

**Comment by dmihos** [comment]
Καλησπέρα bluemyria

Κοιτώντας το λογαριασμό σας, βλέπουμε κάποιες συναλλαγές που έγιναν στο source Default, το οποίο δεν έχει το url dev2.xorafaki.gr.
Θα πρέπει, κατά τη δημιουργία του Order, να περνάτε το SourceCode της εκάστοτε πηγής που θέλετε να χρησιμοποιήσετε
https://github.com/VivaPayments/API/wiki/CreateOrder
https://github.com/VivaPayments/API/wiki/Optional-Parameters (property SourceCode)

**Comment by bluemyria** [comment]
Καλησπέρα,

ευχαριστώ για την απάντηση. Επειδή το documentation είναι κάπως αόριστο 
(SourceCode ( string ): Sources can be created and managed from the merchant's profile. A source is used for grouping and filtering transactions (ie a merchant may have more than one websites, or different product categories).) υπέθεσα αφού ανέλυσα και το παράδειγμα εδώ: https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php
ότι πρέπει στα $postargs  να προσθέσω ένα &SourceCode='xxxxxxxx'; Στο παράδειγμά σας το 'xxxxxxxx' είναι  'Default'. Στην περίπτωση μας υπέθεσα ότι το string που χρειάζεται είναι ο τετραψήφιος αριθμός στη στήλη 'Κωδικός' των Payment Sources. δηλ '1234' 

Καταλαβαίνω ότι για σας είναι προφανές αφού δουλεύετε με τον κώδικα κάθε μέρα. Για μας που χρειάζεται να κάνουμε μια φορά setup δεν είναι. Λίγο πιο καλό documentation (με μερικά παραδείγματα) βρε παιδιά θα βοήθαγε όλους! το γράφω εδώ γιατί μπορεί να το χρειαστεί και κανείς άλλος (ίσως και εγώ στο επόμενο project)

Και πάλι ευχαριστώ για την απάντηση

**Comment by dmihos** [comment]
Καλησπέρα bluemyria

Στον οδηγό του [Redirect Checkout](https://github.com/VivaPayments/API/wiki/Redirect-Checkout), στο section 3, αναφέρεται η σχέση του Source με τα Redirect urls
>
Upon completion of the checkout form, the customer is redirected back to your website. The redirection URLs are defined in your vivapayments.com account under the Sources section.
>
Note that the redirection always happens at the 'Source' level. If you have defined multiple sources on your profile, you need to use the optional parameter 'SourceCode' when creating the order, so that the system selects the appropriate redirection url.

Ωστόσο, σημειώνουμε το σχόλιό σας ότι δεν είναι αρκετά σαφές.

**Comment by bluemyria** [comment]
ναι αλλά **πώς** θα είναι ακριβώς αυτή η παράμετρος SourceCode δεν είναι προφανές, χρειάζεται ψάξιμο! αυτό σας λέω! Βάλτε ένα παράδειγμα με ένα screenshot για να καταλάβουν και οι πελάτες σας ότι πρέπει να βρούν το περιεχόμενο της στήλης "κωδικός" του payment source από το https://members.vivawallet.com/selfcare/el-gr/sources/paymentsources για να τον βάλουν σαν string. Ελπίζω τώρα να έγινε σαφές τι εννοώ

**Comment by bluemyria** [comment]
Πάντως θα ήθελα να ευχαριστήσω για την άμεση ανταπόκριση, βγήκαμε live και όλα είναι μια χαρά με τη σύνδεση στη viva!
