### ISSUE TITLE
Monthly Subscription 

### ISSUE THREAD

**Issue by socialmegr** [VivaPayments/API#633]
Hello,

I need to know if viva wallet supports automated monthly payments. I need to create for my website a ticket that will be sent to my client where he can sign up and fill in his credit card information. After that, monthly payments will be done automatically.
How can we do this?

**Comment by kostGX** [comment]
Hello,

We support **Recurring Payments** but we don't offer an out of the box subscription management service.

Recurring Payments means that you can charge a card again and again (on monthly or adhoc basis).
In order to implement automated monthly payments you'd have to implement the following flow:
1) Get your customer's card info and make a charge for a recurring transaction, in order to get the token/transaction_id you need to charge the same card again in the future (when there's billing to be invoiced)

2) Refund the initial charge to the user so they don't feel like you stole from them.

3) Have a cron job or a scheduling mechanism in place that every day checks which billing cycles close (30 days since initial transaction date) and charge them.

Hope the above makes sense.

Thanks!
