### ISSUE TITLE
Error : Signature not verified

### ISSUE THREAD

**Issue by ProjectPuntr** [VivaPayments/API#651]
I followed the steps that have been outlined here: 
https://github.com/VivaPayments/API/wiki/Shopify-Integration

My merchant ID and Store token has been added to Shopify Viva Wallet payment. 

I then  go onto my shop and push "complete Order" on the shopping cart it then redirects me and gives the a loading screen that says redirecting and then comes up with a screen saying ERROR signature not verified

**Comment by kostGX** [comment]
Hello @ProjectPuntr, please verify that you have pasted correctly the store token and merchant id values as sent by our support team.

This means that Shopify can't tie this to a verified token, which usually happens because of copy pasting wrong things.

Please let me know if the problem persists.

**Comment by ProjectPuntr** [comment]
We have tried multiple times (10-15).
The store token looks like this:
![storecode](https://user-images.githubusercontent.com/20397962/49292528-6967ed80-f4a5-11e8-9845-e137eb189505.PNG)
Please see the attached image.  The code begins with a character than can't be copied and pasted.
The first character becomes a 'd' instead of the character I was given.
e.g: Pasted Store Token: d*wHv
Is there a way we can get a store token without greek letters to try?

**Comment by kostGX** [comment]
@ProjectPuntr this seems like an API key, not a Store Token (please edit your comment and delete the picture for your safety)

Store tokens look like this: Z5hYbDf71Zeee2qRGIJcJc8$y7dsaca1

**Comment by Alisoncoins** [comment]
Hello guys I'm having the same issue it says (Signature not verified) after clicking complete purchase.
I was provided with this store token 62fT6BT does it look correct because it seems short compared to the example @kostGX provided....

:-( 

is this bug because my documents didn't get verified yet????? I've noticed when I click edit on the shopify vivawallet payment settings the store token isn't saved by shopify but my merchantID is still saved.
