### ISSUE TITLE
Transaction id null

### ISSUE THREAD

**Issue by WebWars** [VivaPayments/API#673]
Hello,

I am using Native Checkout and will on the demo account everything runs smoothly on production nothing come to transactions table although it seems everything is ok. I noticed that I don't get any transaction id from the js part

`{"Token":"aIhwc3yNL9RnJCvnE5I7NBJ8ZzH8/frvv3Xz/cCeNmAT5Fj5vKNlXyfsCcSMwqolpeYriELeYgAuIHs7/H67XBh2znBwhizsR3LtaNA5rei9Bp0zm5qVJdDvpDQr1ZK0kv4R2/RuDUPDpYeM9W4f21Eoz+wipw/NGQQmtJvnigRQ83QNjxwKPMft5Jh3XfMXdVcgM2SP6x7Pvvbpdo8x7m3ms2wtdgi3iKihVjHQNNN9kdmyf5slhWyuN4YSUbzRgi3n1vgI3WIuGVrTcT0Vlav4yUIwvgZNk4xE+q3slYZhCE0ABxstei1CSjUKAU/5Y2h0sG2B+om1u0Z9+Hwz6OPukkfkWEzt","TransactionId":null}`

Any ideas what might be wrong? I triple check public key and also added the domain under website/apps correctly.

Thank you in advance

**Comment by kostGX** [comment]
@WebWars hi,

You are on the right track. You don't need a transaction ID at that point. You only need the "charge token" you're getting.

Now you need to POST this token in order to proceed with the charge, as described here: 
https://github.com/VivaPayments/API/wiki/Native-Checkout#call-the-api-to-securely-process-the-payment
