### ISSUE TITLE
Εκκάθαριση συναλλαγής

### ISSUE THREAD

**Issue by pinguinlands** [VivaPayments/API#712]
Καλησπέρα σας.
Μερικές ερωτήσεις σχετικά με το plugin.
Α) Ενώ γίνεται η συναλλαγή και φαίνεται η κίνηση τα ποσά δεν μπαίνουν στον λογαριασμό. Γράφει απλά χρέωση κάρτας.
Β) Δεν γίνεται ανακατεύθυνση στην σελίδα που έχουμε δώσει. Που κάνουμε λάθος;
Γ) Στο Vivawallet Source Code. πρέπει να συμπληρώσουμε κάτι;

Σας ευχαριστώ.

**Comment by VivaWalletSupport** [comment]
Hello, could you provide some details on what plugin is used?

**Comment by pinguinlands** [comment]
Κατεβάσαμε από εδώ το plugin.
Απλά το θέμα μας είναι ότι δεν γίνεται ανακατεύθυνση στην σελίδα που έχουμε δηλώσει. Είναι κάτι που μας έχει ξεφύγει; Κάποια έξτρα ρύθμιση;
Σας ευχαριστώ.

**Comment by VivaWalletSupport** [comment]
There are a lot of different plugins available here, could you please be more specific on what plugin is used?

**Comment by pinguinlands** [comment]
Ώπα συγγνώμη!
Τώρα κατάλαβα. Wordpress - woocommerce.

**Comment by VivaWalletSupport** [comment]
You can create a new Payment Source from the menu My Sales - Payment Sources - New Website/App.
Code - use this code in your plugin (Source Code)
Source Name - provide a logic name here
Linked Wallet - link the payment source to the wallet you want to use with it
Protocol - in case your e-commerce platform uses SSL on the checkout select https, otherwise use https
Integration method - redirection
Company Logo - your png company logo to display on the Vivawallet payment page
**Success URL - as described in the plugin instructions
Failure URL - as described in the plugin instructions**
Advanced Configuration - usually no need to make any changes here

**Comment by pinguinlands** [comment]
We will try it and we'll let you know.
Thanks.
