### ISSUE TITLE
currency not supported

### ISSUE THREAD

**Issue by zorlus** [VivaPayments/API#764]
I am using viva wallet payments api on opencart 3x

I pay in GBP all is fine but when I try EUR and USD I get following error. Anyone know how to enable multicurrency?I looked all over the account settings could nto find it. 

An error occurred (Person #longnumberfortheaccount# does not support currency '978'), please contact the administrator
Please wait...

**Comment by bigtili** [comment]
Hi, I have a similar issue with WooCommerce. Did you get any reply from the support team?

**Comment by zorlus** [comment]
Hi,

Unfortunately the response rate of spam is awful. I am still waiting.

**Comment by matthewrgourd** [comment]
@zorlus @bigtili  Sorry for the lack of response previously. We are working on improving our response times moving forward. The answer to your question is, if you open a business account in the UK, you cannot capture payments in a currency other than GBP. This is due to the way Viva Wallet's accounts are set up. There are some other ways to get around this, like implementing a currency converter in the checkout, opening also a business account in a Euro country, modifying the code to change currency in the payment plugin etc. Hope this helps!
