### ISSUE TITLE
Payment form

### ISSUE THREAD

**Issue by rsanota** [VivaPayments/API#767]
Hi everyone,

I am currently using the simple checkout plugin from woo-commerce on Wordpress but I am looking to have a payment form for customers instead and not the pop-up.  Customers are abandoning the popup payment which then shows up as pending and not cancelled.

Please can someone do this for me? 

Our website is www.koicbd.co.uk

Please can anyone help?

Kind regards,

Ranj

**Comment by donfn** [comment]
Hello!
I am the author of the plugin you've mentioned.

I've checked your website and, as far as I can see, the plugin works properly.
If your customers abandon the popup due to their lack of trust,
then you should go ahead and install the official redirect implementation
of the gateway, as this is much more mainstream and trustworthy (https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce). 

I'm planning to publish a plugin for native payments with (maybe) the ability to support
the Payment Request API (https://paymentrequest.show/demo/), so keep your
eyes on the Wordpress marketplace ;) .

Thanks!

**Comment by rsanota** [comment]
Hi 

How do I download it as a zip file for woo-commerce?

Thanks,

Ranjeet

**Comment by donfn** [comment]
Here: 
[vivawallet-for-woocommerce.zip](https://github.com/VivaPayments/API/files/2936219/vivawallet-for-woocommerce.zip)
