### ISSUE TITLE
payment error in euro 

### ISSUE THREAD

**Issue by eurospania** [VivaPayments/API#774]
please help , my viva wallet  account in GB uk  it does not accept payment card in euro only in GB , when somebody paying in euro through my website  .im receiving this message : internal server error please help

**Comment by bigtili** [comment]
I have a similar problem, EUR payments on WooCommerce do not go through. I have a GBP account.

**Comment by eurospania** [comment]
and whats the solution ?

**Comment by bigtili** [comment]
@eurospania  just to check, when signing up for Viva payments merchant account, you were told that you could accept payments in GBP, EUR and USD, right?

**Comment by eurospania** [comment]
SURE. also we have vivawallet on our cyprus company and when we integrated through API to our e comerce website cards was accepted from only cyprus and greece .we opened another account for our UK company we integrated it to try .and now it accept all cards but only in GB
WE HAVE OTHER 2 payment gateways on our ecomerce website and none have a problem only with vivawallet.and the cool is that nobody want to give a correct answer or a technical answer for how to solve it out.
with other payment gateways we have transactions daily 2 to 3 k .we wanted to work with vivawallet but they does not solve out this problem for us. and even no answer at all correct.

**Comment by bigtili** [comment]
Thank you for your answer. I've sent an email to a senior contact at Viva regarding this. Will let you know when I have something.

**Comment by kostGX** [comment]
Hello @bigtili,

Sorry to have had you waiting.

At this time it's only possible to accept payments in the same currency as your account.

Therefore if you've got a GBP account, you can only accept GBP payments, and consequently we can only clear to you GBP (during our daily payouts process).

As we currently stand, in order to accept both GBP and EUR with Viva Wallet, you will have to have a second EUR account (offered in France, Belgium, Italy, Cyprus and more countries coming soon).

Multi-currency is definitely within our plans but cannot provide you with a concrete timeline right now.

Apologies for any inconvenience this may causes.

**Comment by eurospania** [comment]
sir we have another account viva wallet for cyprus Euro also  , and also we faced a problem and nobody helped ,  when we integrated vivawallet into our website we faced another problem that only cyprus and greek card payments was accepted and when a client internationally was processing a card payment through viva wallet 
he was receiving this message saying that the card not from Greece .
please help. as nobody helped us since we started with vivawallet.

**Comment by kostGX** [comment]
@eurospania regarding the restrictions of charging cards from other countries you should contact merchants@vivawallet.com and request for these restrictions to be lifted from your account.

(This has to do with Risk department)

Hope this helps,
Kostas

**Comment by eurospania** [comment]
we still have problem , now we can accept payment form all countries but most payment when client press to pay it comes the page with 3d secure and then no payment can be proceeded
is there any kind of extra secure from viva wallet for 3d secure that can be removed?

**Comment by kostGX** [comment]
@eurospania I just checked your transactions. You have made many successful transactions and 5 of them were rejected.

Rejections come from card issuers for various reasons.

One of your transactions was rejected because the card didn't have sufficient funds.
The other 4 were rejected with the 05 Do Not Honor rejection reason. 

Issuers will often default to “Do Not Honor” as the catch-all for all denials. Do Not Honor is oftentimes used by issuers to indicate insufficient funds or possible fraud. You should advise your customers contacting their bank and asking to lift any possible restrictions on their cards.

This doesn't have to do with 3D Secure. 3D Secure is there to protect our merchants from receiving disputes.

**Comment by eurospania** [comment]
thanks.so much I will talk to my seller and forward your answer .and to keep working maybe its client problem as you said.

**Comment by eurospania** [comment]
Mr kostas. please find me a solution at least to send a pop up message when transaction card not approved  , now if the transaction on viva wallet did not pass ,we don’t have any message from viva wallet.
is there any option that you can help ? because client does not know what it is going on , we don’t have any pop up message from viva wallet to say that transaction not approved . please help

**Comment by nagleator** [comment]
Hi @eurospania, were you able to accept Euro payments in the end? Have the same issue with our UK company accepting Euro payments, customers are charged in sterling.

**Comment by eurospania** [comment]
on uk account vivawallet cannot accept euro

**Comment by nagleator** [comment]
That is very annoying, I didn't think it would be a big deal for Vivawallet to charge customers in euro, I don't mind accepting sterling but to charge customers the euro amount.

**Comment by eurospania** [comment]
With vivawallet is a big deal


The world of BingoSpania

**Comment by nagleator** [comment]
Were you able to create a euro account with your UK company?

**Comment by eurospania** [comment]
Not possible


The world of BingoSpania

**Comment by eurospania** [comment]
Hello mr Costas, we have the same problem with the transactions , many cards are declined , my seller check same card on another payment gateway and all of them are successfully accepted,
could you please tell me why ? or find out a solution ?
Best Regards,
