### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by deniseking2506** [VivaPayments/API#816]
The customer is asked to add their email address and phone number  at the woocommerce check out page but when they are sent through to Viva Wallet, the email address is taken through but not the phone number.  The customer is asked again for their phone number on the viva wallet page, but this time it says with prefix.  If you add a phone number with the country's prefix, which I am assuming is what this means, the phone number is rejected as invalid.  This is really annoying.  Should the phone number be taken through to the viva wallet page?  deniseking2506@gmail.com

**Comment by VivaWalletSupport** [comment]
Hello, as the phone number at the payment page from Viva requires a specific format and because (default) WooCommerce does not validate the billing phone number for this specific format, this field is not included as a parameter (not causing an error at the Viva payment page).

Feel free to implement your custom validation in WooComerce and to use the phone number in the plugin as an extra parameter besides the email parameter.

For more info have a look at:
https://developer.vivawallet.com/api-reference-guide/payments-api/create-order/#optional-parameters

In case this solves your problem, please close this issue.

**Comment by deniseking2506** [comment]
Thank you for getting back to me - much appreciated.  Unfortunately, I haven't got a clue what the link is referring to and I really don't want to dabble with code.  I am a novice and amazed I have got this far - thank goodness for plug-ins!  Viva requests the phone in a different format, but won't accept it - this is my main problem.  Viva asks for the phone number with a prefix which woocommerce doesn't - I am assuming this is the country prefix - yet when input in this format, viva rejects it. 
![viva phone number prefix problem](https://user-images.githubusercontent.com/49521601/56188614-e394ab00-601d-11e9-8769-87867858d45d.png)

**Comment by VivaWalletSupport** [comment]
Change the plus sign for 00, like the example given before filling the field.

**Comment by deniseking2506** [comment]
Hello Tom

I have only just understood the example phone number!  Am I the only one to have problems with this?  I am concerned that customers are going to do the same thing.

By prefix, I would assume it meant +44, otherwise you could just input an ordinary phone number and it would accept it. 

Is there any way around this at all?

Thank you for your patience.

Denise

Sent from Mail for Windows 10

**Comment by VivaWalletSupport** [comment]
The only way would be to modify WooCommerce with the phone validation and to add the phone number in the payment plugin. You might have to contact a developer for this.

**Comment by deniseking2506** [comment]
OK thank you.
