### ISSUE TITLE
Shopify - Incorrect Currency Charged

### ISSUE THREAD

**Issue by nagleator** [VivaPayments/API#822]
I have a UK company and an account set up with VivaWallet. The prices on my site are in Euro. However when it comes to paying, ViaWallet takes the euro amount and charges the exact same in sterling, oppose to finding an exchange rate. So now I have customers being charged more than they should.

How can I charge the customers in the euro amount? I don't mind if Viva wallet convert this to sterling in the backend. But I can't be charging customers extra.

**Comment by kostGX** [comment]
Hello @nagleator,

For the time being we don't support multi-currency clearing/charging of card payments.

This means your account can only charge in GBP as the country of your company's incorporation is the UK.

If you would like to charge your customers in EUR, you then need to create another account in EUR (which means that you also need to have a company incorporated in a EUR country.

Here's how to create an account for another company: https://vivawallet.zendesk.com/hc/en-us/articles/360001348378-How-can-I-add-a-new-business-to-my-account-

Otherwise, you need to setup your Shopify store to display prices in GBP.

Hope this answers to your question,
Kostas

**Comment by nagleator** [comment]
Hi @kostGX 

Thanks for getting back to me! 

Gotcha, but is it not possible to convert the EURO amount on shopify to a sterling amount, and then charge that sterling amount to our customers?

Oppose to what is happening now
