### ISSUE TITLE
Απενεργοποιηση Τηλεφωνικής πληρωμης

### ISSUE THREAD

**Issue by geoverik** [VivaPayments/API#839]
Απενεργοποιηση Τηλεφωνικής πληρωμης. Ivr
Καλησπέρα
Πως μπορω να απενεργοποιηθεί η επιλογή IVR για το το redirection απο magento εκδοση 1.9;

**Comment by kostGX** [comment]
Κατα το create order στον κωδικά σας περάστε την ακόλουθη παράμετρο.

DisableIVR - boolean - If this parameter is passed with value true, the customer will not have the option to pay over the phone (IVR).

**Comment by geoverik** [comment]
Σε ποιο σημειο του Magento πρεπει να προστεθει ? Μπορειτε να μου  
δωσετε ενα παραδειγμα ?
Παραθέτοντας από Kostas Xiradakis <notifications@github.com>:

**Comment by VivaWalletSupport** [comment]
Hello, \app\code\local\Mage\Vivawallet\Model\Hpay.php line 216 - change to:

$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300&DisableIVR=true';

Please close this issue if that solves your problem, otherwise let me know how I can help.
