### ISSUE TITLE
Cant get vivawallet as an option on shopify dropdown payment provider menu

### ISSUE THREAD

**Issue by thelittlecbdcompany** [VivaPayments/API#892]
I have tried to intergrate vivawallet on my shopify website www.thelittlecbdcompany.com

On step 6 of intergrating the site I have to select a payment provider. On the drop down selection there are lots of payment providers to choose from but vivawallet isnt one of them.

When I intergrated my other web site the option was there and the process was simple.

can you help please

regards

mark 07870 689482

**Comment by matthewrgourd** [comment]
Hi Mark, sorry you're experiencing issues with adding Viva Wallet to your Shopify website. Can you confirm that after navigating to **Settings/Payment providers** you then opened http://www.shopify.com/admin/authorize_gateway/1041324 in the same browser window? This should display the *Recently accessed stores* page. Now, steps 6 and 7 are the same but I've slightly modified the procedure from step 8 onwards. See if this makes any difference otherwise I will escalate the issue. Thanks!

6. Click on your store to display the pre-installation page:<br />
![Pre-installation page](https://developer.vivawallet.com/images/ShopifyYouAreAboutToInstallVivaWallet.png?classes=border&width=900)<br /><br />
7. Click on the **Install payment provider** button. A confirmation popup will be displayed:<br /><br />
![Shopify Activation Message](https://developer.vivawallet.com/images/VivaWalletActivation.png?classes=border)<br /><br />
8. One of the following will happen:
  - The Viva Wallet payment provider settings will be displayed immediately.
Go straight to step 9 below.<br /><br />
  - The *Payment providers* page will be displayed.
    - Click on the **Add a provider** button to display the *Change provider* dialog box.
    - Select the **Third party credit card provider** radio button then choose **Viva Wallet** from the 'Provider' dropdown.
    - Click on the **Continue** button to display the Viva Wallet payment provider settings.
    - Now go to step 9 below.

9. In the **MerchantId** and **StoreToken** fields, enter the relevant details from Viva Wallet.

10. Click on the **Activate** button and an activation message will be displayed:<br />
![PaymentSettingsSaved](https://developer.vivawallet.com/images/PaymentSettingsSaved.png?classes=border&width=200)<br />On the *Payment providers* page, Viva  Wallet is now listed in place of Shopify Payments:<br />
![Payment Providers Viva Wallet](https://developer.vivawallet.com/images/PaymentProvidersVivaWallet.png?classes=border&width=900)<br />You should also receive an email from Shopify confirming the change.

11. Go to **Settings > General > Currency** and set the currency of your Shopify store to one of the currencies supported by Viva Wallet:
  - **Euro (EUR)**
  - **British pound (GBP)**
  - **Romanian leu (RON)**

12. Click on the **Save** button.<br />The Shopify integration is now complete. You can start receiving payments through Viva Wallet!

**Comment by thelittlecbdcompany** [comment]
Thats great thank you,

I just need to get a shop token to complete the procedure. would you know
how to get one of those to put in alongside my merchant number.

thanks again for your help

**Comment by matthewrgourd** [comment]
Hi there, you need to complete and send the below form for a Shopify token:

https://viva.microsoftcrmportals.com/shopify

Thanks,

Matt
