### ISSUE TITLE
Woocomerce Fails Redirection Page 

### ISSUE THREAD

**Issue by PhilipBmlab** [VivaPayments/API#904]
Hey I put as Failure URL mydomain.com/checkout page but when I fail a payment your plugin put 4 parameters in url  so I take 404 error 

the url : **mydomain.com/checkout/?payment-error_&s=7590165094072603&lang=en-US&eventId=0**

The problem is the letter 's' in parameters when I delete it or delete it's value the page runs correct!
I think 's' parameter in wooommerce - wordpress is for search and so if you put s=xxxxxx in my url its normal to get 404 error.

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you've been having issues. I think what you need to do is enter `index.php?wc-api=wc_vivawallet&vivawallet=fail` for the failure URL. This is what is stated in the [integration instructions](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/). Please let me know if any further problems otherwise close the issue if it has been solved. Thanks! Matt
